### ISSUE TITLE
Millorar accessibilitat dels editors TinyMCE

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/rolsac#1]
Numero: 579
Creació: 2016-02-12 11:12:02.184
Els editors TinyMCE integrats em les pantalles "Unitat Administrativa" i "Fitxes informatives" generen codi no accessible.
Es sol·licita analitzar si la migració cap una versió més actualitzada soluciona el problema o altres alternatives tipus editors Markdown.
En l'analisi s'ha de tenir en compte l'adaptació/correcció del codi existent en aquest tipus de camps

**Comment by rsanz-indra** [comment]
Se cierra la tarea, ya que se crearon las respectivas issues para cada uno de los cambios a realizar.
