### ISSUE TITLE
No se pueden eliminar las competencias por materias de las unidades orgánicas.

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/rolsac#17]
Numero: 565
Creació: 2014-04-30 10:13:52.000
No se pueden eliminar las competencias por materias de las unidades orgánicas en la pantalla:
http://sdesapplin12:58080/rolsacback/unitatadm/unitatadm\.do

El problema esta tanto en 1\.2 como 1\.3

A veces indica se da un error servidor, y no borra nada\. Y en otras parece que las borra pero si vuelves a entrar ha borrado alguna menos una\. 

Para poder probarlo debe ser con un rol RSC\_ADMIN o RSC\_SYSTEM\.\. el RSC\_SUPER no debe poder cambiarlas\.

**Comment by kitanibaladmin** [comment]
amartin
2014-05-29 09:51:03

**Comment by kitanibaladmin** [comment]
amartin
2014-05-29 09:53:12
Hola, Estela:

He subido el archivo materias\_relacionadas\.png\. Supongo que te refieres a la relación de la UA con esos elementos\.

He hecho pruebas de eliminación y añadir nuevos elementos tanto en ROLSAC 1\.2 como en 1\.3 sin ningún problema\. ¿Podrías pasarme los logs del servidor donde tú lo pruebas? ¿Es posible que sea algún error debido a vuestro entorno de base de datos?

Un saludo\.

**Comment by kitanibaladmin** [comment]
estelars
2014-07-01 11:01:36.305000
Es un error intermitente.. es decir A veces ocurre y otras no. Con lo que no puedo indicarte claramente lo que ocurre. 

Una forma que lo he reproducido siempre es si le quito todas las competencias de golpe a la unidad. En cambio si lo hago en dos fases va bien.

**Comment by kitanibaladmin** [comment]
estelars
2014-07-01 11:02:36.846000
- **assigned_to**: Estela (DGTIC) --> Toni García Marí
- **Group**:  --> Next Release (example)
- **Reproducibility**: always --> Always

**Comment by igomezd-indra** [comment]
![17-1](https://cloud.githubusercontent.com/assets/18310919/14740540/078751fe-0890-11e6-8626-57064c1a5b57.png)
![17-2](https://cloud.githubusercontent.com/assets/18310919/14740556/2782de42-0890-11e6-8e75-a4e6748911f8.png)
![17-3](https://cloud.githubusercontent.com/assets/18310919/14740559/2b7368a0-0890-11e6-9fb5-dd018bab0da4.png)

**Comment by igomezd-indra** [comment]
Se accede al detalle de la unidad, se desmarcan todas las materias relacionadas y se guarda, cuando volvemos a acceder al detalle seguian saliendo.
