### ISSUE TITLE
Analitzar la indexació d'informació amb Lucene

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/rolsac#2]
Numero: 578
Creació: 2016-02-12 09:44:37.894
Es sol·licita analitzar la indexació de continguts que s'està realitzant amb Apache Lucene amb l'objectiu de millorar les cerques sobre continguts ROLSAC.
Avaluar la incorporació d'altres alternatives com SOLR

**Comment by sgelabert-dgtic** [comment]
Es decideix emprar SOLR com a sistema d'indexació de continguts de ROLSAC
