### ISSUE TITLE
Modificar mòdul auditories

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/rolsac#3]
Numero: 577
Creació: 2016-02-12 09:33:31.657
Modificar el mòdul d'auditories que apareix en les pantalles de "Unitat Administrativa", "Procediments", "Fitxes informatives" i "Normativa"
* Afegir una columna amb el nom i llinatges de l'usuari auditat. Aquesta informació s'ha de recuperar de la taula RSC_USER. En el cas que ja no existeixi l'usuari dins la taula, perquè s'hagi eliminat, la columna ha d'apareixer la cadena "Usuari donat de baixa"
* Eliminar el control sobre la visualització del mòdul d'auditories per rol d'usuari, és a dir, obrir-ho a tots els rols.

**Comment by mcgonzalezu-indra** [comment]
Añadimos la columna NOMBRE, con el nombre y apellidos al modulo Auditorias.
![image](https://cloud.githubusercontent.com/assets/18311022/14777335/ab4a43bc-0acc-11e6-9f89-a74f8a639ce5.png)

**Comment by mcgonzalezu-indra** [comment]
Si se borra usuario para el que se han insertado registros en la auditoria debe aparecer la descripción "Usuario dato de baja"

**Comment by mcgonzalezu-indra** [comment]
![image](https://cloud.githubusercontent.com/assets/18311022/14777381/fc09649a-0acc-11e6-8394-42a531fc3d4e.png)

**Comment by mcgonzalezu-indra** [comment]
Éste modulo de auditorias esta incluido en "Unidad Administrativa", "Procedimientos", "Fichas informativas" y "Normativa". Antes se veía únicamente si el usuario era administrador. Ahora se ha quitado ese control y lo verán todos los usuarios.

**Comment by episano-dgtic** [comment]
En general bien, sólo un par de puntualizaciones:
1) En las unidades orgánicas no se ve el módulo de auditorías para todos los roles (lo he probado rol supervisor)
2) Se podría hacer que la columna usuario no fuera tan amplia. Ya que mayoritariamente será el código (unos 10 carácteres) o el texto "usuario dada de baja". Por otro lado, si el campo fecha ocupa una única línea tal vez quede mejor...

**Comment by episano-dgtic** [comment]
REPITO: Me darás un usuario de vuestro sistema que tenga un rol RSC_SUPER  y otro con el rol RSC_OPER con sus respectivas contraseñas.. y así testear cosas que tengan que ver con los roles.

**Comment by dmadronal-indra** [comment]
Enviados por correo.

**Comment by episano-dgtic** [comment]
perfecto
