### ISSUE TITLE
Manteniment d'espais territorials

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/rolsac#329]
Numero: 588
Creació: 2015-06-24 07:28:20.000
No funciona la definició de la jerarquia d'espais territorials.

**Comment by igomezd-indra** [comment]
![329-1](https://cloud.githubusercontent.com/assets/18310919/14740698/2dbf0dde-0891-11e6-90ec-ad98a6db60ca.png)
![329-2](https://cloud.githubusercontent.com/assets/18310919/14740699/2dc4df34-0891-11e6-9edb-85a769a42cfa.png)

**Comment by igomezd-indra** [comment]
Se accede a espacios territoriales, tiene como padre el raiz, pulsamos cambiar padre y seleccionamos uno de la lista que no sea el raíz, guardamos y no lo cambiaba.

**Comment by sgelabert-dgtic** [comment]
No funciona el boto tornar
