### ISSUE TITLE
Anàlisi SOLR per a la indexació i cerca de continguts

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#341]
Es sol·licita iniciar tasca d'anàlisi per a la indexació i cerca de continguts mitjançant tecnologia SOLR. Temes a tenir en compte:
- Analitzar les entitats que s'indexen actualment a ROLSAC (Unitats Administratives, Procediments, Fitxes i Normativa), els camps que s'indexen en cada entitat i la forma en què s'emmagatzemen finalment sobre l'índex (creixement i la informació que es vol recuperar).
- Avaluar la indexació de noves entitats, eliminar-ne d'obsoletes i contemplar la indexació de documents relacionats amb entitats.
- Oferir procediment/mecanisme per ampliar/reduir els camps a indexar.

**Comment by sgelabert-dgtic** [comment]
Afegeix-ho aspectes a tenir en compte en l'anàlisi degut als canvis de l'inventari de procediments:
- Les entitats relacionades amb un procediment (tràmits, documents, etc.) s'indexarà/desindexarà en funció de la visibilitat del procediment  (estat + data publicació + data caducitat)
- S'elimina la indexació de "Fets Vitals" relacionats amb el procediment
- S'afegeix "Servei responsable" del procediment com a dada dins el SearchTextOpcional
- El camp "Descripció" d'Unitats Administratives, Fitxes, Procediments i Tràmits seran tractats com a camps no requerits en el model de SOLR. Els resultat de cerca, presentaran el camp "Descripció" únicament si s'ha emplenat en el backoffice.
- El camp "Observacions" del Tràmit (antic camp "Descripció") serà indexat dins SearchTextOpcional i no a apareixerà com a resultat de cerca.
- El pes de la informació del Procediment ha d'estar per sobre a l'assignada als documents dels procediment, tramits i documents del tràmit.

**Comment by rsanz-indra** [comment]
En la fase de análisis se especificó  lo siguiente respecto al peso para todos los documentos (de procedimiento, trámite, normativa, etc.):
"Los documentos deberían tener menos peso que las entidades ROLSAC"

Respecto al último comentario:
"El pes de la informació del Procediment ha d'estar per sobre a l'assignada als documents dels procediment, tramits i documents del tràmit."

Entendemos que se indica que el peso debe variar según el tipo de entidad (de mayor a menor):
 1) Procedimientos / Fichas / Normativa / Unidad Administrativa
 2) Trámites
 3) Documentos (procedimiento, trámite, normativa, etc.)

¿Se está indicando esto?

**Comment by sgelabert-dgtic** [comment]
Sí, es tracta de donar més pes a les entitats principals que a les relacionades de segon nivell. La idea és anar-ho polint en base al log de cerques.
Queda pendent veure com obtenim/analitzam el log de cerques efectuades des dels frontals:
- Via /logs/request.log de Jetty 
- Via SolrLogging (http://wiki.apache.org/solr/SolrLogging)
- Via API intermedia (solr-api-web)
- Via log de frontal WEBCAIB, SEUCAIB i GUSITE-FRONT

Entenc que les primers opcions (log centralitzar a SOLR) facilitaria la gestió.

**Comment by rsanz-indra** [comment]
Entonces aplicaremos el cambio indicado para ROLSAC actualizando el documento de análisis.
Se aplicaran 3 niveles de peso para ROLSAC según entidad:
1) Procedimientos / Fichas / Normativa / Unidad Administrativa
2) Trámites
3) Documentos (procedimiento, trámite, normativa, etc.)

Para GUSITE hay que ver si se quiere aplicar pesos según entidades.

**Comment by rsanz-indra** [comment]
Respecto al log de búsquedas, entendemos que para poder analizar correctamente la información habría que "asociar" la búsqueda a la sesión web, para poder analizar que búsquedas hace un usuario en concreto.
Para ello estaba pendiente de que se indicara dónde se quería hacer: 
 - en SOLR-API (en un archivo de texto, p.e. csv)
 - en los diferentes frontales (podría almacenarse en tablas)
Quedamos a la espera de que se decida dónde. En principio parece más operativo en SOLR-API.

**Comment by sgelabert-dgtic** [comment]
Respecte a GUSITE, l'entitat principal es "Contenido", per tant, per seguir la mateixa lògica ens pareix bé que se li assigni més que a "Agenda", "Encuesta", "FAQ", "Noticia" i "Archivo".

Pel que fa al log, tot i que estaria bé fer un anàlisi per sessió, crec que amb una primera fase ens podríem conformar amb un anàlisi global de les cerques. Caldria veure si és possible arribar a determinar l'aplicació que genera la query i centralitzar el logggin sobre el servei de SOLR

Un detall que m'acab de donar compte és que estam parlant de Documentos (procedimiento, trámite, normativa, etc.) però en l'anàlisi no consta l'entitat "documentació relacionada amb el tràmit" (RSC_DOCTRA). Veis complicat afegir-ho ? Entenc que la indexació hauria de ser semblant als "documento procedimiento"

**Comment by rsanz-indra** [comment]
Aplicamos los pesos según lo comentado en Rolsac y Gusite.

Miramos de centralizar el tema del log de búsquedas en el servidor de Solr y os comentamos.

Añadimos al documento de análisis los documentos asociados a trámite y lo implementamos.

**Comment by rsanz-indra** [comment]
Respecto a como realizar el log de las búsquedas realizadas:

- Por defecto el log de Solr muestra las búsquedas con nivel INFO (parámetro "q")

2016-06-21 12:44:55.253 INFO  (qtp15016608-20) [   x:caib] o.a.s.c.S.Request [caib]  webapp=/solr path=/select params={lowercaseOperators=true&indent=true&q=pepe&qf=searchText&_=1466513095191&stopwords=true&wt=json&defType=edismax} hits=0 status=0 QTime=42

- A nivel de Jetty hay que habilitar el log en el fichero jetty.xml descomentando el Request Log y saca la siguiente traza, mostrando usuario autenticado "rolsac" y búsqueda en parámetro "q":

0:0:0:0:0:0:0:1 - rolsac [21/jun/2016:12:47:26 +0000] "GET /solr/caib/select?q=pepe&wt=json&indent=true&defType=edismax&qf=searchText&stopwords=true&lowercaseOperators=true&_=1466513246527 HTTP/1.1" 200 -


Como se ve en el log de Jetty aparece el usuario autenticado que corresponde a la aplicación (rolsac). En el log de Solr no aparece.

Hemos realizado pruebas y si se pasan parámetros no reconocidos por Solr funciona igualmente, por lo que se podría pasar  un parámetro propio para referenciar la aplicación (p.e. "aplicacion") si se quisiera usar el log de Solr:

2016-06-21 13:35:04.114 INFO  (qtp5972292-18) [   x:caib] o.a.s.c.S.Request [caib]  webapp=/solr path=/select params={lowercaseOperators=true&aplicacion=rolsac&indent=true&q=*&qf=searchText&stopwords=true&wt=json&defType=edismax} hits=0 status=0 QTime=6


En ninguno de los 2 logs se podría extraer la sesión web, salvo que el API traspasara el identificador de sesión web siguiendo la técnica mencionada anteriormente de usar un parámetro a la petición no reconocido por Solr.


Respecto a la explotación del log podría realizarse:

 - manualmente: 
	- con alguna herramienta de visualización de logs (p.e. LogMX)
	- con editor de texto tipo Notepad++ y expresiones regulares para filtrar la información para generar un archivo con la info necesaria
	
 - automáticamente:
	- script a nivel de S.O. con sentencias de filtrado (tipo grep o awk) 
	- herramienta de gestión de logs (p.e. Logstash)

**Comment by slromero-indra** [comment]
Con los cambios efectuados, se da cerrada por el momento la tarea (se encuentra en la rama rolsac-1.3-solr).

**Comment by sgelabert-dgtic** [comment]
El log de SOLR no registre l'ID de sessió. 
Modificar l'API-SOLR perquè se li passi la sessió d'usuari a fi que quedi registrada en el log de SOLR, tal i com es comenta en aquest mateix tiquet.

**Comment by slromero-indra** [comment]
Buenas, hemos revisado el código y realizado una batería de pruebas con las distintas aplicaciones que consultan sobre SOLR. Parece que tanto en GUSITE como en SOLR se muestra la sesión id por el log de solr.

GUSITE
La prueba ha consistido en realizar una búsqueda desde el frontal de un site nuevo las palabras 'INDRA PRUEBA' obteniendo el siguiente mensaje por el log de solr y viendo el sesión id **F023E7C654A4DC8989CC7681D338F8BE**:

> 2017-02-23 10:56:56.208 INFO  (qtp22045383-12) [   x:caib] o.a.s.c.S.Request [caib]  webapp=/solr path=/select params={fl=id,categoria,idPadre,padreCategoria,aplicacionId,titulo_ca,descripcion_ca,padreDescripcion_ca,url_ca,padreUrl_ca,extension_ca,fotoUrl,pathUo,familiaId,materiaId,publicoId,telematico,interno,fechaActualizacion,fechaPublicacion,fechaCaducidad,fechaPlazoIni,fechaPlazoFin,idRaiz,categoriaRaiz,score&**sesionId=F023E7C654A4DC8989CC7681D338F8BE**&start=0&q=INDRA+PRUEBA&qf=searchText_ca^2.0+searchTextOptional_ca^0.2&wt=javabin&fq=aplicacionId:(GUSITE)&fq=categoriaRaiz:MIC&fq=idRaiz:MIC41&fq=(-fechaPublicacion:[*+TO+*]+AND+*:*)+OR+fechaPublicacion:[*+TO+NOW]&fq=(-fechaCaducidad:[*+TO+*]+AND+*:*)+OR+fechaCaducidad:[NOW+TO+*]&version=2&defType=edismax&rows=10} hits=0 status=0 QTime=208

SEUCAIB 1.1
La prueba ha consistido en realizar una búsqueda desde el buscador de trámites de seucaib con las palabras 'INDRASEUCAIB PRUEBA' obteniendo el siguiente log con el id sesión **BC1E6E18A5E85516F44027B01F5647E3**:

> 2017-02-23 12:13:19.937 INFO  (qtp22045383-18) [   x:caib] o.a.s.c.S.Request [caib]  webapp=/solr path=/select params={group.format=simple&group.ngroups=true&qf=searchText_ca^2.0+searchTextOptional_ca^0.2&wt=javabin&version=2&rows=10&defType=edismax&fl=id,categoria,idPadre,padreCategoria,aplicacionId,titulo_ca,descripcion_ca,padreDescripcion_ca,url_ca,padreUrl_ca,extension_ca,fotoUrl,pathUo,familiaId,materiaId,publicoId,telematico,interno,fechaActualizacion,fechaPublicacion,fechaCaducidad,fechaPlazoIni,fechaPlazoFin,idRaiz,categoriaRaiz,score&start=0&sesionId=**BC1E6E18A5E85516F44027B01F5647E3**&q=INDRASEUCAIB+PRUEBA&group.field=idRaiz&group=true&fq=categoria:(PRO+OR+DPR+OR+TRA+OR+DTR)&fq=publicoId:(200)&fq=pathUo:+(1#*+OR+1)&fq=(-fechaPublicacion:[*+TO+*]+AND+*:*)+OR+fechaPublicacion:[*+TO+NOW]&fq=(-fechaCaducidad:[*+TO+*]+AND+*:*)+OR+fechaCaducidad:[NOW+TO+*]} hits=0 status=0 QTime=36

SEUCAIB 1.2.
La prueba ha consistido en realizar una búsqueda desde el buscador de trámites de seucaib con las palabras 'INDRASEUCAIB PRUEBA' obteniendo el siguiente log con el id sesión **4E0C71136F4A70DE7CB5B956F60AC2D6**:

> 2017-02-23 12:17:51.588 INFO  (qtp22045383-17) [   x:caib] o.a.s.c.S.Request [caib]  webapp=/solr path=/select params={group.format=simple&group.ngroups=true&qf=searchText_ca^2.0+searchTextOptional_ca^0.2&wt=javabin&version=2&rows=10&defType=edismax&fl=id,categoria,idPadre,padreCategoria,aplicacionId,titulo_ca,descripcion_ca,padreDescripcion_ca,url_ca,padreUrl_ca,extension_ca,fotoUrl,pathUo,familiaId,materiaId,publicoId,telematico,interno,fechaActualizacion,fechaPublicacion,fechaCaducidad,fechaPlazoIni,fechaPlazoFin,idRaiz,categoriaRaiz,score&start=0&sesionId=**4E0C71136F4A70DE7CB5B956F60AC2D6**&q=indra2+secuaib1.1&group.field=idRaiz&group=true&fq=categoria:(PRO+OR+DPR+OR+TRA+OR+DTR)&fq=publicoId:(200)&fq=pathUo:+(1#*+OR+1)&fq=(-fechaPublicacion:[*+TO+*]+AND+*:*)+OR+fechaPublicacion:[*+TO+NOW]&fq=(-fechaCaducidad:[*+TO+*]+AND+*:*)+OR+fechaCaducidad:[NOW+TO+*]} hits=0 status=0 QTime=157

**Comment by sgelabert-dgtic** [comment]
Tens raó Sergio, el que he notat a faltar és que no sempre apareix el paràmtre **aplicacionId** en el log.

- En el següent exemple, NO apareix el valor:
2017-02-24 10:23:29.726 INFO  (qtp1992148286-1076) [   x:webcaib] o.a.s.c.S.Request [webcaib]  webapp=/solr path=/select params={group.format=simple&group.ngroups=true&qf=searchText_es^2.0+searchTextOptional_es^0.2&wt=javabin&version=2&rows=10&defType=edismax&fl=id,categoria,idPadre,padreCategoria,**aplicacionId**,titulo_es,descripcion_es,padreDescripcion_es,url_es,padreUrl_es,extension_es,fotoUrl,pathUo,familiaId,materiaId,publicoId,telematico,interno,fechaActualizacion,fechaPublicacion,fechaCaducidad,fechaPlazoIni,fechaPlazoFin,idRaiz,categoriaRaiz,score&start=0&sesionId=E3A4C9E296B213BE03CEC0925DE57638&q=*&group.field=idRaiz&group=true&fq=categoria:(PRO+OR+DPR+OR+TRA+OR+DTR)&fq=pathUo:+(1#138143#1224#*+OR+1#138143#1224)&fq=(-fechaPublicacion:[*+TO+*]+AND+*:*)+OR+fechaPublicacion:[*+TO+NOW]&fq=(-fechaCaducidad:[*+TO+*]+AND+*:*)+OR+fechaCaducidad:[NOW+TO+*]} hits=4 status=0 QTime=10

- En el següent exemple, SÍ apareix el valor:
2017-02-24 11:15:13.326 INFO  (qtp1992148286-1094) [   x:webcaib] o.a.s.c.S.Request [webcaib]  webapp=/solr path=/select params={fl=id,categoria,idPadre,padreCategoria,**aplicacionId**,titulo_ca,descripcion_ca,padreDescripcion_ca,url_ca,padreUrl_ca,extension_ca,fotoUrl,pathUo,familiaId,materiaId,publicoId,telematico,interno,fechaActualizacion,fechaPublicacion,fechaCaducidad,fechaPlazoIni,fechaPlazoFin,idRaiz,categoriaRaiz,score&sesionId=69EC75F4CCD9ADE7A3F0A2126D6F3E3D&start=0&q=Soib&qf=searchText_ca^2.0+searchTextOptional_ca^0.2&wt=javabin&fq=**aplicacionId:(GUSITE)**&fq=categoriaRaiz:MIC&fq=idRaiz:MIC14&fq=(-fechaPublicacion:[*+TO+*]+AND+*:*)+OR+fechaPublicacion:[*+TO+NOW]&fq=(-fechaCaducidad:[*+TO+*]+AND+*:*)+OR+fechaCaducidad:[NOW+TO+*]&version=2&defType=edismax&rows=10} hits=0 status=0 QTime=6

Pot ser que no totes les aplicacions ho passin?

**Comment by slromero-indra** [comment]
Buenas, en el ejemplo que no sale la aplicación, se produce la búsqueda en SEUCAIB. En este caso, no se pasa el aplicacionID porque es un filtro de búsqueda y no es necesario porque ya se pasa el filtro categoría (Procedimiento, Doc. Procedimiento, Trámite y Doc Tramite) que restringue a que tipos de datos se le aplica la búsqueda.

¿Si queréis incluímos el filtro de aplicación Id en seucaib (sería aplicacionId.ROLSAC)? los datos serían los mismos. Si lo que se desea es saber qué aplicación es la que realiza la consulta, no existe ningún parámetro que lo indique, deseáis que se añada también un parámetro que lo indique?

Saludos!

**Comment by sgelabert-dgtic** [comment]
Sí, el que volem es precisament això, poder sabre des de quin frontal (SEUCAIB, GUSITE o WEBCAIB) es realitza la cerca. Si és possible també traçaria les operacions d'indexació (ROLSAC o GUSITE)
En resum el que volem és es registri el paràmetre 'fictici" que comentava Rafa en aquest mateix tiquet.

**Comment by rsanz-indra** [comment]
Un detalle, lo que se analizó (e implementó) fue añadir un parámetro ficticio para añadir la sesión web en las búsquedas (sesionId).
No hay problema de añadir un nuevo parámetro adicional para identificar a la aplicación invocante (p.e. aplicacionCallerId).  Este parámetro sería una cadena (no tipada, solo tenemos tipados las aplicaciones que indexan).
Para las búsquedas sería replicar lo que se hace para el sesionId pero para la indexación no tenemos claro si se podría ya que las peticiones se hacen de otra forma ¿queréis que investiguemos si se puede?

**Comment by sgelabert-dgtic** [comment]
És això el que volem, passar paràmetre fictici amb una cadena no tipada de les aplicacions que empren SOLR, principalment per traçar les cerques i si es possible també per les operacions d'indexació. A priori no hi veig diferència entre passar el sessionId, corregim si s'equivoc.
De fet, pensava que amb el teu comentari de dia 21/06/2017 sobre aquest mateix tiquet seria el que farieu:
"Hemos realizado pruebas y si se pasan parámetros no reconocidos por Solr funciona igualmente, por lo que se podría pasar un parámetro propio para referenciar la aplicación (p.e. "aplicacion") si se quisiera usar el log de Solr"

**Comment by rsanz-indra** [comment]
No sé si nos hemos explicado bien: para las búsquedas no hay problema en replicar el funcionamiento (es añadir un parámetro nuevo).
El tema viene con la indexación, tal como funciona el cliente de solr (el ofrecido por solr) habría que investigar como se puede pasar este dato ya que lo que se envía es un documento con los datos y no aparece en la request que sale en el log. Os pedimos confirmación para que si veis que es necesario tener este dato en el log a la hora de indexar, investigar como se puede hacer.

**Comment by sgelabert-dgtic** [comment]
Entenc que per indexació, la informació que surt actualment amb el paràmetre **aplicacionId** en seria suficient:

2017-02-24 09:00:00.113 INFO  (qtp1992148286-1094) [   x:webcaib] o.a.s.u.p.LogUpdateProcessorFactory [webcaib]  webapp=/solr path=/**update** params={wt=javabin&version=2}{deleteByQuery=id:FCH2839038 AND categoria:FCH AND **aplicacionId:ROLSAC** (-1560204332346900480)} 0 7

2017-02-24 01:02:09.750 INFO  (qtp1992148286-1100) [   x:webcaib] o.a.s.u.p.LogUpdateProcessorFactory [webcaib]  webapp=/solr path=**/update**/extract params={literal.url_es=/M34/f/223103&literal.pathUo=1#138143&literal.descripcion_es=2017-03-25+Anellament+salines+(pdf)&literal.id=ARC223103_es&wt=javabin&**literal.aplicacionId=GUSITE**&version=2&literal.titulo_es=2017-03-25+Anellament+salines&literal.padreUrl_es=/M34/es/agenda_de_actividades&literal.interno=true&fmap.content=searchText_es&literal.fechaPublicacion=2015-11-26T00:00:00Z&literal.categoriaRaiz=MIC&literal.idPadre=CON83543&boost=0.2&literal.categoria=ARC&literal.padreCategoria=CON&literal.idRaiz=MIC34&literal.extension_es=pdf}{add=[ARC223103_es (1560174269299687424)]} 0 17

**Comment by rsanz-indra** [comment]
El tema es que no siempre sale este parámetro a la hora de indexar. Los ejemplos que nos pasas son respecto a operaciones para indexar un fichero y borrar elementos. No sale cuando se indexa un elemento como tal, en ese caso se pasa un objeto con toda la información del elemento, pero esa info no sale en el log:
     HttpSolrClient.add(SolrInputDocument);
Hay que ver en este caso como se puede pasar el parámetro de aplicación invocante, ya que se está usando el api proporcionado por Solr.

**Comment by sgelabert-dgtic** [comment]
OK, donau-li una ullada. Si la cosa es complica no hi dediqueu molt de temps. El que ens interessa es traçar les cerques per sessió d'usuari i aplicació. Les operacions d'indexació ens no són necessaries de moment, però bé, donarien informació addicional a nivell de log.

**Comment by slromero-indra** [comment]
Buenas, tras realizar diversas pruebas no hemos sido capaces de introducirlo en la indexación de datos.

Respecto a las búsquedas, ahora voy a comitear diversos cambios (deberían estar todos los cambios a partir de mañana) que implican cambiar el constructor de la entidad SolrSearcher para que acepte un campo más 'aplicaciónCallerId' que indicará quien está realizando la consulta.

En los proyectos ant (ROLSAC Y GUSITE), el jar está incluido en el proyecto pero en los proyectos que utilizan MAVEN (WEBCAIB y SEUCAIB) hay que compilar el proyecto solrapi para que se acepten los cambios y luego realizar un build de los proyectos.
