### ISSUE TITLE
Creación Modelo BBDD para Rolsac 1.3

### ISSUE THREAD

**Issue by dmadronal-indra** [GovernIB/rolsac#342]
Creación Modelo BBDD para Rolsac 1.3

**Comment by slromero-indra** [comment]
Se ha mandado un email con la documentación generada:

-	rolsac_comments.sql : SQL para generar los comentarios de tablas y campos. Las tablas y campos no estaban comentados a nivel de BBDD.
-	Diagramas de tablas: 
o	ROLSAC_Diagrama_Principal: Este es el diagrama que estamos usando para que el equipo de desarrollo tenga la visión global del modelo.
o	ROLSAC_Diagrama_Archivos: Diagrama con la relación del uso de archivos
o	ROLSAC_Diagrama_Administracion_Remota: Diagrama con la funcionalidad de administración remota que ya nos comentastéis que no se usaba.
-	ROLSAC-1.3-Modelo BBDD: documento con los diferentes diagramas y el listado de tablas. No hemos introducido el detalle con los campos de cada tabla pero podríamos generarlo con la herramienta.

**Comment by sgelabert-dgtic** [comment]
Tot el tema l'administració Remota afecta a la Integració de ROLSAC amb ROLSACPMA el qual, a dia d'avui i si no hi ha canvis al respecte, ha quedat en via morta.

Interessa ampliar la documentació de les entitats principals ROLSAC i les seves relacions amb entitats secundàries (public objectiu, matèries, fets vitals, documents, ...) :
- Unitats Administratives
- Fitxes Informatives
- Procediments/Tràmits Administratius 
- Normativa
- Usuaris

**Comment by sgelabert-dgtic** [comment]
S'ha de tenir en compte els criteris establerts a las tasca https://github.com/GovernIB/gusite/issues/26 de GUSITE per generar documentació coherent

**Comment by rsanz-indra** [comment]
La documentación a generar tendrá la siguiente estructura:

diagrama global
listado de tablas con su descripción
diagrama particular de los principales subsistemas

**Comment by rsanz-indra** [comment]
Se me pasó comentar que deberían estar los cambios  en el doc de rolsac en 8-12h.

**Comment by slromero-indra** [comment]
Se suben los documentos relacionados
