### ISSUE TITLE
Afegir camp "Correu electrònic" a l'apartat responsable UA

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#343]
Es sol·licita afegir un camp nou anomenat "Correu electrònic" en l'apartat "Responsable" de la pantalla d'Unitats Administratives.
La tasca ha de contemplar: 
- Controlar la validesa del format del camp (igual que es fa amb el camp ja existent "Correu electrònic" de la UA)
- Modificar l'API de consulta de ROLSAC perquè es pugui recuperar aquesta informació de la UA
- Actualitzar la documentació 1.3 (manual d'usuari, model de dades)

**Comment by episano-dgtic** [comment]
Correcto en caibter y el manual a sido modificado correctamente. 
La parte del api no la he podido testear. 
Tb. han modificado los scripts de BD.

**Comment by sgelabert-dgtic** [comment]
Cal especificar el tipus CHAR en els scripts de BBDD (rolsac_create_schema.sql / rolsac_update_schema_from_1.2.sql)

ALTER TABLE RSC_UNIADM ADD UNA_EMAILR varchar2(**CHAR** 256);
