### ISSUE TITLE
Afegir camp "Correu electrònic" a l'apartat responsable UA - ROLSAC 1.2

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#344]
Es sol·licita incorporar la funcionalitat de correu electrònic per al responsable d'una UA desenvolupada en ROLSAC 1.3 (#343) sobre la branca ROLSAC 1.2.
S'ha de tenir en compte:
- Modificar scripts de BBDD branca 1.2 i 1.3 (rolsac_update_schema_from_1.2.sql) suposant que és un canvi des de la versió 1.2
- Consolidar els canvis en l'API versions 1.2 i 1.3
- Actualitzar sac-api-client.jar en els projectes relacionats (GUSITE, WEBCAIB i SEUCAIB)
Gràcies.

**Comment by dmadronal-indra** [comment]
Se han actualizado las aplicaciones GUSITE, WEBCAIB i SEUCAIB, con la nueva libreria.
