### ISSUE TITLE
Implementació de la indexació de continguts ROLSAC amb SOLR

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#346]
Es sol·licita incorporar al backoffice de ROLSAC les funcions necessàries per realitzar la indexació de continguts (online/manual) amb SOLR.
Es sol·licita també eliminar del repositori de codi les classes i llibreries utilitzades per la indexació amb Lucene.

**Comment by sgelabert-dgtic** [comment]
- Afegir botó per forçar la finalització de les tasques d'indexació pendents.
- Canviar el nivell de log a debug els comentaris classificats com errors:
```
2016-09-21 11:45:20,334 ERROR [es.caib.rolsac.back2.util.IndexacionJob] Ejecutando el indexacion job con tipoIndexacion:todo
2016-09-21 11:45:20,336 ERROR [org.ibit.rol.sac.persistence.ejb.HibernateEJB] INDEXAR TODO FICHA.
```
- Revisar funcionament de la pestanya "Indexar pendent" ja que es queda en estat "Carregant llistat d'indices. Esperi un moment, si us plau". I corregir error ortogràfic "Carregant llistat **d'índexos**. Esperi un moment, si us plau"

**Comment by slromero-indra** [comment]
Se han actualizado los scripts, eliminando referencias a solr en los scripts de la 1.3 e incluidos los nuevos scripts en la 1.4.

**Comment by slromero-indra** [comment]
Buenas, ya está actualizado correctamente en la rama 1.3. Saludos!

**Comment by sgelabert-dgtic** [comment]
Tenim problemes d'indexació de fitxes i procediments de ROLSAC en producció.
Remet per correu, logs servidor d'aplicacions i descarrega de la taula RSC_SOLRPD
