### ISSUE TITLE
Canviar la forma de validació dels schemas XML en l'API de ROLSAC

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#348]
Es sol·licita canviar la forma en què es valida el fitxer sac-api-client-1.2.jar/es/caib/rolsac/api/v2/resources/sac-api-context.xml. Actualment fa referència a una URL externa per validar l'esquema, concretament www.springframework.org/schema/beans/spring-beans-3.0.xsd. Si el servei està caigut (com ha passat recentement) totes les aplicacions que fan ús de l'API generen error i cauen.

Per tal d'evitar dependre de webs externes, hem trobat aquest article que pot ser útil per configurar l'aplicació per tal que validi internament els esquemes:
http://stackoverflow.com/questions/1729307/spring-schemalocation-fails-when-there-is-no-internet-connection

Per altra banda, es sol·licita informar sobre la resta de fitxers XML que duen URLs externes

**Comment by sgelabert-dgtic** [comment]
Ok, aplicar aquest canvi sobre la branca 1.2.
Actualitzar la llibreria sac-api-util.jar en els projectes relacionats.

**Comment by dmadronal-indra** [comment]
```
Revision: 323
Author: u83491
Date: lunes, 30 de mayo de 2016 15:43:45
Message:
GovernIB/rolsac#348 Actualizar validación schemas XML en API ROLSAC
- Actualizar librería sac-api-client.jar en seu caib
----
Modified : /branches/seucaib-1.1/war/aux-lib/sac-api-client.jar
Modified : /branches/seucaib-1.1.1/war/aux-lib/sac-api-client.jar
```

```
Revision: 66
Author: u83491
Date: lunes, 30 de mayo de 2016 16:05:40
Message:
GovernIB/rolsac#348 Actualizar validación schemas XML en API ROLSAC
- Actualizar librería sac-api-client.jar en seu caib


----
Modified : /trunk/etc/libs/maven-install-libs.txt
Modified : /trunk/etc/libs/sac-api-client.jar

```

**Comment by dmadronal-indra** [comment]
Revisando el código hemos visto otra reverencia externa en \moduls\back2\etc\rolsacmvc-servlet.xml:
```
xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.0.xsd       
http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-3.0.xsd">

```

El resto de referencias están ubicadas en los test del proyecto (carpeta test):

- Persistence/integracion/resources/dao_persistence.xml
- Persistence/integracion/resources/dao.xml
- Persistence/integracion/resources/dataSource_persistence.xml
- Persistence/integracion/resources/dataSurce.xml
- Persistence/unitario/resources/dao.xml
- Persistence/unitario/resources/dataSource.xml
- Persistence/vuds/integracion/resources/WEB-INF/action-servlet.xml y vuds/integracion/resources/WEB-INF/action-servlet.xml
- Persistence/vuds/integracion/resources/WEB-INF/applicationContext.xml y vuds/integracion/resources/WEB-INF/applicationContext.xml
- Persistence/vuds/integracion/resources/dao.xml y vuds/integracion/resources/ dao.xml
- Persistence/vuds/integracion/resources/dataSource.xml y vuds/integracion/resources/dataSource.xml

**Comment by sgelabert-dgtic** [comment]
Es detecta errada al intentar cercar l'schema spring-beans-3.0.xsd en projectes que no disposen de org.springframework.beans-3.0.5.RELEASE.jar

`org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 30; schema_reference.4: Failed to read schema document 'classpath:org/springframework/beans/factory/xml/spring-beans-3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>. `

L'objectiu és tenir un únic sac-api-client.jar vàlid per a tots els projectes.

**Comment by sgelabert-dgtic** [comment]
El fitxer /ROLSAC-1.3-GIT/moduls/back2/etc/rolsacmvc-servlet.xml segueix fent referència a URLs externes enlloc de cercar l'schema en el classpath

**Comment by sgelabert-dgtic** [comment]
Ho podeu revisar per favor i així tanquem ja aquest tiquet
Gràcies.

**Comment by sgelabert-dgtic** [comment]
No he rebut resposta sobre aquest assumpte

**Comment by slromero-indra** [comment]
Nos ponemos a ello, esperamos tenerlo en la mayor brevedad posible para subirlo con la versión 1.5.4
