### ISSUE TITLE
Canvis formulari de procedimients

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#349]
Es sol·licita implementar els següents canvis sobre la pantalla de Prodeciments:

1.-Canvis nomenclatura de camps:

- Menú &quot;Catàleg de procediments&quot; per &quot;Inventari de procediments&quot;

- Camp &quot;Forma d&#39;iniciació&quot; per &quot;Forma d&#39;inici&quot;

- Botó &quot;Borrar&quot; per &quot;Esborra&quot;

- Mòdul lateral &quot;Públics objectiu relacionats&quot; per &quot;Públic objectiu&quot;

- Mòdul lateral &quot;Tipus de procediment&quot; afegir * d&#39;obligatorietat al títol i eliminar etiqueta del selector

- Mòdul lateral &quot;Normativa relacionada&quot; afegir * d&#39;obligatorietat al títol i canviar nom &quot;Normativa del procediment&quot;

- Mòdul lateral &quot;Documents relacionats&quot; per &quot;Documents relacionats amb el procediment&quot;

1.2.- Ocultar camps del formulari

- Resultat

- Finestreta única

- Mòdul Fets Vitals

1.3.- Canviar apartat informadors per &quot;Dades de contacte&quot; i hauran d&#39;aparèixer els següents camps:

- Servei o Secció responsable (mostra pop-up arbre selector UAs) - Obligatori
- Nom del responsable (no visible a la Seu Electrònica) - Obligatori
- Adreça electrònica  - Opcional - Correspon al camp "Notes per a informadors" al qual se li haurà d'aplicar la màscara de correu electrònic per validar el contingut del camp.

1.4.- Canviar ordre col·locació camps i mòduls laterals del formulari. (S'adjunta document explicatiu)

**Comment by sgelabert-dgtic** [comment]
[2016 05 23 Formulari procediments.pdf](https://github.com/GovernIB/rolsac/files/286675/2016.05.23.Formulari.procediments.pdf)

**Comment by sgelabert-dgtic** [comment]
- Els valors introduïts dins el camp "Tipus de procediment" fan que el selector quedi fora del box contenidor. Canviar marca d'obligatorietat perquè aparegui a nivell de títol del mòdul. Adjunt captura de pantalla.
- El mòdul lateral Matèries relacionades ha de tenir marca d'obligatorietat a nivell de títol
- Ocultar el mòdul lateral de Fets vitals relacionats.
- Moure mòdul lateral de tràmits al final del mòduls laterals, tal i com s'indica en el pdf de mostra
- Moure camp observacions dins l'apartart Dades, just davall el camp "Organ o servei instructrutor"
- Canviar els següents literals de l'aplicació :  
castellà -  botó "previsualitza" per "previsualizar"
castellà -  Mòdul lateral "Materies relaciondas" per "Materias relacionadas"
castellà - Mòdul Auditorites, columna "data" per "Fecha" i columna "Operació" per "Operación"
castellà - Mòdul lateral "Documentos relacionados con el procedimento", botó "AÑADIR 
DOCUMENTO" per "Añadir documento" 
català - botó "Borrar" per "Esborrar" del camp "Òrgan competent per resoldre"

**Comment by sgelabert-dgtic** [comment]
Bug detectats: 
- No s'emmagatzemen els canvis fets en el camp "Organisme competent per resoldre"
- A l'hora de publicar un procediment (canviar "estat=public") sempre apareix "Error es obligatori crear un model de sol·licitud per el tràmit d'inici". Si es carrega la pantalla de tràmit i es retorna a la pantalla de procediments, l'error desapareix.
- El traductor automàtic no funciona en la pantalla de procediment.

**Comment by slromero-indra** [comment]
Desde el entorno caibter no tenemos acceso al servicio web encargado de la traducción (por si probais la traducción, ahora si que da el mensaje, no sé si es posible pero si tenéis una url para la traducción podríamos cambiar caibter para que acceda al servicio web).

Igualmente, el error que había en la traducción de procediments ya esta resuelto, se debía a un problema antes de enviar los datos a la url de traducciones que sólo afectaba a procediments después de los cambios realizados en la interfaz.

**Comment by sgelabert-dgtic** [comment]
-Seguim tenint problemes de traducció en la pantalla de procedimetns:
Les propietats a configurar en el jboss-service.xml  de ROLSAC per activar la traductor automàtic són:
es.caib.rolsac.integracion.traductor=S
es.caib.rolsac.integracion.traductor.servidor=scatwnt1.caib.es:8080
Teòricament hauríeu de tenir accés al servidor scatwnt1.caib.es:8080 via VPN de INDRA. 

- Quan es crea un procediment nou apareixen els mòduls laterals de "Matèries relacionades" i "Normativa relacionada", els quals donen error si no s'ha creat el procediment abans.

**Comment by slromero-indra** [comment]
Hemos sido capaces de conectarnos a la traducción en local, pero de momento en caibter no está activo la conexión a scatwnt1.caib.es, por favor, validad en el entorno caib.

**Comment by sgelabert-dgtic** [comment]
Ok amb el traductor sobre l'entorn caib.
Segueix passant el problema amb donar d'alta matèries i normativa sense tenir creat el procediment. La solució passaria per ocultar aquests mòduls a la creació.

**Comment by slromero-indra** [comment]
Hemos visto el caso en el que aparecen los módulos materias y normativas, si entramos en el detalle de uno, pulsamos volver y posteriormente procedemos a crear uno nuevo. Si inicialmente pulsamos en crear sin haber entrado en el detalle de un procedimiento no aparecían los módulos ¿es el mismo caso que habíais detectado?

**Comment by sgelabert-dgtic** [comment]
Correcto.

**Comment by slromero-indra** [comment]
Subido a caibter.

**Comment by sgelabert-dgtic** [comment]
Ok en caibter. 
Cuando puedas commitea código sobre el repositorio.

**Comment by slromero-indra** [comment]
Ya está subido. Un saludo

**Comment by sgelabert-dgtic** [comment]
Ok, pero falta fix en este tiquet ;-)

**Comment by slromero-indra** [comment]
Sorry, ha habido un poco de jaleo con todos los comentarios, entre el comentario tuyo de hace 4 horas y el mío de hace 30 minutos está el fix. He subido el fix antes que el comentario, sorry, ya está comiteado todo comiteado. Saludos.
