### ISSUE TITLE
Canvis formulari de tràmits

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#350]
Sol·licitam que s&#39;implementin els següents canvis sobre el formulari de tràmits:

1.- Canviar valor &quot;Iniciació&quot; per &quot;Inici&quot; del selector &quot;moment&quot;

2- Ocultar camps del formulari

- Validació

- Data caducitat

- Lloc

- Mòdul lateral &quot;Documentació requerida&quot;

3.- Afegir control obligatorietat sobre els camps:

- Requisits

- Termini màxim

4.-Canvis nomenclatura de camps

- Selector &quot;Moment&quot; per &quot;Fase del procediment&quot;

- Camp &quot;Termini màxim per a la presentació&quot; per &quot;Termini màxim&quot;

- Camp &quot;Òrgan competent per tramitar&quot; per &quot;Òrgan competent per a la tramitació&quot;

- Camp &quot;Documentació&quot; per &quot;Documentació a presentar&quot;

- Mòdul lateral &quot;Models de sol•licitud&quot; per &quot;Models&quot;

- Mòdul lateral &quot;Documentació informativa&quot; per &quot; Documents relacionats amb el tràmit&quot;

5.- Afegir camp observacions. Reconvertir el camp &quot;Descripció&quot; a &quot;Observacions&quot; de manera que conservi el seu contingut.

6.- Canviar ordre col•locació camps i mòduls laterals del formulari. (Veure document adjunt)

7.- Canviar selectors dels camps data perquè permetin especificar l'hora i el minut. Veure edemés si és possible fer que el camp "Data de tancament" tingui per valor per defecte el dia actual i hora 
 23:59

**Comment by sgelabert-dgtic** [comment]
[2016 05 23 Formulari tramits.pdf](https://github.com/GovernIB/rolsac/files/286733/2016.05.23.Formulari.tramits.pdf)

**Comment by sgelabert-dgtic** [comment]
- El mòdul lateral Models ha de tenir marca d'obligatorietat a nivell de títol. Endemés l'obligatorietat del camp ha de ser independent de si el procediment al qual està associat és públic o no.
Actualment surt aquest missatge " "No es pot guardar el tràmit d&#39inici degut a que el procediment al qual està associat està en estat publicat i no té models de sol-licitud." 

- El camp "Data de tancament" ha de tenir hora per defecte 23:59

- Canviar els següents literals de la pantalla :
català  - Modul lateral "Publicaci?" per "Publicació" 
castellà - Modul lateral "Publicaci?" per "Publicación" 
català - "No es pot guardar el tràmit d&#39inici degut a que el procediment al qual està associat està en estat publicat i no té models de sol-licitud." per "Error, és necessari associar algun model al tràmit"

**Comment by sgelabert-dgtic** [comment]
Falta canviar:
- El camp "Data de tancament" ha de tenir hora per defecte 23:59

- Canviar els següents literals de la pantalla :
català - Modul lateral "Publicaci?" per "Publicació" 
castellà - Modul lateral "Publicaci?" per "Publicación"

**Comment by sgelabert-dgtic** [comment]
Ocultar la secció "VENTANILLA ÚNICA" de la pantalla de tràmit, amb independència del checkbox "ocult" de la pantalla de procediments.

**Comment by slromero-indra** [comment]
Buenas, se observó que si se creaba un procedimiento y posteriormente se gestionaba los trámites, aparecía el módulo de ventana única. Con el cambio, ya ha desaparecido la opción de ventana única.
