### ISSUE TITLE
Desaparició mòdul auditories UA, Fitxes i Normativa

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#352]
Ha desaparegut el mòdul d'autories de les pantalles d'Unitats Administratives, Fitxes Informatives i Normativa. 
La informació no apareix en aquestes pantalles amb independència del rol d'accés RSC_SYSTEM, RSC_SUPER
Aquesta informació apareixia quan validàrem la tasca #3

**Comment by episano-dgtic** [comment]
okey
