### ISSUE TITLE
Bug canvi d'ordre fitxes-seccions pantalla unitats administratives

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#354]
En el mòdul lateral "Seccions" de la pantalla d'unitats administratives, es pot entrar a gestionar l'ordre d'aparició de les fitxes en una determinada secció. En aquesta subpantalla de gestió s'han detectat els següents erros:
- Sempre apareix el literal "Agència de notícies" quan hauria d'aparèixer el nom de la secció gestionada.
- Quan via selector es vol canviar l'ordre de les fitxes de la secció i aquesta secció té més de 10 fitxes (hi ha paginació) al gravar es perden totes les fitxes que queden fora de la primera pàgina.
- Quan s'elimina una fitxa de la secció s'ha de comprovar que la fitxa no queda orfe, és a dir, no ha de permetre eliminar la fitxa de la secció si aquesta secció és la única amb la que està relacionada la fitxa.

**Comment by slromero-indra** [comment]
Buenas, el guardar ya funciona correctamente. Aún así, se ha observado que el guardado se realiza mediante una petición asíncrona AJAX, saliéndose de la página mientras se está guardando la información. Esto puede provocar que se pueda volver a incorporar en la misma página sin haber finalizado el guardado de cambios en la base de datos y sin verse todavía los cambios de orden en la interfaz (este comportamiento sólo se observa cuando se dispone de centenares de secciones).

**Comment by sgelabert-dgtic** [comment]
Em funciona a caibter però quan descarreg el codi en local, no... 
Podeu revisar que s'hagin pujat tots els canvis sobre el repositori ?

**Comment by slromero-indra** [comment]
Buenas, hemos probado volviendo a bajar en un workspace por separado de eclipse y hemos podido compilar sin ningún problema y desplegarlo en un jboss probando los cambios y funciona. Por favor, podéis confirmarme si os funciona o en caso de error, si tenéis un error de compilación, ejecución o la prueba que habéis realizado. Saludos!

**Comment by sgelabert-dgtic** [comment]
Tens raó Sergio, era qüestió de temporals ...
Ara sí que puc veure els canvis, provam i et deim coses

**Comment by episano-dgtic** [comment]
Respecto al primer pto: Ahora no aparece ni el nombre de la sección ni el literal "Agència de notícies"  SINO "undefined". 

Tampoco está arreglado "Quan s'elimina una fitxa de la secció s'ha de comprovar que la fitxa no queda orfe, és a dir, no ha de permetre eliminar la fitxa de la secció si aquesta secció és la única amb la que està relacionada la fitxa."
He podido quitar la única relación que tenía una ficha con una sección, haciendo que luego no pueda acceder a la ficha de ninguna manera.

**Comment by sgelabert-dgtic** [comment]
Amb els canvis que heu fet el que controlau és que una secció no quedi buida (i això sí que pot passar), el que sol·licitam és que tota fitxa estigui com a mínim a una secció-unitat administrativa

**Comment by slromero-indra** [comment]
Ok, ahora revisamos la incidencia y cambiamos el comportamiento con las secciones. 

Respecto al literal 'undefined', no hemos sido capaces de replicar el error en caibter, podéis comentar con que unidades administrativan os ocurre?

**Comment by slromero-indra** [comment]
También somos capaces de acceder a proves pero no tenemos permisos para visualizar los procedimientos y unidades administrativas, nos podéis dar permisos para así cuando tengáis algún problema poder replicarlo. Saludos!

**Comment by sgelabert-dgtic** [comment]
Hecho,
Alta usuarios de los siguientes usuarios, con autorizaciona a UA Govern:
Sanz Villanueva, Rafael;
Corullón Lago, Guillermo;
Lopez Romero, Sergio;

Avisadme por correo personal si se necesitan más usuarios o necesitais cambio de rol de acceso.

**Comment by slromero-indra** [comment]
Exceptuando el punto de "undefined" ya está subido el resto.

**Comment by slromero-indra** [comment]
Buenas, ya está subido los cambios comentado por teléfono. Se ha dejado la interfaz de gestión de las secciones como estaba. Respecto al borrar fichas huérfanas, se ha solucionado implementando un método que se llama cuando se pulsa el aspa, avisando al usuario si puede borrarlo (en caso de ser una ficha huérfana, con una única relación, se impide el borrado y muestra un mensaje informativo de la razón que no se puede borrar).

Pruebas realizadas para borrar huérfanas:
  - Se crean dos fichas, una de ellas asociada a la misma unidad administrativa y sección (en nuestro caso de prueba, INVENTADO SOLR) y una de ellas asociada también a otra unidad administrativa y otra sección (GIB).
  - Posteriormente, se entra en la unidad administrativa INVENTADO SOLR y se intenta borrar ambas fichas y sólo permite borrar una de ellas.
