### ISSUE TITLE
Resultats cercador de procediments pantalla Procediments Administratius

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#355]
El cercador de la pantalla de procediments no quadren els resultats de la cerca quan es filtra per "cercar en UA filles" + visibilitat.
Exemple:
- Consulta base: UA "Govern Illes Balears" en la molla de pa i marcant en el cercador de procediments "cercar en UA filles" --> 1692 procediments.
- Consulta base + filtre "visible" --> 1504 procediment (s'observa que la cerca proporciona erroneament procediments no visible)
- Consulta base + filtre "no visible" --> 839 procediments.

La visibilitat d'un procediment ve determinada per: data de publicació + data caducitat + estat

**Comment by sgelabert-dgtic** [comment]
Ok
Només una cosa, preferiria que empràsiu Validacion.INTERNA i Validacion.RESERVA en lloc de fer referència explicita al codi en ProcedimientoFacadeEJB.java. Al final el codi és més mantenible.

**Comment by slromero-indra** [comment]
Fet.

**Comment by episano-dgtic** [comment]
Siguen sin cuadrar los números. Para el govern balears y hijos en el cuadro de control 1071 procedimientos no visibles y con el buscador 1065

**Comment by slromero-indra** [comment]
Buenas, hemos visto que en el mando de control pone 1985 (captura adjunta) mientras que en buscar de procedimiento pone 1979 (captura adjunta 2). Este se debe a que cada uno de las páginas llaman a un método totalmente distinto por lo que necesitamos que nos digáis cual os parece la correcta, más exactamente, al comprobar los procedimientos no visibles.
El problema, tras investigarlo, se debe a que el código de familia en varios procedimientos no existe (en la interfaz, tipo de procedimiento). El tipo de procedimiento es un valor requerido, seguramente sean datos antiguos o incorrectos. 

La pregunta es, preferís identificar y modificar los procedimientos con tipos de procedimiento a nulo o modificar el código para que contemple los casos de procedimientos sin familia?

Captura 1
![image](https://cloud.githubusercontent.com/assets/17451407/16519524/e6d2ffcc-3f89-11e6-8ef4-71cd678e7854.png)

Captura 2
![image](https://cloud.githubusercontent.com/assets/17451407/16519527/f007454e-3f89-11e6-9e63-4ca90ccdffcb.png)

**Comment by sgelabert-dgtic** [comment]
OK Sergio, fem un update noltros a BBDD i tornam a provar
