### ISSUE TITLE
Bug pantalla Administració Edificis

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#356]
En la pantalla de manteniment d'edificis accessible des del menú d'Administració, no apareix el mòdul lateral "Unitats Administratives relacionades". Donat és una relació requerida, no és possible donar d'alta nous edificis.

**Comment by slromero-indra** [comment]
Hemos estado revisando al dar de alta un edificio y sí aparece el módulo lateral(se adjunta imagen,se puede comprobar en el entorno indra).Por contra, hemos observado que al acceder a la edición de un edificio inicialmente no aparece el módulo pero si pulsamos el botón guardar, se observa el módulo al volver a cargar,¿Os referis a ese problema?

![image](https://cloud.githubusercontent.com/assets/17451407/16270274/0a1e0008-3896-11e6-9356-78b3f7b8d08a.png)

**Comment by slromero-indra** [comment]
Hemos observado que realmente el problema se debe después de pulsar sobre el botón volver (ya no se vuelve a observar las unidades relacionadas), seguimos revisando para ver si encontramos el problema.

**Comment by sgelabert-dgtic** [comment]
Efectivament, el mòdul lateral desapareix després d'haver executat la seqüència següent:
- Editar un edifici de llistat
- Pitjar el botó "torna"
- Entrar en "Crea un nou edifici"

**Comment by episano-dgtic** [comment]
En vuestro entorno funciona, pero en el nuestro se queda pensando indefinidamente y no llega a entrar en la pantalla de edición del edificio.

**Comment by slromero-indra** [comment]
Buenas, acabos de revisar en vuestro entorno de pruebas, hemos entrado al detalle de varios edificios y no hemos encontrado ningún problema (captura adjunta). Aún así, en la pantalla principal parece que no os cargan los datos, por favor, podéis ver si hay algún problema en los logs.


![image](https://cloud.githubusercontent.com/assets/17451407/16519294/262df160-3f88-11e6-8ee3-e53aa8b1135e.png)

**Comment by sgelabert-dgtic** [comment]
Ok, també devia ser problema de temporals. Ara funciona
