### ISSUE TITLE
Romandre en pantalla de tràmit al guardar

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#358]
Després de guardar un tràmit s'ha de romandre en la mateixa pantalla de tràmit. Actualment es retorna a la pantalla de procediments

**Comment by slromero-indra** [comment]
Buenas, hemos revisado la incidencia. Hemos realizado los siguientes pasos:
  - Acceder a un procedimiento y posteriormente entramos al detalle de un trámite, tras pulsar el botón de guardar, observamos que sigue permaneciendo en la pantalla de trámite. 
  - Hemos repetido las pruebas pero creando un trámite y se comporta de la misma manera.

Lo hemos probado tanto en nuestro entorno de caibter como en proves de caib, por favor, nos podéis decir como replicar el error.

**Comment by slromero-indra** [comment]
Tras hablarlo por teléfono, se ha visto que el funcionamiento deseado es el siguiente:
  - Cuando se cree un trámite, tras pulsar el botón de guardar, se deberá de quedar en el formulario (principalmente, porque al crear hay cierto módulos que no son visibles hasta que se guarda).
  - Cuando se edite un trámite, tras pulsar el botón de guardar, se deberá de volver a la pantalla de formulario.

Saludos!
