### ISSUE TITLE
Canvis per al bolcat inical de dades ROLSAC-SIA

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#366]
Es sol·licita efectuar els següents canvis per poder donar suport al bolcat inicial del catàleg de procediments dins SIA.
- Introduir un camp nou "Codi DIR3" en la pantalla d'Unitats Administratives no editable. El camp ha de situar-se just a continuació del camp "Codi estàndard"
- Introduir un camp nou "Codi SIA" en la pantalla de Procediments Administratius no editable. El camp ha de situar-se just a continuació del camp "Codi"
- Redefinir el camp Silenci Administratiu de la pantalla de Procediments Administratius perquè passi a ser un camp tipificat, amb valors mantenibles des d'una nova opció del Menú Administració.

**Comment by slromero-indra** [comment]
Buenas, la conversión de los valores de silencio administrativo (actualmente es un texto libre) a los nuevo valores tipificados como se realizará y quien se encargará de ello? Que patrón se utilizará para darle un valor tipificado?

**Comment by slromero-indra** [comment]
Revisando más en profundidad sobre la inclusión del silencio administrativo dentro de los procedimientos, hemos observado los siguientes detalles (que incrementarán el tiempo por encima de las 25 horas):
 - Actualmente, el silencio administrativo es un literal que está asociado a las traducciones de un procedimiento. Con el nuevo cambio, el silencio administrativo irá asociado a nivel de procedimiento (no de traducción). La traducción pues será la que se haya introducido en la nueva tabla mantenible que se vamos a crear para el silencio administrativo.
  - Al cambiar la ubicación, afectará al sac-api-client que utiliza el campo silencio administrativo (en seucaib se puede observar al entrar en un procedimiento) para que cargue correctamente el nuevo valor.

**Comment by sgelabert-dgtic** [comment]
Correcte Sergio, qualsevol canvi funcional en l'aplicació ha de quedar reflectit també a l'API de consulta.
Per tant, s'haurà de definir una nova entitat de consulta "Silenci Administratiu" i refer els mètodes de recuperació d'informació perquè ataquin a la nova entitat.
Quan pogueu ens passau doncs estimació de la tasca

**Comment by sgelabert-dgtic** [comment]
Errades localitzades:
- Falta traducció en català per la property 'menu.silenci_adm':
```
2016-09-20 08:00:54,935 ERROR [org.springframework.web.servlet.tags.MessageTag] No message found under code 'menu.silenci_adm' for locale 'ca'.
javax.servlet.jsp.JspTagException: No message found under code 'menu.silenci_adm' for locale 'ca'.
```
- Després de passar els següents scripts de BBDD s'obté un error al accedir al menú d'Administració "Silenci Administratiu" i a la pantalla de "Procediments Administratius" del menú "Organigrama"

```
table RSC_SILADM creado.
COMMENT on column rsc_siladm.sil_codi 'CODI correcto.
table RSC_TRASIL creado.
table RSC_TRASIL alterado.
table RSC_PROCED alterado.
COMMENT on column rsc_proced.pro_codsil 'CODI correcto.
table RSC_PROCED alterado.
```

```
2016-09-20 08:18:46,131 WARN  [net.sf.hibernate.util.JDBCExceptionReporter] SQL Error: 942, SQLState: 42000
2016-09-20 08:18:46,131 ERROR [net.sf.hibernate.util.JDBCExceptionReporter] ORA-00942: la tabla o vista no existe
2016-09-20 08:18:46,132 ERROR [org.jboss.ejb.plugins.LogInterceptor] EJBException in method: public abstract es.caib.rolsac.utils.ResultadoBusqueda org.ibit.rol.sac.persistence.intf.SilencioAdmFacade.listarSilencioAdm(int,int,java.lang.String) throws java.rmi.RemoteException, causedBy:
net.sf.hibernate.exception.SQLGrammarException: Could not execute query
	at net.sf.hibernate.exception.ErrorCodeConverter.convert(ErrorCodeConverter.java:69)
	at net.sf.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:29)
	at net.sf.hibernate.impl.SessionImpl.convert(SessionImpl.java:4131)
	at net.sf.hibernate.impl.SessionImpl.find(SessionImpl.java:1557)
	at net.sf.hibernate.impl.QueryImpl.list(QueryImpl.java:49)
	at org.ibit.rol.sac.persistence.ejb.SilencioAdmFacadeEJB.listarTMSilencioAdm(SilencioAdmFacadeEJB.java:135)
	at org.ibit.rol.sac.persistence.ejb.SilencioAdmFacadeEJB.listarSilencioAdm(SilencioAdmFacadeEJB.java:90)
```
- Per altra banda falten afegir els scripts  DML de correspondència de Matèries i Normativa. Els adjunt a continuació:
[rolsac_sia_dml.txt](https://github.com/GovernIB/rolsac/files/481787/rolsac_sia_dml.txt)

- Finalment el commit s'ha fet únicament sobre el branch ROLSAC 1.4, quan aquest es un tiquet que s'ha obert sobre la versió 1.3,  per tant,  ha d'estar disponible per 1.3 i consolidat sobre 1.4. Podeu canviar-ho?

**Comment by slromero-indra** [comment]
Buenas, ya hemos arreglado el problema con el literal en catalán. Lo de la tabla, que no pueda encontrarla, puede ser que se tienen dos usuarios (rolsac y www_rolsac) y que las tablas sean propiedad de rolsac y falte los permisos? Si es así, confírmanos cuál es el usuario y lo podemos añadir al ddl.

Más tarde pasaremos el dml y los cambios de este ticket a la rama 1.3. 

Saludos!

**Comment by sgelabert-dgtic** [comment]
Teòricament no hauria de passar... En el DataSource del projecte es fa un alter session de l'usuari del pool de connexions www_rolsac cap a l'usuari propietari ROLSAC:
 <new-connection-sql>
        BEGIN
        EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA=ROLSAC';
        END;
    </new-connection-sql>
De totes formes faré la consulta amb el DBA

**Comment by sgelabert-dgtic** [comment]
L'alter session evita la creació dels sinònims públics sobre la BBDD, però requereix l'assignació de GRANTS sobre l'usuari del pool de connexions.
Donat que es tracta d'una configuració específica de la CAIB convé diferenciar-lo de la resta de scripsts. Crear un subdirectori caib dintre del directori de scripts de la versió que pertoqui i afegir-hi els grants:

GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SOLRPD TO WWW_ROLSAC;     
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SOLJOB TO WWW_ROLSAC;     
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SIATNR TO WWW_ROLSAC;     
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SIAMAT TO WWW_ROLSAC;     
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SILADM TO WWW_ROLSAC;
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_TRASIL TO WWW_ROLSAC;
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SOLRPD TO RSC_MNT;     
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SOLJOB TO RSC_MNT;     
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SIATNR TO RSC_MNT;     
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SIAMAT TO RSC_MNT;     
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SILADM TO RSC_MNT;
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_TRASIL TO RSC_MNT;

**Comment by sgelabert-dgtic** [comment]
En el manteniment de "Silènci Administratiu" es sol·licita a l'usuari la introducció del codi com a camp obligatori. Això es diferent de la resta de manteniments de l'aplicació on el codi es genera automàticament per l'aplicació m itjançant una seqüencia de BBDD (Tipus d'afectació, família, butlletins oficials,...)
Es sol·licita ocultar aquest camp de la pantalla i canviar l'assignació del codi perquè s'assigni per seqüència:
```
            <generator class="sequence">
                <param name="sequence">RSC_SEQ_ALL</param>
            </generator>
```

**Comment by slromero-indra** [comment]
Habíamos entendido que se quería una lista de valores tipificados con identificadores funcionales fijos, para poder establecer equivalencia y no depender de entornos (la secuencia variará los valores según entornos: desa, pre, pro).
Si se cambia a tener un identificador secuencial, establecer un valor por defecto implicará definir en la tabla de tipos de silencio administrativo un campo que indique que valor es el por defecto, ya que no habrá un identificador funcional al que asociarlo.
Confirmadnos si se quiere cambiar el identificador funcional por un identificador secuencial.

**Comment by sgelabert-dgtic** [comment]
A priori no veig cap problema perquè l'identificador canvii entre entorns. Es tracte d'homogeneïtzar el comportament de les pantalles i evitar cercar una solució particular per a cada requeriment.
Respecte a l'identificador per defecte només cal que estigui disponible a nivell de JSP. Si t'hi fixes et deman el mateix funcionament que té el selector "Forma d'inici" on el valor "Cap" no està a nivell de taula de BBDD.

**Comment by slromero-indra** [comment]
Pasamos a cambiar el id funcional por un id secuencial.
Respecto al valor por defecto creíamos que te referías a un valor específico de los tipos de silencio, no a indicar que no se ha elegido ninguno. Aclarado.

**Comment by sgelabert-dgtic** [comment]
Ok. Ja que hi sou, canviau també el valor del desplegable "Fi de la via administrativa" "ns/nc" per "Cap"

**Comment by slromero-indra** [comment]
Buenas, ya están los cambios subidos e integrados en la rama 1.3. Hay que tener cuidado en el sql, porque al cambiar el ID de silencio administrativo de String a Long, se han tenido que realizar varias sql para arreglarlo (borrando tablas y rehaciendo permisos). En resumen, se tiene que borrar las 2 tablas de silencio y la relación de procedimientos hacia ella y luego volverlas a crear con sus permisos. SQL ejecutadas en nuestros entorno:

```
--REINICAR LOS DATOS

ALTER TABLE RSC_PROCED DROP COLUMN PRO_CODSIL;
DROP TABLE RSC_TRASIL;
DROP TABLE RSC_SILADM;

CREATE TABLE RSC_SILADM
  (
    SIL_CODI NUMBER(19,0) NOT NULL ENABLE,
    PRIMARY KEY (SIL_CODI) 
  );

CREATE TABLE RSC_TRASIL
  (
    TSI_CODSIL NUMBER(19,0) NOT NULL ENABLE,
    TSI_NOMBRE VARCHAR2(256 BYTE),
    TSI_DESCRI VARCHAR2(4000 BYTE),
    TSI_CODIDI VARCHAR2(2 BYTE) NOT NULL ENABLE,
    PRIMARY KEY (TSI_CODSIL, TSI_CODIDI),
    CONSTRAINT RSC_TSISIL_FK FOREIGN KEY (TSI_CODSIL) REFERENCES RSC_SILADM (SIL_CODI) ENABLE
  );
  
COMMENT ON COLUMN RSC_SILADM.SIL_CODI IS 'CODI SILENCI ADM';
ALTER TABLE RSC_PROCED ADD PRO_CODSIL NUMBER(19,0);
ALTER TABLE RSC_PROCED ADD CONSTRAINT RSC_PRO_CODSIL_SERV_FK foreign key (PRO_CODSIL) references RSC_SILADM;

GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_SILADM TO WWW_ROLSAC;
GRANT INSERT, SELECT, DELETE, UPDATE ON RSC_TRASIL TO WWW_ROLSAC;
```

Saludos!

**Comment by slromero-indra** [comment]
Buenas, los cambios en seucaib sobre el silencio administrativo se subirán al svn cuando se de por bueno la parte de ROLSAC (hay que tener en cuenta que ambas partes tienen que estar actualizadas a la vez, cualquier 'desincronización' en el sac-api-client.jar provocará problemas en seucaib).

**Comment by sgelabert-dgtic** [comment]
Bones, he fet un parell de correccions sobre el branch 1.3 del projecte:
- Seguia sense haver-hi traducció en català per` menu.silenci_adm' for locale 'ca'.
- La carpeta caib havia d'estar dins el directori /script/1.3/oracle/caib ja que fa referència a taules que només estan disponibles a partir de la versió 1.3
- Hi havia problemes amb l'encoding de caràcters amb accents.
- He modificat els scripts DML per separar la funcionalitats pròpies del ROLSAC-CAIB de les generals.
- He actualitzat la documentació de la versió 1.3

Tot i això, he detectat noves errades:
- El selector "Silenci Administratiu" ha de ser obligatori, tal i com ho era el camp textual anterior.
- Amb la introducció d'aquest darrer canvis es perd el valor emmagatzemat en el camp "Servicio o Sección responsable"

**Comment by slromero-indra** [comment]
Actualizado, el silencio es obligatorio (pensamos que al agregar Cap no hacía ya falta, se ha quitado el cambio) y ahora carga correctamente el servei responsable que le faltaba cargar el dato. Está en ambas ramas (rolsac-1.3 y rolsac-1.4).

**Comment by episano-dgtic** [comment]
Si se indica una categoría de silencio administrativo en la pestaña de catalán, en castellano no aparece dicha opción ni siquiera tras haber guardado el procedimiento

**Comment by episano-dgtic** [comment]
En la sede si haces búsquedas textuales da como resultado -1 y no devuelve resultados. 
[error_api_sede.txt](https://github.com/GovernIB/rolsac/files/561795/error_api_sede.txt)

**Comment by slromero-indra** [comment]
Buenas, normalmente cuando da un resultado -1 suele ser por mala conexión con ROLSAC o SOLR. En este caso parece que el problema se debe al silencio administrativo. Hemos vuelto a probar y desplegar rolsac/seucaib y no hemos sido capaces de replicar el error. Por si acaso, he vuelto a subir sac-api-client a seucaib.

Por favor, puedes probar a descargarlo todo y desplegarlo de nuevo a ver si desaparece el error?
