### ISSUE TITLE
BUG en producción: En algunos procedimientos no se puede descargar los ficheros. 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#368]
No he detectado aun la causa, pero en algun procedimeinto devuelve un null en todos los ficheros adjuntos.  Pese a que en el backoffice se pueden visualizar.

EX en producción:
https://www.caib.es/seucaib/ca/200/persones/tramites/tramite/2483781

EX de desarrollo:
http://sdesapplin12:58080/seucaib/ca/200/ciutadania/tramites/tramite/138430

Si consigo que se pongan visibles con cambios de datos os indico la razón

**Comment by episano-dgtic** [comment]
En pruebas podéis replicarlo en:
https://proves.caib.es/seucaib/ca/200/ciutadania/tramites/tramite/747799

Concretamente en el trámite de presentación

**Comment by slromero-indra** [comment]
Buenas, podéis darle permisos al usuario e24394731b para que pueda acceder a sistraback. Puedo acceder pero no veo nada (no sé si es permisos o asignarle alguna propiedad más).

![image](https://cloud.githubusercontent.com/assets/17451407/17697591/0d480918-63b6-11e6-8771-40b9d6ccf7d7.png)

He mirado cosas básicas y no tiene relación con si es un modelo, debe ser alguna propiedad del trámite que está a null, sigo mirando el código fuente.

Saludos!

**Comment by episano-dgtic** [comment]
Efectivamente no estabas dado de alta en pruebas. Te he dado de alta, aunque siendo system podías hacerlo sin problemas.

**Comment by episano-dgtic** [comment]
adjunto los logs de producción, repliqué el problema a las 13:06

**Comment by episano-dgtic** [comment]
la url de los logs, http://tn.caib.es/ZPerBbKA 
Le he dado acceso a e24394731b

**Comment by slromero-indra** [comment]
Gracias, podemos acceder a rolsacback y descargarnos el fichero. Seguimos con la investigación.

**Comment by episano-dgtic** [comment]
Las url de desarrollo son:
http://sdesapplin12:58080/seucaib/ca/200/ciutadania/tramites/tramite/1384457
http://sdesapplin12:58080/seucaib/ca/200/ciutadania/tramites/tramite/1384303

En desarrollo he puesto todos los trámites a visibles, excepto los trabajados apartir de vuestras modificaciones que quedan a null.  Para asegurar tb. he puesto a null la fecha de caducidad. La fecha de publicación la debo respectar ya que actualmente es modificable por backoffice.

**Comment by slromero-indra** [comment]
Se han actualizado las ramas 1.3 y 1.4 de rolsac y también seucaib (ramas 1.1 y 1.2). Hemos visto 3 problemas:
 - ROLSAC: Si se produce un error no controlado se pierde el error sin poder ser capturado ni mostrado el error por log. Hemos añadido una captura para errores genéricas que además devuelve un error.
 - ROLSAC: En los trámites se ocultó el campo validación pero se utiliza en las comprobaciones y, en caso de no ser público, da un error como no disponible (error 404). Habría que ver si actualizar todos los trámites como PÚBLICO o quitar dicha comprobación.
 - SEUCAIB.: Ignora el error al realizar la petición a ROLSAC mediante el API. Es decir, si se produce un error (por ejemplo, documento no disponible o hay un error interno) no devuelve ningún error e  intenta descargarlo por pantalla (produciendo que se descargue como en el error un null). En caso de devolver un código distinto al 200 (código cuando todo ha sido correcto), se devolverá al usuario el error que devuelva ROLSAC.
 Además, se ha añadido más logs para tener claro el error que se ha producido en ROLSAC.
 Se debe de desplegar en el entorno de proves o desarrollo de caib y los procedimientos que devuelve el fichero null, probar y pasarnos el log.

**Comment by episano-dgtic** [comment]
Pasé los scripts el jueves. 
Decisiones a tomar=> Definir com se debería comportar rolsac cuando se le pide un documento de un trámite. Actualmente, se comprueba si el trámite es visible (se mira campos fecha de publicación, fecha caducidad y validación) y si el procedimiento es visible. Se plantean las siguientes dos opciones:
·         Mantener las dos comprobaciones pero del método es visible de los trámites se excluirá los campos fecha de caducidad y el campo validación.
·         Excluir la comprobación del trámite, sólo dejando la comprobación de si es un procedimiento visible.
