### ISSUE TITLE
Canvi literals aplicació

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#370]
Es sol·licita canviar els següents literals de l'aplicació:
- Del menú d'Administració com en les pantalles d'administració associades:
     - Canviar "Família" per "Tipus de procediment"
     - Canviar "Tipus d'iniciació" per "Forma d'inici"
- Del mòdul d'Auditories que apareix en diferents pantalles:
     - Canviar "Nombre" per "Nom" quan l'idioma de navegació és Català

**Comment by episano-dgtic** [comment]
Falta: 
Del mòdul d'Auditories que apareix en diferents pantalles:
    Canviar "Nombre" per "Nom" quan l'idioma de navegació és Català

**Comment by slromero-indra** [comment]
Buenas, estamos revisando y no encontramos el error. Hemos visto que en el sac-back2-tags_ca.properties está el texto correcto como NOM (hemos revisado que está en ambas ramas).

**Comment by sgelabert-dgtic** [comment]
![image](https://cloud.githubusercontent.com/assets/17268396/19598123/629732b0-9799-11e6-9f81-c598d9c16a07.png)

Ejecutamos Rolsac v1.3 build: 13-10-2016 12:38:00(b567342)
