### ISSUE TITLE
Canvi mòdul estadístiques d'accés

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#372]
Es sol·licita canviar el mòdul d'estadístiques d'accés de Fitxes Informatives, Procediments Administratius, Unitats Administratives i Normativa perquè registri únicament els accessos de lectura fets per als frontals a través de l'API.
Actualment el comptador s'actualitza quan hi ha actualitzacions des del backoffice.

**Comment by rsanz-indra** [comment]
Se han eliminado los registros de estadísticas que se pusieron.
Se ha subido el cambio en las ramas 1.3 y 1.4
