### ISSUE TITLE
Control obligatorietat tipus de norma

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#376]
Sol·licit controlar l'obligatorietat del camp "Tipus de norma" de la pantalla de Normatives, a fi que no deixi emmagatzemar la norma sense aquest camp.

**Comment by episano-dgtic** [comment]
Lo he probado en la versión de CAIBTER y en nuestra versión y no hay ningun control respecto al campo "Tipo normativa" ni en la creación, ni en la modificación de normativa.
