### ISSUE TITLE
Independitzar URL endpoint WS del client sac-api-client.jar

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#380]
Es sol·licita independitzar la propietat  es.caib.rolsac.api.v2.url que especifica  la URL del enpoint de l'API de ROLSAC del client sac-api-client.jar 
Concretament es sol·licita canviar la lectura de la propietat de sistema des del client per la parametrització de la URL en la cridada a l'API, de manera semblant a com s'especifica l'estratègia de connexió.

**Comment by slromero-indra** [comment]
Para probar este cambio en sede habria que añadir la nueva url.

**Comment by slromero-indra** [comment]
Hemos detectado que el api de rolsac hace llamadas internas en los que no se está trasladando la url de Rolsac. Como medida provisional habría que mantener las 2 propiedades, la antigua (es.caib.rolsac.api.v2.urlPrefix) y la específica por proyecto.

**Comment by sgelabert-dgtic** [comment]
Així no hi guanyem res, seguim sense complir els estàndards i ara tenim dues propietats que fan el mateix...
La solució definitiva implicaria redistriuir de nou el client en totes les aplicación que utilitzen l'API? Si és així se li ha de donar solució definitiva abans del pas a PROducció. 
Digam coses i en tot cas canvio prioritat de la tasca

**Comment by rsanz-indra** [comment]
Como hemos comentado estamos en ello y esperamos tenerlo adaptado hoy.
El workaround que comentamos es hasta tener este cambio solucionado.

**Comment by slromero-indra** [comment]
Buenas, ya están subidos todos los cambios en todos los proyectos. Además, ya está actualizado el sac-api-client en todos los proyectos para que se conecten a rolsac de manera independente. Os paso la nueva propiedad que debería ir en cada uno de los proyectos:

**GUSITE**
       es.caib.gusite.url.rolsac = http://localhost:48080/sacws-api/services/

**SEUCAIB**
       es.caib.seucaib.url.rolsac=http://localhost:48080/sacws-api/services/
	
**WEBCAIB**
       es.caib.webcaib.url.rolsac = http://localhost:48080/sacws-api/services/
