### ISSUE TITLE
Canvis pestanya cercador de procediments

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#381]
Sol·licit realitzar les següents millores sobre el cercador de procediments:
- Afegir filtre "Silenci Administratiu"
- Afegir filtre "Codi SIA" i "Bolcat a SIA" (Alta/Baixa/Cap)
- Canviar literal "Inici:" per "Forma d'inici", "Vigens" per "Tràmit vigent" i "Telemàtic" per "Tràmit telemàtic", "Públic Objectiu" per "Públic objectiu" i "Identificador tràmit" per "Identificador del tràmit".
- Revisar funcionament filtre "Vigent" , ja que hauria de retornar els procediments amb algun tràmit obert i ara no ho fa.
- Afegir opció "Cap" als selectors "Públic Objectiu", "Matèria", "Tipus de procediment", "Forma d'inici", "Fi de la via Administrativa" i "Silenci Administratiu". L'establiment del valor "Cap" en un selector ha de permetre determinar els procediments que no tenen valor introduït.
- Col·locar els camps del selector avançant en el següent ordre:
1.- Codi SIA
2.- Estat SIA 
3.- Forma d'inici
4.- Silenci administratiu
5.- Fi de la via administrativa
6.- Públic objectiu
7.- Tipus de procediment
8.- Matèries
9.- Identificador del tràmit
10.- Tràmit vigent
11.- Tràmit telemàtic

**Comment by slromero-indra** [comment]
Pendiente el funcionamiento del filtro "Bolcat a SIA" hasta que se finalice la implementación de SIA.

**Comment by episano-dgtic** [comment]
He detectado un par de bugs, gracias al actual funcionamiento: 

1) La pantalla del buscador se ha perdido la posibilidad de ordenar por código, tipo procedimiento y fecha actualización, los resultados de la búsqueda.
2) Con el campo silencio administrativo, y forma de inicio de los procedimientos hay cache. Es decir, si busco procedimientos sin silencio y accedo a él, me muestra los datos del silencio del procedimiento que visualicé anteriormente y no el campo vacío.
3) El filtro por identificador del trámite no funciona. Cuando funcione, os indicaremos que se incluya ese valor en la pantalla del trámite ya que actualmente sólo podemos saber los identificadores del trámite con la bd.

**Comment by sgelabert-dgtic** [comment]
No s'han solucionat els errors detectats per n'Estela

**Comment by sgelabert-dgtic** [comment]
- El filtre per id-Tramit segueix sense funcionar.
- Afegir el camp "Clau primària" a la pantalla de Tramits
- L'ordenació per Tipus de Procediment tampoc funciona. Adjunt captura de pantalla
![ordenacioporced](https://cloud.githubusercontent.com/assets/17268396/26777892/4bd2cfbe-49df-11e7-9464-88f739db84eb.jpg)
