### ISSUE TITLE
Bug elements multimèdia pantalla Edificis

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#383]
En la secció multiidioma de la pantalla d'Edificis del menú Administració s'han localitzat les següents errades:
- No s'eliminen els fitxers associats a "Foto gran"
- Qualsevol fitxer associat a "Foto gran" o "Foto petita", s'acaba emmagatzemant dins el camp "Plànol"
- Canviar el literal "Pláno" per "Plano" en l'idioma castellà

**Comment by episano-dgtic** [comment]
En nuestro entorno sigue igual, incluso la palabra plano.

**Comment by slromero-indra** [comment]
Buenas, me puedes confirmar si la versión de vuestro entorno es la rama rolsac-1.4.1? Solo hemos comiteado el cambio en esa rama, si queréis lo pasamos a rolsac-1.4

**Comment by episano-dgtic** [comment]
1.4.0.2
