### ISSUE TITLE
Recuperació col·leccions de tràmits amb elements nuls

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#386]
Sol·licit que es revisin els mapejos definits en Hibernate entre Procediments i Tràmits  per evitar que operacions com procedimiento.getTramites() retornin elements nuls

**Comment by slromero-indra** [comment]
Hemos realizado un análisis previo observando que las entidades que pueden estar afectadas son:
-	AgrupacionHechoVital
•	Lista de hechosVitalesAgrupacionHV.
-	AgrupacionMateria
•	Lista de materiasAgrupacionM.
-	Ficha
•	Lista de documentos y enlaces.
-	HechoVital
•	Lista de hechosVitalesProcedimientos
-	Procedimiento
•	Lista de trámites y documentos.
-	UnidadAdministrativa
•	Lista de hijos y fichasUA.

La solución pasaría por utilizar en el mapeo de Hibernate un Set en lugar de un List. Este cambio tendría implicaciones a nivel de código ya que se cambia el tipo de datos. 

Para minimizar el impacto se podría hacer lo siguiente para intentar mantener el tipo de datos:
-	Mapear los elementos  en una nueva variable mapeada como tipo Set.
-	Mapear en el hbm el cambio de tramites a esta nueva variable
-	Hacer una conversión del Set en List y viceversa
o	El método set transformará el List en Set
o	El método get transformará el Set en un List

Para validar la solución habría que realizar una prueba de concepto con una entidad (p.e. Procedimientos y Trámites) y ver que se puede mantener la lógica de recuperación y guardado con la solución propuesta.
A partir de aquí con la solución validada, se podría evaluar una estimación global del cambio.

**Comment by sgelabert-dgtic** [comment]
Abans de fer aquests canvis m'agradaria determinar quina es la causa del problema, és a dir, perquè les col·leccions recuperades venen amb elements nuls. El mapeig tipus List no és en principi un mapeig estrany... Segurament els problemes provinguin de l'ordenació de la col·lecció.
En cas que no trobem causa/solució analitzaríem la solució que porposes.

**Comment by slromero-indra** [comment]
Se va a proceder a buscar donde se produce el problema del mal reordenadomiento. Cuando se encuentre el problema, además de solucionarlo, sería correcto realizar una prueba de concepto con los siguientes cambios:

- El getTramites, antes de devolver la lista, borrará los elementos nulos y reasignará el parámetro orden a cada uno de los tramites.
- El setTramites, antes de setear la lista, recorrerá de nuevo los elementos y reasignará el valor de orden.

Es recomendable realizar esa prueba de concepto para poder solucionar los problemas de los trámites ya mal ordenados.
