### ISSUE TITLE
Problemes amb el llançament de la indexació manual de pendents

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#387]
Tenim problemes per llançar la indexació manual d'elements pendents d'indexació a ROLSAC. 
Adjunt captura de pantalla, on es pot observar errada JavaScript.
![indexarpendents](https://cloud.githubusercontent.com/assets/17268396/21767035/0bc46940-d672-11e6-9792-b83c542bf96c.jpg)

**Comment by sgelabert-dgtic** [comment]
Podríeu consolidar el canvi en el branch 1.4, versió 1.4.1?

**Comment by slromero-indra** [comment]
Perdona, a consolidar te refieres a que creemos un tag? Ahora mismo sólo hay 2 ramas, 1.4 y 1.5

**Comment by sgelabert-dgtic** [comment]
Perdona Sergio, no havia vist que també havíeu commitat sobre la 1.4
No fa falta fer res més. Provam i us dieim coses.
