### ISSUE TITLE
Migració de l'apliació a Jboss 5.2 EAP

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#388]
Es sol·licita preparar l'aplicació per al desplegament sobre JBoss 5.2 EAP.  Analitzar els canvis requerits per, si és possible, mantenir la compatibilitat de desplegament sobre el Jboss 3.2.8 actual. En cas contrari informau-nos dels canvis abans de commitar-ho sobre el branch 1.5 del respositori.

**Comment by rsanz-indra** [comment]
Se añade un documento con los problemas que se han encontrado en la migración a JBoss5 para ver las acciones a realizar.

**Comment by sgelabert-dgtic** [comment]
Ok amb les accions a realitzar. Comprovar també la coherència del fitxer application.xml i les llibreries desplegades.

**Comment by slromero-indra** [comment]
Hemos encontrado más incidencias con el despliegue al revisar el log del servidor:

	- Se despliega antes Rolsac que Seycon, con lo que da errores de autenticación (javax.naming.NameNotFoundException: es.caib.loginModule.SesionEJB not bound). Esto pasa porque hay código en Rolsac que se ejecuta al inicializar la aplicación (ServletContextListener) y se llama a un EJB y hace saltar la autenticación. Esto ya se detectó hace tiempo en la migración de Sistra a JBoss5 con los procesos automáticos, JBoss5 no despliega antes la carpeta deploy que la carpeta deploycaib, sino que lo despliega por orden alfabético los ears. Se puede solucionar fácilmente renombrando el ear de seycon (o los de las aplicaciones). Hemos probado de esta forma y funciona correctamente.
	
	- Rolsac usa un interceptor de Hibernate que usa clases que no existen en JBoss5. Este interceptor es es.caib.rolsac.persistence.hibernate.ConnectionInfoInterceptor y parece que realiza un log al hacer el postflush, por lo que la solución pasaría por eliminar dicho interceptor. Hemos probado de esta forma y funciona correctamente.

 Quedaría adaptar la generación del ear para tener en cuenta la inclusión de librerías según la versión de JBoss. Se podría hacer que el ANT distinguiese mediante una propiedad si se debe generar para JBoss3 o JBoss5 y que genere el ear como toca. Otra opción es que el ANT genere directamente el ear para JBoss5. 
 
 Por último habría que ver la dedicación a esta tarea porque se han dedicado unas 29 horas. Por tanto supondrá un coste mayor de 24 horas y habría que ver si se debe confeccionar un documento de estimación en el que se refleje la dedicación realizada y la que queda pendiente.

**Comment by sgelabert-dgtic** [comment]
Respecte al canvi de nom dels ears ho consultaré amb serveis web. No sé com es solucionà amb sistra però en principi el nom de l'ear ha de coincidir amb el codi d'aplicació i no sé si voldran canviar el nom de seycon. Us dic coses.
Pel que fa als interceptors postflush, efectivament actualitzen log de debug. Si donen problemes es poden eliminar.
Preferiblement la tasca ANT hauria de permetre l'empaquetat per Jboss 5 i Jboss 3.
Finalment, pel que fa a les hores enviau-me quan pogueu document amb les hores imputades (podeu incloure el detall de les tasques del pdf i comentaris d'aquest tiquet) i estimació de les tasques a realitzar

**Comment by sgelabert-dgtic** [comment]
Després de parlar amb serveis web, m'indiquen que tenen mecanismes per forçar el desplegament previ de seycon abans que ROLSAC. A falta de fer les proves, podem obviar en principi aquest problema

**Comment by rsanz-indra** [comment]
Ok. Nosotros de momento en nuestro entorno renombraremos el ear de seycon para forzarlo (si nos indicáis lo que va a hacer serveis web lo replicaremos).

**Comment by sgelabert-dgtic** [comment]
Adjunt log del servidor d'aplicacions Jboss 5 amb errors de desplegament.
Configuració d'empaquetat:
```
# Versio de jboss. Valors posibles: 3.2 , 5.2
jboss.version=5.2
# versio  de jboss xml. Valors posibles: 3.2
jboss-xml.version=3.2
```
[rolsac-jboss5-server.txt](https://github.com/GovernIB/rolsac/files/749789/rolsac-jboss5-server.txt)

**Comment by slromero-indra** [comment]
Buenas, revisando el error he visto que el problema se debe principalmente a un error por el cron. 
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.scheduling.config.ScheduledTaskRegistrar#0': Invocation of init method failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1420)

```

He sido capaz de replicar el error eliminando del jboss-service.xml de rolsac el cron para sia:
` es.caib.rolsac.sia.jobpendientes=0 0 10 * * ?`

Por favor, podéis comprobar que tiene el cron para sia y solr en el jboss-service.xml de rolsac y que no hay ningún espacio?

**Comment by sgelabert-dgtic** [comment]
Faltaven les propietats que indiques. El desplegament és correcte renombrant seyconsession-ear.ear a 00seyconsession-ear.ear
Sistmes no posa pegues al renombrament del fitxer

**Comment by sgelabert-dgtic** [comment]
Us pas la versió que hem desplegat a PREproducció corresponent al tag 1.5.3 però empaquetada canviant la propietat  jboss.version=5.2. http://tn.caib.es/qWgeWwUc
Les errades que hem localitzat són les següents:

- A la molla de pa, l'enllaç de la UA redirigeix a index.jsp
(https://proves.caib.es/rolsacback/unidadAdministrativa/cambiarUA.do?ua=6&redirectTo=https://proves.caib.es/rolsacback/index.jsp)  en canvi amb Jboss 3.2.8 redirigeix cap a quadreControl.do, unitatadm.do, catalegProcediments.do, fitxainf.do, normativa.do o personal.do

- Els popups que mostrer l'arbre de UAs no funcionen. Apareix una erra JS (`TypeError: el.offset(...) is null`)

- Tampoc ens està funcionant el traspàs de normativa des del BOIB, ni l'accés al servei de traducció. Pareix que no és problema de connectivitat. En qualsevol cas, aquest això ho revisem noltros amb sistemes.

**Comment by slromero-indra** [comment]
Buenas, se han corregido las problemáticas referentes a la "molla de pa" y al offset (afectaba a diferentes popups incluido el de calcular coordenadas de la página de edificios). Hemos verificado que funciona tanto en jboss 5 como en jboss 3.

Si debemos revisar algo con respecto al punto 3 nos lo indicáis.

**Comment by slromero-indra** [comment]
¿Se puede dar la incidencia por cerrada?
