### ISSUE TITLE
Modificar disseny classe ArxiuServelt de l'API-ROSLAC

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#389]
Arran de l'anàlisi efectuat en #388  es sol·licita traslladar la lògica del servlet d'arxius relacionada amb l'accés i control d'accés a fitxers interns a la capa d'EJB

**Comment by slromero-indra** [comment]
Buenas, se ha observado que existe también otra clase con la misma problemática, ArxiuInternServlet. Se va a proceder también a cambiar ya que los cambios son muy parecidos.
