### ISSUE TITLE
Control de la qualitat de les dates en els tràmits

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#391]
Es sol·licita efectuar els següents canvis sobre la pantalla de tràmits:
- Controlar que la data de publicació de qualsevol tràmit sigui posterior o igual a la data de publicació del procediment.
- Establir com a valor per defecte la data de publicació del procediment (obligatòria) en el camp data de publicació del tràmit.
- Fer obligatori el camp data de publicació en els tràmit.
- Fer obligatori el camp data d'inici en els tràmits.
- Controlar que la data d'inici del tràmit sigui posterior o igual a la data de publicació de tràmit.

**Comment by slromero-indra** [comment]
Buenas,  
Hemos revisado los cambios solicitados, y realizando las pruebas nos han surgido las siguientes preguntas:

- Al crear un trámite hemos aplicado por defecto la fecha de publicación del procedimiento. Si el trámite ya existe y tiene una fecha posterior o no está indicada (vacía) ¿Debemos realizar alguna modificación?
- Hemos visto que se podría crear un procedimiento con sus trámites de manera correcta, y posteriormente   modificar la fecha de publicación del procedimiento, y al guardar no se controla que los tramites tengan una fecha posterior o igual a la del procedimiento, permitiendo inconsistencias. ¿queréis que al guardar el procedimiento incluyamos esta validación?

**Comment by sgelabert-dgtic** [comment]
-En el primer cas, si el tràmit ja existeix i té una data de publicació nul·la no hauria de deixar guardar el tràmit, ja que hem fet la data de publicació de tràmit sigui obligatòria. Si es posterior a la publicació estam en el cas correcte. Finalment, si és anterior a la publicació del procediment tampoc hauria de deixar guardar i avisar a l'usuari del motiu.
- En el segon cas, cal establir un control a nivell de procediment que no deixi guardar i avisi quan hi ha tràmits amb data de publicació anterior a la data de publicació del procediment.

**Comment by slromero-indra** [comment]
Respecto al primer punto, es lo que se ha implementado, lo dejamos como está. 
Respecto al segundo punto Añadiremos este control.

**Comment by slromero-indra** [comment]
Buenas, el commit anterior 205bb7e , lo realizamos sobre la rama 1.5, tenemos listos los cambios del último punto, ¿se podría subir esta incidencia en la versión 1.5.4, o deshacemos los cambios para incorporarlos en una nueva rama 1.6?

**Comment by sgelabert-dgtic** [comment]
No hi ha pega, ho incorporam a la 1.5.4 i ho arrossegam cap a la 1.6

**Comment by sgelabert-dgtic** [comment]
Pareix que hi ha un error en la comporvació de la data de publicació del tràmit perquè sigui **igual** o posterior a la data de publicació del procediment. Endemés cal  que les comporvacions tinguin en compte l'hora i el minut cosa que ara no està passant (dd/mm/yyyy hh:mm).
Adjunt captura de pantalla, amb procediment i tràmit amb la mateixa data de publicació
![controldatapublicacio](https://user-images.githubusercontent.com/17268396/27168449-f95ba778-51a5-11e7-8e29-26c551790515.jpg)

**Comment by slromero-indra** [comment]
Buenas,
Lo que comentas es lo que se ha realizado, haciendo pruebas, detectamos que nos sucedía este error a causa de los segundos, que no se muestran por pantalla, y aunque parezcan fechas iguales no lo eran, este caso lo solucionamos, e hicimos múltiples pruebas para validarlo,  es posible que sea tema de los milisegundos, o algún otro tema, en cualquier caso lo revisamos, no debería pasar.

**Comment by slromero-indra** [comment]
Buenas,
Hemos intentado reproducirlo pero no lo conseguimos, hemos añadido las modificaciones para que los milisegundos no afecten, pero no hemos encontrado ningún caso en que nos diera el error que mostrabais. 
¿podéis verificar si con esta modificación continua ocurriendo?
