### ISSUE TITLE
Errada en la informació de versionat

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#392]
Després de l'empaquetat de l'aplicació en el branch apareix informació incorrecte sobre el versionat.
Adjunt captura de pantalla
![rolsac1_5](https://cloud.githubusercontent.com/assets/17268396/23541843/2a52f3b2-ffea-11e6-937f-6aec7139581d.jpg)

**Comment by sgelabert-dgtic** [comment]
Cal canviar el valor de la propietat rolsac.version=1.5 del fitxer default.properties perquè es corregeixi la informació del logo del rolsac

![image](https://cloud.githubusercontent.com/assets/17268396/24162348/801fb600-0e67-11e7-9d34-9ac95de7c66a.png)

**Comment by slromero-indra** [comment]
Buenas, en el properties se cambió al valor 1.5 pero resulta que el valor resaltado de la imagen está introducido a la fuerza. Se ha modificado para que lo lea según el valor de rolsac.version del fichero default.properties.
