### ISSUE TITLE
Control integritat UAs i procediments administratius

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#395]
Hem detectat un error d'integritat referencial amb UAs eliminades que tenen procediments administratius relacionats. Concretament falta controlar la integritat dels camps PRO_CODUNA_RESOL i PRO_CODUNA_SERV amb la RSC_UNIADM RSC_UNA_PK
A banda de controlar-ho per BBDD s'ha de controlar via aplicació, de manera que informi que no es possible esborrar una UA amb continguts relacionats.

**Comment by sgelabert-dgtic** [comment]
No s'han definit les restriccions a nivell de base de dades, tal i com es demanva a la incidència. 
Cal afegir script rolsac_update_schema_from_1.5.3_to_1.5.4.sql amb la definició de les constraints

**Comment by slromero-indra** [comment]
Buenas, en nuestro entorno tenemos FKs que relaciona la tabla procedimentos con UAs (a través de los campos PRO_CODUNA, PRO_CODUNA_RESOL y PRO_CODUNA_SERV), nos puedes confirmar si en vuestro entorno también existen? Si no es así, generamos la sql con las constraints.

**Comment by sgelabert-dgtic** [comment]
Adjunt resultat de les constraints definides sobre la taula RSC_PROCED [constraints.sql](https://github.com/GovernIB/rolsac/files/1077547/resultat_sql.txt). Com veis no estan definides.
Per altra banda, falta crear script rolsac_create_schema.sql complet, dintre de la branca 1.5

**Comment by slromero-indra** [comment]
Buenas, de los 3 campos que hay de referencia hacia SIA, en los constraint sólo hay 2, faltaba PRO_CODUNA_SERV.

Se ha añadido un script de la 1.5.4 a la 1.5.5. que de momento sólo tiene la inclusión de la FK que faltaba, además se han añadido el rolsac-create-schema (incluye la restricción nueva).
