### ISSUE TITLE
Bug ordenació documents relacionats amb procediments

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#396]
S'ha detectat un bug en l'assignació de l'ordre dels documents relacionats amb els procediments.
Pareix que al modificar l'ordre d'un document i posteriorment editar-ne algun (accedir a la pantalla de modificació i guardar), s'emmagatzema un ordre incorrecte al document.

**Comment by slromero-indra** [comment]
viene de: #2229 Recuperació incorrecte de documents relacionats amb el procediment

Adjuntamos una consulta para identificar que procedimientos existen actualmente en la BBDD con esta problemática. y un script para modificar el campo orden de los procedimientos detectados.

```SQL
---- LISTA LOS PROCEDIMIENTOS QUE CONTENGAN DOCUMENTOS CON EL CAMPO "ORDEN" DUPLICADO (VARIOS DOCUMENTOS DE UN PROCEDIMIENTO CON EL MISMO ORDEN)
select * from (
  select doc_codpro, count(doc_orden) documentos_duplicados 
  from rsc_docume where doc_codpro is not null 
  group by doc_codpro, doc_orden
) where documentos_duplicados > 1
```

```SQL
--- ACTUALIZA EL CAMPO ORDEN DE LOS DOCUMENTOS DEL PROCEDIMIENTO INDICADO (Sustituir XXXXXXX por el código de procedimiento)
DECLARE
   ORDEN NUMBER := 1;
begin
  for i in (select * from rsc_docume where doc_codpro = XXXXXXX order by doc_orden) loop
    update rsc_docume set doc_orden= ORDEN where doc_codi = i.doc_codi;
    ORDEN := ORDEN + 1;
  end loop;
end;
```

**Comment by slromero-indra** [comment]
Tratado en el commit 9087cf58397fd4c909e23d2bf125246b20f3fcb1

**Comment by sgelabert-dgtic** [comment]
Adjunt script que aglutina els altres dos:

```
SET SERVEROUTPUT ON;
DECLARE
  ORDEN NUMBER := 1;
  /* CURSOR DOCUMENTS PROCEDIMENTS AMB ORDRE INCORRECTE */
  CURSOR c_proced IS
  select * from (
  select doc_codpro, count(doc_orden) documentos_duplicados 
  from rsc_docume where doc_codpro is not null 
  group by doc_codpro, doc_orden
  ) where documentos_duplicados > 1;
  
  proced c_proced%ROWTYPE;
BEGIN
  OPEN c_proced;
  LOOP
    FETCH c_proced INTO proced;
    EXIT WHEN c_proced%NOTFOUND;
    dbms_output.put_line('proced:' || proced.doc_codpro);
		  FOR i IN (select * from rsc_docume where doc_codpro = proced.doc_codpro order by doc_orden) LOOP
                        update rsc_docume set doc_orden= ORDEN where doc_codi = i.doc_codi;
                        dbms_output.put_line('update rsc_docume set doc_orden=' || ORDEN || ' where doc_codi =' || i.doc_codi || ';');
                        ORDEN := ORDEN + 1;
		  END LOOP;
    END LOOP;
  CLOSE c_proced;
END;
```

**Comment by sgelabert-dgtic** [comment]
Es torna a reproduir el problema
Adjunt Excel amb els resultats de la select:
```
---- LISTA LOS PROCEDIMIENTOS QUE CONTENGAN DOCUMENTOS CON EL CAMPO "ORDEN" DUPLICADO (VARIOS DOCUMENTOS DE UN PROCEDIMIENTO CON EL MISMO ORDEN)
select * from (
  select doc_codpro, count(doc_orden) documentos_duplicados 
  from rsc_docume where doc_codpro is not null 
  group by doc_codpro, doc_orden
) where documentos_duplicados > 1 
```
[export_documents.xlsx](https://github.com/GovernIB/rolsac/files/1127410/export_documents.xlsx)

**Comment by slromero-indra** [comment]
Lo revisamos.

**Comment by sgelabert-dgtic** [comment]
S'han tornat a queixar per problemes amb doc. relacionats amb procediments eliminats que següeixen apareixent a la Seu Electrònica.
Adjunt captures de pantalla d'un cas concret **procID:2975088**
![ordenacio-rolsac](https://user-images.githubusercontent.com/17268396/28067737-c803ef9e-6642-11e7-8490-5b0929ac6cd0.jpg)
![ordenacio-seucaib](https://user-images.githubusercontent.com/17268396/28067744-cf04f5a4-6642-11e7-906f-8f49af3ecbf0.jpg)
![ordenacio-bbdd](https://user-images.githubusercontent.com/17268396/28067758-da9006ac-6642-11e7-814a-76a8fffc75f4.jpg)

**Comment by slromero-indra** [comment]
Buenas, hemos conseguido sólo una manera de poder replicar el problema pero teniendo dos pestañas abiertas con el mismo navegador. El mecanismo para generar el problema es en una pantalla generar nuevos documentos y alterar el orden mientras en la otra pestaña, tras haber realizado los cambios anteriores, se debe también realizar cambios en el orden.  

El problema se debe porqué los datos en la sesión y en la base de datos se descuadran produciendo que algunos datos se actualicen incorrectamente. Se va a proceder a cargar la información en vez de con session.load, probar con session.get y forzar refrescos de los datos y la utilización de sesion.saveOrUpdate. 

Hemos observado también que el método genera es demasiado complejo y realiza demasiados pasos (se llama desde el CatalegProcediments --> GuardadoAjaxUtil.actualizarYOrdenarDocumentosRelacionados --> al DocumentoResumenFacadeEJB.actualizarOrdenDocs que está deprecated). 

Vamos a proceder a realizar más pruebas con el session.get y session.saveOrUpdate para solucionar dichos problemas. Si queréis evitar mejor estos problemas, podemos ver la posibilidad de añadir un índice de unicidad que provocaría un error cuando se produjesen solapados por lo que ya no se producirían estos errores.

**Comment by sgelabert-dgtic** [comment]
He fet un parell de proves i he aconseguit reproduir l'error amb la següent seqüència de passes:
- S'elimina un document de la llista de documents
- Sense guardar es canvia l'ordre a dos documents més de la llista
- A continuació es guarden els canvis (això genera duplicats en el camp ordre)
- Si es surt i es torna a entrar en una pantalla (pareix que hi ha una errada JS que bloqueja l'eliminació), es torna a eliminar un document i es guarden els canvis, la pantalla mostra un document menys però en base de dades no s'elimina (RSC_DOCUME)

**Comment by rsanz-indra** [comment]
Según hemos comentado anteriormente hemos estado revisando como se gestionan las colecciones en Rolsac y por decirlo suavemente es caótica.  En lugar de gestionar la adición/eliminación de elementos en las coleccione de forma centralizada en la clase "padre" está repartido la gestión por varios métodos y diferentes clases, cosa que suele producir inconsistencias entre los datos de caché de hibernate (tanto en la caché de primer nivel como en la de segunda nivel). En el código encontramos comentarios del tipo:

 ```
 <!-- amartin 2014/04/25: se ha desactivado esta caché al dar problemas con la ordenación de los documentos asociados al procedimiento(al reordenar documentos los valores en la BD cambiaban correctamente pero Hibernate seguía ofreciendo valores cacheados).
En Ficha.hbm.xml hay un list de documentos con esta misma configuración, con la caché activada, y no da problemas.
Desconozco el motivo.  -->
```
Al parecer con la ordenación de documentos se deben producir casuísticas que provocan errores y tal como está el código es díficil de depurar porque el código está repartido entre distintas clases y existen dependencias (hay métodos implicados que se llaman desde otras clases).

Nuestra propuesta sería crear un método específico en ProcedimientoFacade que se encargue de realizar la operación de reordenación de documentos, asegurándose de que el Procedimiento se queda con la información consistente. Además no estaría de más crear una clave de unicidad a nivel de BBDD (id ficha, id documento y orden) como método de protección.

**Comment by rsanz-indra** [comment]
Investigamos también la secuencia de pasos que comentas

**Comment by slromero-indra** [comment]
Buenas, hemos repetido la secuencia que nos comentas y sólo hemos sido capaces de replicarlo 1 vez de 6 intentos realizados.

**Comment by slromero-indra** [comment]
Hemos implementado en procedimientoFacadeEJB el reordenado de los documentos en un método específico y se ha incluido una restricción de unicidad como método de protección para evitar cualquier duplicado.

Sería conveniente realizar el mismo enfoque para los documentos de una ficha ya que se ha observado que existen dos clases, Documento y DocumentoResumen, ambas deprecated y que apuntan a la misma tabla, cosas que podría ocasionar problemas con la caché de hibernate.

**Comment by sgelabert-dgtic** [comment]
Cal tornar a passar el PLSQL https://github.com/GovernIB/rolsac/issues/396?_pjax=%23js-repo-pjax-container#issuecomment-301444964 abans de incloure les restriccions d'unicitat de l'script rolsac_update_schema_from_1.5.4_to_1.5.5.sql ?

**Comment by slromero-indra** [comment]
Buenas, para la subida a producción de ROLSAC, sólo hay que ejecutar esta instrucción (las otras 2 restricciones ya están ejecutadas en producción):

```
alter table rsc_docume add CONSTRAINT "RSC_DOC_ORDEN_UNIQUE" 
  UNIQUE ("DOC_CODFIC", "DOC_CODPRO", "DOC_ORDEN");
```

Antes de poner esa restricción, habría que solucionar el problema por bbdd de los documentos duplicados. Podéis ejecutar esta instrucción para ver cualquier duplicado?

```
SELECT DOC_CODFIC, DOC_CODPRO, DOC_ORDEN, COUNT(*)
 FROM RSC_DOCUME
 GROUP BY DOC_CODFIC, DOC_CODPRO, DOC_ORDEN
 HAVING COUNT(*) > 1;

```

**Comment by sgelabert-dgtic** [comment]
A això mateix em referia Sergio, no executaries el PLSQL https://github.com/GovernIB/rolsac/issues/396#issuecomment-301444964 justa abans d'executar la restricció d'integritat ?

**Comment by sgelabert-dgtic** [comment]
Adjunt resultat de la select sol·licitada sobre l'entorn de PROducció
[export.xlsx](https://github.com/GovernIB/rolsac/files/1169206/export.xlsx).

**Comment by slromero-indra** [comment]
Para poder aplicar la restricción de unicidad se debería "arreglar" también la parte de fichas, ya que la tabla de documentos es compartida.

Cuando se ejecutan los updates asociados al reordenamiento de documentos para fichas no se cumple la restricción de unicidad (p.e. imagina que se ejecutan 2 updates para cambiar el orden de 2 documentos, en el primer update saltaría la restricción de unicidad).

Para procedimientos realizamos el reordenamiento en 2 fases, para evitar que se produzcan problemas con la restricción de unicidad.

Lo que parece estar claro es que al igual que pasaba con procedimientos, la reordenación de documentos para fichas no funciona bien (los datos del excel así lo reflejan).

Nuestra propuesta sería:
 1) modificar el reordenamiento de documentos para fichas igual que lo hemos aplicado para procedimientos
 2) arreglar mediante un script los ordenes duplicados para dejar los datos coherentes
 3) aplicar la restricción de unicidad de forma global para procedimientos y fichas

Si no se arregla el reordenamiento de documentos para fichas evidentemente no se puede aplicar la restricción de unicidad.

Ya nos comentas como proceder.

**Comment by sgelabert-dgtic** [comment]
Ok, feis-ho en base a un PLSQL de l'estil https://github.com/GovernIB/rolsac/issues/396#issuecomment-301444964 que revisi i depuri alhora tant l'ordenació de fitxes com la procediments
El PLSQL ha d'imprimir tot els els updates que realitza a BBDD

**Comment by slromero-indra** [comment]
Entonces, modificamos el reordenamiento de documentos para fichas igual que hemos hecho para procedimientos?

**Comment by sgelabert-dgtic** [comment]
Sí. Voltros mateixos em deis que pot ser font de problemes...

**Comment by rsanz-indra** [comment]
Ok. La implementación actual del reordenamiento en fichas no funciona bien tal como muestran los datos en BBDD. 
Este cambio además de corregir el reordenamiento, permitirá establecer una restricción de integridad por BD como medidad de seguridad adicional.

**Comment by slromero-indra** [comment]
Respecto a la generación de una restricción con 3 campos, en un primer momento, lo lógico era pensar en 2 restricciones, una **restricción procedimiento** (DOC_CODPRO y DOC_ORDEN) y una **restricción ficha** (DOC_CODFIC y DOC_ORDEN). 

El problema es que la constraint unique tiene en cuenta los valores nulos. Por ejemplo, cuando se introducen 2 documentos de ficha, el campo DOC_CODFIC se introduce pero el DOC_CODPRO se queda nulo y saltaría la restricción de unicidad.

Por tanto, sólo se puede incluir la restricción de unicidad incluyendo los 3 campos en élla.

Saludos!

**Comment by slromero-indra** [comment]
Ya hemos comiteado todos los cambios. Hay que tener en cuenta que para ejecutar la restricción de unicidad hay que ejecutar antes el script que soluciona los ordenes repetidos ( rolsac_update_data_from_1.5.4_to_1.5.5.sql ; no se puede incluir dentro del script el alter table ). Se ha aprovechado el script anterior para solucionar los problemas tanto con documentos de procedimientos como de ficha.

Por tanto, el orden de ejecución es:
 - Ejecutar rolsac_update_data_from_1.5.4_to_1.5.5.sql.
 - Incluir la restricción:
  ```
alter table rsc_docume add CONSTRAINT "RSC_DOC_ORDEN_UNIQUE" 
  UNIQUE ("DOC_CODFIC", "DOC_CODPRO", "DOC_ORDEN");
```

**Comment by sgelabert-dgtic** [comment]
Després de 'Guardar" un canvi d'ordre sobre el mòdul de Documents Relacionats amb el Procediment, no funciona l'aspa per esborrar documents de la llista
Per altra banda, el selector d'idioma no indica l'idioma seleccionat (hauria de fer-ho tal i com ho fa ara els documents relacionats amb fitxes informatives)
Adjunt captura de pantalla
![ordenaciodocument](https://user-images.githubusercontent.com/17268396/28610594-1d970b24-71e9-11e7-9bd3-459820f9bf4b.jpg)

**Comment by slromero-indra** [comment]
Estamos analizando el código y parece que el problema se encuentra en lista_ordenable.js y modul_documents.js (ninguno de los 2 javascript han sido alguna vez tocados) que son los encargados de aplicar los distintos eventos de reordenación. 

Parece ser que cualquier reordenación de los elementos, borra el evento sobre el aspa para poder borrar un elemento. Este problema pasas tanto en la reordenación de documentos de procedimiento como de fichas.

Respecto al problema de marca el idioma, ese problema se produce en procediments.js (el cambio de nombre si se produce correctamente) y no se produce en fichas (que si selecciona el idioma correctamente).

Seguimos investigando el problema para tenerlo solucionado en el menor tiempo posible.

**Comment by slromero-indra** [comment]
Tras una reordenación, el evento de edición (igual que el de borrado de un documento) también desaparecido. Se ha actualizado el javascript para que también mantenga el evento.

También se ha observado que el módulo de documentos en catalegProcediments tampoco se había actualizado dentro del proyecto.
