### ISSUE TITLE
Bug amb l'ordenació de fitxes Informatives

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#397]
Hem detectat que un problema  de duplicació de fitxes informatives quan se'ls hi canvia l'ordre des de la pàgina d'Unitats Administratives, Mòdul Seccions. 
A banda d'això, els enllaços cap a la fitxa tampoc funcionen

Adjunt captura de pantalla.
![image](https://cloud.githubusercontent.com/assets/17268396/26153037/f5d66960-3b09-11e7-9b8d-f06af77f0e14.png)

**Comment by slromero-indra** [comment]
Buenas, estamos intentando replicar el problema y no hemos sido capaces con la última versión. Podrías pasarnos un patrón para repetir el problema en nuestro entorno de caibter?

También nos sería interesante tener la información almacenada en la base de datos para ver si existe algún problema más y asi replicar el problema.

Seguimos revisando en la última versión subida con los distintos navegadores.

**Comment by sgelabert-dgtic** [comment]
A caibter no teniu la mateixa versió que desplegàrem ahir a PROducció. Hauríeu de col·locar-hi https://github.com/GovernIB/rolsac/commit/8e6d3e0d

**Comment by slromero-indra** [comment]
Buenas, nos ponemos a cambiar la versión de caibter, pero si queréis, podéis intentar replicar el problema en https://proves.caib.es/rolsacback que si está la misma versión. Cuando tengamos la nuestra actualizada aviso.

**Comment by sgelabert-dgtic** [comment]
Ho he estat mirant en local i tampoc aconsegueixo que em dupliqui la informació. 
El que sí que veig és que no me permet posar fitxes en primera posició.

**Comment by slromero-indra** [comment]
Buenas, no hemos sido capaces de replicar el problema de duplicar la información cuando se reordena. Ahora bien, si hemos sido capaces de replicarlo a través de otra utilidad. Parece ser que si se utiliza el buscador de la derecha, no se controla si ya ha sido introducida la ficha (hemos sido capaces de introducirla tantas veces como queramos).

![image](https://cloud.githubusercontent.com/assets/17451407/26200355/f7ba11f4-3bcd-11e7-9813-69304906cae1.png)

Ahora bien, lo que hemos observado es que, si ya están duplicadas e introducidas, cuando se reordena una de las fichas, automáticamente se reordenan juntas las mismas fichas (dando la falsa sensación de duplicar cuando se reordena).

Nos interesaría también saber cuantas fichas hay duplicadas en producción, te paso una sql a ejecutar en producción:

```
select  FUA_CODUNA,
        FUA_CODFIC,
        FUA_CODSEC, count(*)
   from rsc_fichua  
   group by FUA_CODUNA,
        FUA_CODFIC,
        FUA_CODSEC        
    having count(*) > 1    ;
```

Se propone realizar lo siguiente:
  - Desde el formulario de la derecha 'Opcions de cerca' se va a bloquear la opción de insertar una ficha ya introducida. 
  - Desde el método java encargado de reordenar e introducir las fichas, se comprobará si hay alguna ficha duplicada y eliminará la ficha duplicada.
 - Después de limpiar las fichas duplicadas, se debería de añadir una restricción de unicidad.

¿Realizamos los cambios?

**Comment by slromero-indra** [comment]
Tras comentarlo con Salvador se realizará lo siguiente:
  - Salvador revisa los casos existentes duplicados y los arregla eliminando los duplicados. Podrían quedar huecos en el orden.
  - Revisamos a ver si la pantalla se comporta bien si existen huecos y al guardar se reordena correctamente.
 - Definir indice único por sección/ficha/ua
 - En la pantalla de Secciones UA se establece un control para no permitir duplicar una ficha

**Comment by slromero-indra** [comment]
Hemos procedido a borrar fichas dejando huecos en el orden. Entrando de nuevo a la pantalla, se observa que se muestran con un nuevo orden (no deja hueco, todos los órdenes son consecutivos) y al pulsar el botón de guardar, se actualiza el orden en la BBDD quitando los huecos.

**Comment by sgelabert-dgtic** [comment]
Correcte, era el que em pareixia.
Adjunt script per eliminació de duplicats:
```
SET SERVEROUTPUT ON;
DECLARE
  CURSOR c_duplicats IS
  (select  FUA_CODUNA,
        FUA_CODFIC,
        FUA_CODSEC, count(*) NUM_DUP
   from rsc_fichua  
   group by FUA_CODUNA,
        FUA_CODFIC,
        FUA_CODSEC        
    having count(*) > 1);
  N NUMBER := 1;
  duplicat c_duplicats%ROWTYPE;
BEGIN
  OPEN c_duplicats;
  LOOP
    FETCH c_duplicats INTO duplicat;
    EXIT WHEN c_duplicats%NOTFOUND;
    dbms_output.put_line('FUA_CODUNA=' || duplicat.FUA_CODUNA || ' FUA_CODFIC=' || duplicat.FUA_CODFIC || ' FUA_CODSEC=' || duplicat.FUA_CODSEC || ' NUM_DUP=' || duplicat.NUM_DUP);
    N := 1;
    FOR i IN (SELECT * FROM RSC_FICHUA WHERE FUA_CODUNA=duplicat.FUA_CODUNA AND FUA_CODFIC=duplicat.FUA_CODFIC AND FUA_CODSEC=duplicat.FUA_CODSEC ORDER BY FUA_ORDEN DESC) LOOP
        EXIT WHEN N>=TO_NUMBER(duplicat.NUM_DUP);
        DELETE FROM RSC_FICHUA WHERE FUA_CODI=i.FUA_CODI;
        dbms_output.put_line('DELETE FROM RSC_FICHUA WHERE FUA_CODI=' || i.FUA_CODI || ';');
        N := N + 1;
    END LOOP;
   END LOOP;
  CLOSE c_duplicats;
END;
```

**Comment by sgelabert-dgtic** [comment]
Adjunt resultat de la consulta sobre PRO [CAI-1721700-log.txt](https://github.com/GovernIB/rolsac/files/1010912/CAI-1721700-log.txt)

S'observen registres amb fua_codfic a null. Entenc que aquests es poden eliminar directament... Veis algun problema en definir com a not null cada un dels camps seccio/ficha/ua ?

**Comment by slromero-indra** [comment]
Buenas, nos parece correcto que añadir una reesctricción de no nulo a ficha y la eliminación de los datos con fichas a nulo. Cuanto más restrictivos seamos por bbdd, mejor irá la aplicación y evitaremos más la posibilidad que algún dato/error se nos pase.

**Comment by slromero-indra** [comment]
Añadido como script para incluir en la subida. El comando para incluir la restricción UNIQUE a la tabla.

`ALTER TABLE rsc_fichua ADD CONSTRAINT FUA_UNIQUE UNIQUE (FUA_CODUNA, FUA_CODSEC, FUA_CODFIC);`

**Comment by slromero-indra** [comment]
Avisamos cuando este totalmente completo, hemos visto algún comportamiento extraño con los ordenes.

**Comment by sgelabert-dgtic** [comment]
Una cosa més, a producció tenim seccions amb moltes fitxes (400 o 500 fitxes publiques en una secció/ua), per facilitar la tasca a l'usuari el nou missatge  que indica "La fitxa ja es troba introduïda"  hauria d'indicar l'ordre, és a dir, "**La fitxa ja es troba introduïda a la posició xxx**"

**Comment by sgelabert-dgtic** [comment]
Un altre bug, si s'empra l'aspa d'esborrat s'elimina per complet la fitxa de la taula RSC_FICHUA, deixant la fitxa com a orfa. S'ha de corregir perquè s'elimini només de la secció-ua actual i mantenir el control que verifica que és la fitxa queda associada com a mínim a una secció-ua (això funciona bé).

**Comment by slromero-indra** [comment]
Buenas, surgió un bug bastante extraño provocado cuando se añadía la restricción de unicidad debido a un mal mapeo. 

El error que se producía era que el método encargado de insertar la relación entre UAs, Secciones y Fichas primero borra todas las fichas y luego las vuelve a insertar. En FichaResumen existe una colección que se relaciona con FichaUA que provocaba un comportamiento extraño en hibernate. El comportamiento era que cuando se borraba una FichaUA, en algunos casos, generaba un update con el valor de fichas a nulo (ahora con la restricción de unicidad, provocaba un error no controlado). Esto se producía debido a que no se indicaba que tabla era el 'propietario' de la relación. 

Hemos podido solucionar el problema indicando el propietario de la relación (mediante el inverse=true) pero hay que realizar una serie de pruebas de generación de fichas para que el comportamiento siga siendo correcto. Debido a la complejidad de la localización del error, tanto este como el inicial, al final del día (tras las pruebas y los últimos cambios pedidos) estaremos rondando las 25 horas.

**Comment by sgelabert-dgtic** [comment]
Ok, entenc que la tasca està suficientment encarrilada per enllestir-la. Continua-la sempre i quan no sorgeixin nous inconvenients que superin les 30h. En aquest cas, enviau-nos document amb el resum de problemes detectats i estimació del que falta per finalitzar la tasca

**Comment by slromero-indra** [comment]
Buenas, respecto al comentario del bug de tener fichas huérfanas, no hemos sido capaz de replicarlo. Cuando se borra una relación desde la pantalla de UAs, se borra sólo las fichas con la relación UA y Sección. 

La única manera que hemos sido capaces de replicarlo ha sido cuando están las fichas duplicadas, que no controla bien cuando a la ficha le queda una relación. Nos podéis decir una manera de replicarlo?

**Comment by sgelabert-dgtic** [comment]
M'ha passat una vegada més però no aconseguesc trobar el patró... No hi perdeu més temps, si ho replic us dic coses

**Comment by slromero-indra** [comment]
Buenas, ya hemos actualizado completamente el código para el tema de la unicidad y que no se permitan meter fichas duplicadas (según UA y Sección) y muestre un mensaje de error con el orden de la ficha. Sin contar el problema que no somos capaces de replicar, el resto de errores ya lo hemos comiteado.

**Comment by sgelabert-dgtic** [comment]
Hi ha un bug en el mòdul d'opcions de cerca que fa en determinats casos els `inputs` de cerca i codi es deshabilitin. Adjunt captura de pantalla:
![image](https://cloud.githubusercontent.com/assets/17268396/26347333/888d3a4c-3fa9-11e7-8954-ffc2adddcc7d.png)

**Comment by slromero-indra** [comment]
Buenas, respecto al problema principal, ya se realizaron todos los cambios para solucionarlo y hemos llegado a 30. El problema es el bug del módulo buscador que no coincide con la casuística del problema inicial, como continuamos con la incidencia? Seguimos revisando el problema del buscador?

**Comment by sgelabert-dgtic** [comment]
Tanc aquesta incidència passem el nou bug localitzat al tiquet #398
