### ISSUE TITLE
Bug cercador pantalla Unitats Administratives - Mòdul Seccions

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#398]
Hi ha un bug en el mòdul d'opcions de cerca que fa que en determinats casos els `inputs` de cerca i codi es deshabilitin. Adjunt captura de pantalla:
![image](https://cloud.githubusercontent.com/assets/17268396/26347333/888d3a4c-3fa9-11e7-8954-ffc2adddcc7d.png)

**Comment by slromero-indra** [comment]
También hemos observado que repetir varias veces la búsqueda consigue que siempre se visualice 'buscando items' (la búsqueda parece que se hace correctamente pero comete el error de no ocultar y mostrar correctamente los divs).

**Comment by sgelabert-dgtic** [comment]
Em segueix passant el mateix problema. El camp queda inhabilitat inclús després d'esborrar el filtre de cerca
![cercador](https://user-images.githubusercontent.com/17268396/27168748-57b3914a-51a7-11e7-8c4f-2b6ab3b3505b.jpg)

**Comment by slromero-indra** [comment]
Hemos actualizado el comportamiento para, sin importar el resultado (devuelve datos o ninguno o un error), siempre habilite los campos.

**Comment by sgelabert-dgtic** [comment]
- Si s'afegeix una fitxa a la secció i just després s'intenta eliminar amb l'aspa (sense guardar) apareix el missatge "No se puede borrar la ficha porque quedaría sin asociar a ninguna sección."
- Cal netejar els camps Text i Codi del cercador quan es surt i torna entrar a la pantalla.

**Comment by slromero-indra** [comment]
Se ha actualizado para que cada vez que se entre a la pantalla, limpie los campos de texto en la búsqueda.

Respecto al problema de borrar sin almacenar. El problema se debía a que, para eliminar una ficha, **siempre** se pregunta al servidor y, si la ficha está en 1 o 0 fichas en la tabla de fichasUA, entonces lanza un error. 

Obviamente este comportamiento no tiene en cuenta si se añade un ficha y no se ha pulsado el botón de guardar. Para evitar este problema se han realizado los siguientes cambios:
 - Cada vez que se añade una ficha, se le añade un atributo para indicar que esa ficha no ha sido aún almacenada.
 - Cuando se borra, se mira si dicha ficha tiene la nueva propiedad. Si no la tiene, se continua con el mismo funcionamiento, en cambio si la tiene, se saltará la comprobación de preguntar al servidor.
