### ISSUE TITLE
Millora pantalla d'enviament pendents a SIA

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#399]
Es sol·licita que l'apartat d'enviament de pendents a SIA apareguin només aquells procediments que compleixin amb els critèris de visibilitat i tinguin les dades necessaries per l'enviament a SIA. La pantalla mostrarà també l'estat de l'enviament (pendent o la causa de l'error després de l'enviament)

Endemés es sol·licita que des de la pantalla d'Administració SIA, es pugui extreure el log de procediments visibles, però no enviables a SIA, evitant així el reenviament d'aquests procediments mentre no canviin les condicions.

**Comment by rsanz-indra** [comment]
Se realizarán los siguientes cambios:

1) Al modificar un procedimiento se revisará si se debe enviar a SIA algún cambio (alta/modificación/baja):
- Se borrará en tabla de SIA Pendientes todos los registros de ese procedimiento (de esta forma sólo habrá información del último intento para un procedimiento)
- Si no se debe enviar ningún cambio, no se hace nada más
- Si se debe enviar un cambio, se verifica si se disponen de todos los datos para enviar a SIA:
- si falta algún dato, se guarda en SIA Pendiente como NO POSIBLE EJECUTAR y en el MENSAJE DE ERROR lo que falta
- si se tienen todos los datos, se guarda en SIA Pendiente como PENDIENTE DE EJECUTAR

2) Al ejecutar el proceso de integración con SIA, recuperan los PENDIENTE DE EJECUTAR y se intentan subir a SIA:
- en caso de error se reintentarán los días configurados. Si se pasa del límite de días, se cambiará estado a NO POSIBLE EJECUTAR
- en caso correcto se borrará de la tabla de SIA Pendientes

3) En la pantalla de Indexación de SIA dispondremos de 3 pestañas:
- Enviar todo: para realizar volcado completo
- Enviar pendientes: mostrará los envíos PENDIENTE DE EJECUTAR (bien porque no se hayan ejecutado todavía o porque se haya producido un error)
- Advertencias pendientes: mostrará los registros de SIA Pendiente como NO POSIBLE EJECUTAR

Además modificar:
 - formato fechas a  dd/mm/yyyy hh:mm:ss
 - los literales: "Data envio" a "Data d'enviament" y "Missatge de error" a "Missatge d'error"

**Comment by sgelabert-dgtic** [comment]
He provat de modificar un procediment (en principi enviable a SIA) i no m'apareix a la llista de pendents d'enviament. Tampoc apareix al llistat d'avertències.
Ho he provat a CAIBTER amb el procediment 2512129 i em passa el mateix.

Per altra banda, la data d'alta de la pestanyà de pendents d'enviament segueix amb format incorrrecte mm/dd/yyyy (comprovar també la data d'enviament)

**Comment by slromero-indra** [comment]
Buenas, cada vez que se modifica un procedimiento, se sigue la siguiente pauta:

1. Borrar todas las sia pendientes.
2. Comprobar si es 'indexable SIA'
   2.1 Si no es indexable SIA, no seguimos.
4. Comprobar si están todos los datos completos.
     3.1 Si no están completos, se inserta en pendientes con datos pendientes (aparecerá en la nueva pestaña y con el mensaje del campo que falta).
     3.2. Si está completo, se inserta en pendiente (se verá en la segunda pestaña, se podrá ejecutar manual

mente o bien con la tarea automática).

Si no sale el procedimiento, es porque se debe quedar en el punto 2.1 

Un procedimiento es NO indexable si no cumple alguna de las siguientes condiciones:
  1.- El procedimiento es visible.
  2.- Existe una SIA UA (el nuevo formulario creado) a partir de organ resolutori (la asociada o algún padre)
  3.-Existe una  UA con código DIR3 a partir de organ resolutori (la asociada o algún padre)

¿Me puedes comprobar si se cumplen las 3 condiciones? Puede que ser que no exista SIA UA (el nuevo formulario creado) asociado a dicha UA? 

Saludos!

**Comment by sgelabert-dgtic** [comment]
Correcte Sergio, faltava crear un "SIA UA". 
Me pareix lo suficientment important com perquè aparegui un missatge en la nova pestanya "Advertències pendents". Podríem indicar-ho "No existeix cap entitat arrel definida per aquest procediment" ?

**Comment by slromero-indra** [comment]
Ok, pues con el nuevo cambio, un procedimiento es NO indexable si no cumple alguna de las siguientes 3 condiciones (se nos había olvidado comentar que la UA también tiene que ser visible desde òrgan resolutori hasta la raíz):
1.- El procedimiento es visible.
2.-Existe una UA con código DIR3 a partir de organ resolutori (la asociada o algún padre)
3.-La UA es visible de organ resolutori (la asociada o algún padre)

La condición de la SiaUA se irá a una función que comprueba si un procedimiento cumple todos los datos. Si los cumple, se va a la tabla de pendientes para ejecutar, sino se va directamente a la pestaña de 'Advertències pendents' con el mensaje de error 'No existeix cap entitat arrel definida per aquest procediment'.

Los datos que se deben cumplir actualizados son:

1. Tiene materias
2. Tiene normativas y al menos una tiene tipo SIA.
3. Tiene nombre 
4. Tiene resumen
5. Tiene SiaUA

**Comment by sgelabert-dgtic** [comment]
Hi ha una cosa que no me queda clara, si els camps "materia", "normativa", "nom" i "resum" són obligatoris, i no deixam actualitzar el procediment, quan és que passem a "Advertències pendents" ?

L'única opció que veig és introduir-los quan es fa un bolcat complet, cosa que he provat i ara no fa.

**Comment by slromero-indra** [comment]
Buenas, las condiciones materia, normativa, nom y resum son obligatorias en el servicio de SIA por lo que antes de provocar un error no controlado, lo mandamos a la pestaña de "Advertències pendents".

También se pueden introducir en dicha pestaña si se actualiza una normativa o UA asociada a un procedimiento.

**Comment by sgelabert-dgtic** [comment]
No sé si m'explic ... Corregim si m'equivoc però crec que estau passant a "Advertències pendents" quan s'actualitza el procediment, no ? Donc si a un procediment li falta algun d'aquests camps, els procediment no s'actualitza i , per tant, no passarà mai a "Advertències pendents". 

Te pos un exmple:
-Agaf un procediment (1475728 entorn de PRE) no bolcat a SIA però donat d'alta abans d'establir els controls d'obligatorietat i que li falta la normativa
- Modific les seves dades però deix la norma sense introduir
- La pantalla m'avisa que li falta la normativa i no s'actualitza.
- Si consult a "Advertències pendents" el procediment no hi és (no s'ha actualitzat)
- Si torn al procediment i li afegeix-ho una norma, el procediment complirà amb els requisits, s'actualitzarà i s'enviarà a SIA
Per tant, a "Advertències pendents" no hi haurà res mai.... (llevat del control de les arrels i dels tipus de normativa).
L'única opció és introduir aquest procediments a "Advertències pendents" quan es fa un bolcat complet.

Si no ho veis clar o vaig errat, en parlem

**Comment by sgelabert-dgtic** [comment]
Adjunt log del servidor d'aplicacions de producció de dia 15/06/2016 
http://tn.caib.es/ToECQoXA

**Comment by slromero-indra** [comment]
Buenas, para introducir procedimientos en esa pestaña es posible de varias maneras. 
- Actualización de una normativa, se introduce todos los procedimientos relacionados en las tablas de pendientes de ejecutar o advertencias pendientes.
- Cuando se actualiza las materias relacionadas o normativa del procedimiento, se llama al método de grabarProcedimiento sin necesidad de pulsar el botón de guardar (y sin necesidad de tener todos los campos introducidos). 

Igualmente, como te comentaba, esos campos son obligatorios por parte de SIA, y es una restricción para evitar cualquier problema no controlado. Si se desea y se comenta anteriormente, se podrían añadir los procedimientos que no cumplan todos los datos tras realizar un volcado completo.

Además, ahora que la entidad raíz es una condición para cumplir los datos, podrían introducirse procedimientos en esa pestaña que no cumplan esa condición.

**Comment by slromero-indra** [comment]
Respecto a lo comentado, se van a realizar las siguientes mejoras:

En el volcado completo:
- Cuando se realice un volcado completo, se borraran todos los datos en la tabla de pendientes.
- Se comprobará que no esté ejecutándose otra tarea y se parará avisando del problema (este comportamiento se añadirá también a la ejecución de pendientes).
- Si algún procedimiento tiene las condiciones para entrar en sia pero le falta algún dato, se introducirá en la pestaña de advertencias pendientes.

Cuando se modifique un procedimiento y se pase a pendientes, se quitará de advertencias pendientes en caso que esté.

**Comment by sgelabert-dgtic** [comment]
Una cosa més, he canviat les dades d'un tràmit d'inici i guardat el canvis del tràmit sense guardar el procediment. El procediment no queda dins pendents SIA, quan entenc que hi hauria d'estar perquè s'actualitzin les seves dades

**Comment by sgelabert-dgtic** [comment]
Es sol·licita separar els conceptes de la utilitat de bolcat complet de procediments amb els següents:
S'han intentat enviar XXX procedimients d'un total de XXX procedimients disponibles:
- XXX s'han enviat correctament
- XXX han donat errors al enviar
- XXX no són visibles i no s'han d'enviar 
- XXX s'haurien d'enviar però falten dades
Cal comprovar que els elements de la categoria "XXX s'haurien d'enviar però falten dades" haurien de coincidir amb els de la pestanya "Advertències pendents"

**Comment by slromero-indra** [comment]
Comiteado y actualizado de los textos.

**Comment by sgelabert-dgtic** [comment]
Adjunt resultats del bolcat complet de procediments dins SIA
![bocat-20170714](https://user-images.githubusercontent.com/17268396/28201228-6774c2f4-6870-11e7-8b38-45120ab6ed6d.jpg)

Errades:
   ---- Procediment: 2678513 
   ---- S‘ha enviat a SIA incorrectament. 
   ---- Missatge:1163:Ya existe una tramition con ese codigo de origen asociado a ese departamento 
   ---- Operaci?:A. 

   ---- Procediment: 2740340 
   ---- S‘ha enviat a SIA incorrectament. 
   ---- Missatge:1163:Ya existe una tramition con ese codigo de origen asociado a ese departamento 
   ---- Operaci?:M. 

Es tracta de procediments de l'entorn de PREproducció, per tant, no em preocupa que acabin dins SIA sinó que l'error no es reprodueixi sobre l'etorn de PROducció. 

Per altra banda a PROducció segueixen havent-hi procediments amb codiSia i sense estat https://github.com/GovernIB/rolsac/issues/377#issuecomment-287696316

[export_SIA_senseEstat.xlsx](https://github.com/GovernIB/rolsac/files/1147586/export_SIA_senseEstat.xlsx)

**Comment by rsanz-indra** [comment]
Respecto a los registros que existen con codiSIA pero sin estado/fecha hemos verificado lo siguiente:
 - Desde el proceso de integración siempre se establecen los 3 valores (código, estado y fecha). Se realiza en un único punto centralizado, tomando el valor de la fecha como un new Date(), por lo que si se updatea desde este punto nunca podría tener valor nulo la fecha.
- El proceso de guardado desde el Back gestiona el guardado de procedimiento creando un objeto nuevo y cargando de nuevo los valores, tomando los valores de la request y del objeto almacenado actualmente en BD. Es decir, no es un update del objeto recuperado de BBDD. No obstante se ha verificado que se alimentan los campos fecha y estado del objeto actualmente almacenado.
- Por tanto es como si una vez "integrado" con SIA, hay algún momento donde pierde esos datos (estado y fecha). En caso de perder estos datos, hemos verificado que el proceso de integración intenta hacer un alta (provocando el error "Ya existe una tramition con ese codigo de origen asociado a ese departamento").

Proponemos los siguientes cambios:
- al guardar un procedimiento establezcamos una verificación de que si un procedimiento tiene código SIA pero no tiene estado o fecha, genere un error y no permita guardar
- en el proceso de integración si se detecta que existe código SIA pero no estado ni fecha, se genere un error de validación

Respecto al error: 

---- Procediment: 2740340
---- S‘ha enviat a SIA incorrectament.
---- Missatge:1163:Ya existe una tramition con ese codigo de origen asociado a ese departamento
---- Operaci?:M.

Hemos verificado en SIA que se han creado 2 registros consecutivos para el mismo procedimiento. Habría que hablar con el soporte SIA como ha sido posible esto.

Respecto al error:

---- Procediment: 2678513
---- S‘ha enviat a SIA incorrectament.
---- Missatge:1163:Ya existe una tramition con ese codigo de origen asociado a ese departamento
---- Operaci?:A.

Es debido al error comentado anteriormente cuando se pierden los datos de estado y fecha (ese procedimiento tiene código SIA pero no tiene fecha ni estado)

Para arreglar los datos de PRO pasaremos un update para actualizar la fecha y el estado.
Habría que hacer una consulta en PRE para ver si hay otros registros con ese problema.

**Comment by sgelabert-dgtic** [comment]
El plantajament "al guardar un procedimiento establezcamos una verificación de que si un procedimiento tiene código SIA pero no tiene estado o fecha, genere un error y no permita guardar" no aporta solució al problema i l'usuari no podria modificar les dades d'aquest procediment. Realment ho veis necessari? No ens bastaria amb el control des del procés d'integració i anotar-ho a pendents ?

**Comment by rsanz-indra** [comment]
El tema de la verificación no es una solución al problema, servirá para poder detectar como y donde se está produciendo el error (dejar en blanco fecha y estado) y ver como resolverlo.
Otra opción sería que si no tiene fecha ni estado, tomarlo como una modificación (pero no estaríamos resolviendo el problema de base que existe).

**Comment by sgelabert-dgtic** [comment]
No m'acaba d'agradar que es bloquegi la publicació/actualització de procediments en teoria vàlids a la nostra Seu Electrònica per un problema colateral d'integració amb SIA.

En qualsevol cas, si no hi ha més remei bloquejau-ho, però revisau abans els procediments actuals sense (data i estat) de l'entorn de PRE  a veure si podem determinar el problema. Adjunt exportació [export_SIA_PRE.xlsx](https://github.com/GovernIB/rolsac/files/1151803/export_SIA_PRE.xlsx)

**Comment by sgelabert-dgtic** [comment]
Adjunt exportació amb un procediment de PROducció sense codiSIA, però amb estatSIA i dataActSIA
[export_SIA_senseCodi_20170718.xlsx](https://github.com/GovernIB/rolsac/files/1155383/export_SIA_senseCodi_20170718.xlsx)

**Comment by rsanz-indra** [comment]
Hemos implantado el check de validación y vamos a empezar a realizar pruebas en nuestro entorno para ver dónde se están borrando los datos que mete el proceso.
Os vamos comentando.

**Comment by slromero-indra** [comment]
La SQL a ejecutar en PRODUCCIÓN:
` update rsc_proced set PRO_ESTSIA = 'A', PRO_FECSIA = TO_DATE('10/07/2017','dd/mm/yyyy'), PRO_CODSIA = 225052  where PRO_CODI in (2992829);`

La SQL a ejecutar en preproducción:
`update rsc_proced set PRO_ESTSIA = 'A', PRO_FECSIA = TO_DATE('26/09/2016','dd/mm/yyyy') where PRO_CODI in (1298438, 2677904, 2683545, 2692271, 2680288, 2678513, 1757148, 1760261);`

Hay un documento adjuntado el 14 de julio a las 9:02 (export_SIA_senseEstat.xlsx) y parece que se entiende que es producción según el comentario, es en producción o preproducción? La siguiente SQL sería a ejecutar según el entorno utilizado para generar el xlsx:
`update rsc_proced set PRO_ESTSIA = 'A', PRO_FECSIA = SYSDATE  where PRO_CODI in (1468506,1648514,2377957);`

**Comment by sgelabert-dgtic** [comment]
Enviem descàrrega de la taula de RSC_PROCED per correu electrònic

**Comment by slromero-indra** [comment]
Hemos preparado un update para dejar coherentes los datos de Rolsac con los de SIA en Producción con casos que hemos detectado: 
[update-PRO.txt](https://github.com/GovernIB/rolsac/files/1159719/update-PRO.txt)

También sería conveniente proteger por BBDD la unicidad del código SIA en la tabla de procedimientos y los procedimientos a revisar en la tabla de sia pendientes: 
[indices-PRO.txt](https://github.com/GovernIB/rolsac/files/1159746/indices-PRO.txt)  (antes hay que ejecutar el update).

Mañana comitearemos los cambios para meter el check de validación de la actualización de los datos de SIA y sería conveniente subirlo cuanto antes a Producción, para ver si podemos detectar donde esta la fuente del error. Tenemos sospechas de que podría estar relacionado con la issue 404 y el cacheo de JS. Sería interesante proteger la aplicación para evitar estos cacheos (p.e. pasando el número de versión de la aplicación como parámetro, de esta forma forzaría la recuperación ante el despliegue de una nueva versión).

**Comment by slromero-indra** [comment]
Hemos realizado una batería de pruebas sobre modificaciones de procedimientos y no hemos podido replicar ningún caso. Hemos actualizado catalegProcediments para que incluya el número de la revisión del git (la revisión se observa arriba en la cabecera) al cargar el procediment.js para evitar cacheo del javascript.

**Comment by rsanz-indra** [comment]
Pasamos nuevo fichero de update para ejecutar en PRO: 
[update-PRO2.txt](https://github.com/GovernIB/rolsac/files/1162757/update-PRO2.txt)

Realmente son casos que ya existían ayer y que se nos pasó incluir en el fichero de update de ayer.

Una vez ejecutado el update habría que habilitar el índice único:
`alter table RSC_PROCED add CONSTRAINT "RSC_PRO_CODSIA_UNIQUE" UNIQUE ("PRO_CODSIA");`

**Comment by sgelabert-dgtic** [comment]
Fet a producció

**Comment by slromero-indra** [comment]
El martes, una vez se pase a producción la versión 1.5.5, habría que realizar un volcado completo en SIA y enviarnos una exportación de la tabla de procedimientos y así verificaremos que está todo correcto.

**Comment by sgelabert-dgtic** [comment]
Amb la darrera versió commitada, l'enviament de pendents a SIA dóna la següent errada sobre l'entorn de PREproducció:
`Unexpected Error:; nested exception is: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory`
Adjunt captura de pantalla
![enviamentpendentssia](https://user-images.githubusercontent.com/17268396/28610333-43dc0bc8-71e8-11e7-87cc-0f28639f4b7c.jpg)

**Comment by sgelabert-dgtic** [comment]
L'error també és reprodueix amb la tasca de "Bolcar complet procediments dins SIA"

**Comment by slromero-indra** [comment]
¿Nos podéis pasar la parte del log para ver donde se produce el error?  Supongo que se está desplegando en jboss3, ¿se ha generado el ear con el valor jboss.version=3.2 en el fichero default.properties ?

**Comment by sgelabert-dgtic** [comment]
Adjunt log servidor d'aplicacions de PRE Jboss 3.2.8 [server25-07-2017-PRE.log.txt](https://github.com/GovernIB/rolsac/files/1175932/server25-07-2017-PRE.log.txt)

Entenc que sí estava a jboss-version=3.2... Hi ha alguna manera de comprovar-ho mitjançant l'ear ?

**Comment by slromero-indra** [comment]
Buenas, he realizado las pruebas y parece que se ha desplegado en jboss3 un ear con la propiedad jboss-version=5.0 en el default.properties.

Se puede saber si el ear para rolsac es para jboss3 o jboss5 si se busca el jar slf4j-log4j.jar.

En jboss5 no se verá el jar:
![image](https://user-images.githubusercontent.com/17451407/28616101-b5a899ac-71fb-11e7-82d9-2fef28b11ce5.png)

En jboss3 sí se verá el jar (slf4j-log4j12-1.6.4.jar):
![image](https://user-images.githubusercontent.com/17451407/28616115-c35bd87a-71fb-11e7-9b92-73ca239dcc3d.png)

Habría que volver a generarlo con el valor jboss-version=3.2 en default.properties.

Saludos!

**Comment by sgelabert-dgtic** [comment]
OK, reempaquet i envii a PREproducció

**Comment by sgelabert-dgtic** [comment]
Adjunt resultats del bolcat complet a SIA
![bolcatsia-20170727](https://user-images.githubusercontent.com/17268396/28662978-57c18bc0-72bc-11e7-8073-b15b27103e6b.jpg)
Caldria comprovar els procediment que han donat error:
   ---- Procediment: 535864 
   ---- S‘ha enviat a SIA incorrectament. 
   ---- Missatge:1163:Ya existe una tramition con ese codigo de origen asociado a ese departamento 
   ---- Operaci?:A. 
   
   ---- Procediment: 2526252 
   ---- S‘ha enviat a SIA incorrectament. 
   ---- Missatge:0019:El c?digo de organismo corresponde a un organismo de jerarqu?a Departamento. 
   ---- Operaci?:AC. 
   
   ---- Procediment: 2799118 
   ---- S‘ha enviat a SIA incorrectament. 
   ---- Missatge:1163:Ya existe una tramition con ese codigo de origen asociado a ese departamento 
   ---- Operaci?:A.

**Comment by sgelabert-dgtic** [comment]
Adjunt descàrrega de dades de la taula RSC_PROCED dels procediments problemàtics:
[RSC_PROCED_ERRADES_SIA.xlsx](https://github.com/GovernIB/rolsac/files/1179441/RSC_PROCED_ERRADES_SIA.xlsx)

**Comment by slromero-indra** [comment]
## Procedimiento 2526252
Este procedimiento esta asignado a nivel raíz (Govern, codua = 1). SIA no permite procedimientos asignados a nivel raíz. Deberán cambiar en Rolsac la UA a una descendiente del Govern para que se pueda enviar a SIA.

> ---- Procediment: 2526252
> ---- S‘ha enviat a SIA incorrectament.
> ---- Missatge:0019:El c?digo de organismo corresponde a un organismo de jerarqu?a Departamento.
> ---- Operaci?:AC.


## Procedimiento 2799118
Hay que ejecutar la siguiente SQL en producción:
`update rsc_proced set pro_codsia = 208336, pro_estsia = 'A', pro_fecsia = to_date('27/07/2017','DD/MM/RRRR') where pro_codi = 2799118 ;`

## Procedimiento 535864
Para este proc no existe en BBDD info de SIA y en SIA no existe ningún procedimiento con ese código origen (ni activo ni de baja). Vamos a contactar con ISA para preguntarles información por este caso.

**Comment by sgelabert-dgtic** [comment]
Tenim un problema de rendiment amb la càrrega de dades de la pantalla d'integració amb SIA
La petició https://apps.caib.es/rolsacback/sia/llistatSIAJob.do descarrega 1.2MB i tarda uns 10 minuts en carregar la resposta.
Adjunt captura de pantalla
![rendimentintegraciosia](https://user-images.githubusercontent.com/17268396/28764161-dd61b778-75c3-11e7-8ec0-8e4302d6500d.jpg)

**Comment by slromero-indra** [comment]
Actualizaremos el método de llistatSiaJob para que no cargue los BLOBs y que, al pulsar el botón 'Mes info' pida los datos a base de datos. Lo realizaremos en cuanto podamos terminar las issues abiertas para la subida de WEBCAIB.

**Comment by sgelabert-dgtic** [comment]
S'envia via correu electrònic logs de la petició AXIS, el log del servidor d'aplicacions i exportació del procediment 535864 per la seva depuració

**Comment by sgelabert-dgtic** [comment]
Efectivament el procediment 535864 s'ha bolcat a SIA, però en el log del servidor d'aplicacions apareixen les següents errades:
- Traça en el moment de desar el procediment. [ErradaMarcarProcedimentPendent.txt](https://github.com/GovernIB/rolsac/files/1196485/ErradaMarcarProcedimentPendent.txt)

```
	org.ibit.rol.sac.persistence.delegate.SiaPendienteProcesoDelegateImpl.obtenerSiaUA(SiaPendienteProcesoDelegateImpl.java:222)
	at org.ibit.rol.sac.persistence.delegate.SiaPendienteProcesoDelegateImpl$$EnhancerByCGLIB$$ca0337e3.CGLIB$obtenerSiaUA$0$11(<generated>)
	at org.ibit.rol.sac.persistence.delegate.SiaPendienteProcesoDelegateImpl$$EnhancerByCGLIB$$ca0337e3$$FastClassByCGLIB$$f9145538.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:201)
	at org.ibit.rol.sac.persistence.util.DelegateLogInterceptor.intercept(DelegateLogInterceptor.java:91)
	at org.ibit.rol.sac.persistence.delegate.SiaPendienteProcesoDelegateImpl$$EnhancerByCGLIB$$ca0337e3.obtenerSiaUA(<generated>)
	at org.ibit.rol.sac.persistence.delegate.SiaPendienteProcesoDelegate.obtenerSiaUA(SiaPendienteProcesoDelegate.java:98)
	at org.ibit.rol.sac.persistence.util.SiaUtils.obtenerSiaUA(SiaUtils.java:485)
	at org.ibit.rol.sac.persistence.util.SiaUtils.cumpleDatos(SiaUtils.java:369)
	at org.ibit.rol.sac.persistence.ejb.SiaPendienteProcesoFacadeEJB.generarSiaPendiente(SiaPendienteProcesoFacadeEJB.java:460)
```
- Traça en el moment d'enviar manualment el procediment a SIA. [ErradaEnviamentSIAPendents.txt](https://github.com/GovernIB/rolsac/files/1196490/ErradaEnviamentSIAPendents.txt)
```
at org.ibit.rol.sac.persistence.delegate.SiaPendienteProcesoDelegateImpl$$EnhancerByCGLIB$$ca0337e3.obtenerSiaUA(<generated>)
	at org.ibit.rol.sac.persistence.delegate.SiaPendienteProcesoDelegate.obtenerSiaUA(SiaPendienteProcesoDelegate.java:98)
	at org.ibit.rol.sac.persistence.util.SiaUtils.obtenerSiaUA(SiaUtils.java:479)
	at org.ibit.rol.sac.persistence.util.SiaUtils.cumpleDatos(SiaUtils.java:369)
	at org.ibit.rol.sac.persistence.ejb.SiaPendienteFacadeEJB.enviarPendienteTipoProcedimiento(SiaPendienteFacadeEJB.java:511)
	at org.ibit.rol.sac.persistence.ejb.SiaPendienteFacadeEJB.enviarPendientes(SiaPendienteFacadeEJB.java:429)
```

**Comment by slromero-indra** [comment]
El mensaje que se muestra en los logs se debía a que no se cerraba correctamente la sesión cuando se llamaba al método obtenerSiaUA. Hemos revisado la clase para evitar cualquier problema no detectado y cerrando la sesión donde sea necesario.
