### ISSUE TITLE
Afegir control obligatorietat sobre camps de la pantalla de procediments/tramits

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/rolsac#4]
Numero: 576
Creació: 2016-02-12 09:08:41.960
Afegir control obligatorietat sobre els seguents camps de la pantalla de gestió de procediments:
* Objecte
* Destinataris
* Forma d'iniciació
* Termini màxim per resoldre i notificar (veure ticket [8](https://github.com/GovernIB/rolsac/issues/8))
* Fi de la via administrativa
* Data publicació, de l'apartat Publicació
* Responsable del procediment, de l'apartat Informadors (veure ticket [6](https://github.com/GovernIB/rolsac/issues/6))
* Normativa relacionada

Afegir control obligatorietat sobre els modul lateral "Models de sol·licitud" de la pantalla de gestió de tràmits, en el cas que sigui un tràmit d'inici (Moment=Inicialització")

**Comment by slromero-indra** [comment]
Falta por terminar el ticket 8 para dar la tarea por terminada.

**Comment by episano-dgtic** [comment]
He hecho una previa comprobación de lo que habéis hecho. Comentaros un par de cosas:
1) Respecto al fin de la vía administrativa.  Tiene poco sentido obligar a marcar un check box en el que únicamente diferenciáis dos estados y obligáis a que esté marcado. Se debe poder diferenciar 3 estados (no indicado, marcado y desmarcado) y obligar a que esté marcado.

2)  No estaba especificado petición: Otro módulo más al que hay que añadir la obligatoriedad es a las materias relacionadas. (como mínimo deben indicar una, similar caso públicos objetivos) 

3) Respecto a la obligatoriedad de las normativas, tal y como lo habéis programado da más problemas que beneficios. 1er no está marcado como obligado, segundo en la creación no se obliga, y en las modificaciones no se guarda las referencias. 
Recomiendo obligar a las normativas cuando se desee publicar el procedimiento, similar al control del trámite de inicio.

**Comment by episano-dgtic** [comment]
1) En la creación del procedimiento el hecho de que aparezca el módulo de materias y normativas da más problemas que soluciones. Testearlo please.. Tratando de guardar normativa sin el código y faltando campos da errores, incluso con todos los campos
Salen mensajitos "Ha ocurrido un error. Pruebe de nuevo o contacte con el administrador de sistemas"
Y patra más inri, luego no aparecen las normativas y materias indicadas. 

2) Un caso no habéis contemplado. 
Procedimientos con todos los campos obligatorios y publicado. Al que se eliminan las normativas  ó materias asociadas y permite guardar con estado público sin normativas y sin materias.
No habéis tenido en cuenta que una vez publicado el procedimiento se pueden eliminar las normativas asociadas y se debe controlar que no se permita continuar teniendo el procedimiento público.

**Comment by episano-dgtic** [comment]
Algo que no me había dado cuenta que no habéis hecho:
Afegir control obligatorietat sobre els modul lateral "Models de sol·licitud" de la pantalla de gestió de tràmits, en el cas que sigui un tràmit d'inici (Moment=Inicialització")
