### ISSUE TITLE
Bug presentació pantalla de procediments administratius

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#400]
Hi ha una errada de presentació quan es retorna a la pantalla de procediments just després d'haver desat un model en la pantalla de tràmits. Pareix un error en l'ocultació de capes
Adjunt captures de pantalla
![bugcapestramit](https://cloud.githubusercontent.com/assets/17268396/26818277/522a1244-4a9a-11e7-80ab-306801cde546.jpg)

![bugcapestramit2](https://cloud.githubusercontent.com/assets/17268396/26818282/57a6c3ca-4a9a-11e7-940d-0710fdbb7d88.jpg)

**Comment by sgelabert-dgtic** [comment]
Ha canviat el comportament de la pantalla de tràmits. Després de desar el tràmit t'apareixien els mòduls laterals de "Models" i "Documents relacionats amb el tràmit", ara no.
Per altra banda, el control sobre la unicitat del tràmit d'inici s'hauria de canviar i comprovar en el moment de desar el tràmit, no en el moment de desar el procediment.

**Comment by slromero-indra** [comment]
Buenas,
Respecto al primer punto, lo revisamos. Compararemos el funcionamiento con el tag 1.5.2 para tratar de averiguar el origen del problema. 
Respecto al segundo punto, hemos realizado una prueba inicial y parece que al crear el trámite o al guardarlo, si es de inicio, no te permite darlo de alta/guardarlo si ya existe uno. ¿Puede ser que se trate de datos insertados con anterioridad? ¿puedes facilitarnos como reproducirlo, o darnos un ejemplo?

**Comment by slromero-indra** [comment]
Buenas,
hemos revisado el primer punto, y después de guardar la primera vez, se mantiene la página y se muestran los módulos de modelos y documentación.

Respecto al segundo punto, parece que esta comprobación ya se está realizando al guardar el trámite, ¿puedes facilitarnos como reproducirlo, o darnos un ejemplo?

**Comment by slromero-indra** [comment]
Respecto al segundo punto, actualmente solo se valida si hay un único trámite de inicio cuando el procedimiento es publico. **Lo que se solicita** (según entendimos en la reunión) es que esta validación se realice siempre, tanto si es publico como si es interno.

**Comment by slromero-indra** [comment]
Buenas, hemos realizado la modificación solo a nivel del trámite, ya que, haciendo pruebas, hemos detectado que, si se añade a nivel de procedimiento, una vez guardado el procedimiento y creado el trámite de inicio, el trámite de inicio no se podía eliminar ni substituir por otro. El funcionamiento queda como sigue:

- En la ventana de trámites

1. Al guardar siempre se comprueba que solo exista un trámite de inicio, tanto si el procedimiento es público como si no.

- En la ventana de procedimientos (se queda como hasta ahora)
1. Si el procedimiento no es público (interno) permite guardar el trámite, aunque no exista un trámite de inicio
2. Si el procedimiento es público, solo permite guardar si existe un trámite de inicio y es único.
