### ISSUE TITLE
Utilitat exportació resultats de cerca a fitxer

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#401]
Es sol·licita incorporar a les pestanyes de "cercador" una utilitat d'exportació a fitxer (Excel o csv).
El botó "Exportació" haurà de bolcar a fitxer els mateixos resultats de la cerca, tenint en compte els filtres aplicats i mantenint els criteris d'ordenació de resultats.
La utilitat haurà d'estar disponible en els cercadors de fitxes informatives, procediments, normativa i personal.
Els camps que ha de contenir el fitxer seran els següents:

- **Fitxes Informatives** 
(CODI_FITXA, 
NOM_FITXA_CA,
NOM_FITXA_ES,
ESTAT_FITXA DECODE(FIC_VALIDA,1,'PUBLIC',2,'INTERN','RESERVA')
VISIBILITAT_FITXA (ESTAT+DATA_PUB+DATA_CAD + UA_VISIBLE)
PUBLIC_OBJECTIU (ID_PUBLIC OBJECTIU SEPARATS PER COMES)
NOM UA
DATA_ACTUALITZACIO)
- **Procediments** 
(CODI_PROCEDIEMNT, 
CODI_SIA
ESTAT_SIA
DATA_ACTUALITZACIO_SIA
ESTAT_PROCEDIMENT DECODE(PRO_VALIDA,1,'PUBLIC',2,'INTERN','RESERVA')
VISIBILITAT_PROCEDIMENT (ESTAT+DATA_PUB+DATA_CAD + UA_VISIBLE)
NOM_PROCEDIMENT_CA,
NOM_PROCEDIMENT_ES,
OBJECTE_CA
PUBLIC_OBJECTIU (ID_PUBLIC OBJECTIU SEPARATS PER COMES)
NOM UA_INSTRUCTURA 
NOM UA_RESPONSABLE	
NOM_RESPONSABLE	
NOM_UA_RESOLUTORIA	
NUM TRAMITS
NUM TRAMITS TELEMÀTICS
NUM NORMES
DATA_ACTUALITZACIO
COD_USUARI_DARRERA_ACT,
NOM_USUARI_DARRERA_ACT)
- **Normativa**
(CODI_NORMA, 
NOM_NORMA_CA,
NOM_NORMA_ES,
ESTAT_NORMA DECODE(NOR_VALIDA,1,'PUBLIC',2,'INTERN','RESERVA'),
VISIBILITAT_NORMA (ESTAT+DATA_PUB+DATA_CAD + UA_VISIBLE),
PUBLIC_OBJECTIU (ID_PUBLIC OBJECTIU SEPARATS PER COMES),
TIPUS_NORMATIVA (LOCAL, EXTERNA),
NOM UA,
RANG_LEGAL (LLEI, DECRECET,...)
TIPUS_BUTLLETÍ,
NUM_BUTLLETÍ,
ENLLAÇ
DATA_NORMA)
- **Personal**
(CODI_PERSONA,
NOM_PERSONA,
CARREC,
NOM_UA,
CORREU ELECTRÒNIC
TELEFON EXTERIOR (PER_NUMPUB)
EXTENSIÓ FIXA (PER_EXTPUB)
TELEFON MÒBIL (PER_NUMMOV)
EXTENSIÓ MÒBIL (PER_EXTPUB)
)

**Comment by slromero-indra** [comment]
Buenas, cuando se especifica que se puede exportar a Excel o csv, no tenemos claro si es que debe existir un combo con las 2 opciones (generando un .xls o .calc dependiendo de la opción) o bien debemos exportar a una de esas dos opciones (no habrá combo y directamente exportará sólo a uno de los dos formatos).

**Comment by sgelabert-dgtic** [comment]
Basta exportar a csv, així podrem obrir-ho tant amb Excel com amb LibreOfice.
He corregit el nom de les columnes que han de tenir els fitxers, fixau-vos-hi perquè des de qualitat ens sol·liciten que siguin aquests (òbvimane sense els `comentaris`)

**Comment by slromero-indra** [comment]
Buenas, respecto a las fichas, se relacionan con las UA y las secciones por lo que, cuando se pide 'NOM UA', se pide el nombre de todas las UAs con las que tiene relación una ficha?

En personal, hay una pequeña errata, el valor PER_EXTPUB está duplicado en dos campos, el correcto será EXTENSIÓ MÒBIL (PER_EXTMOV).

Saludos!

**Comment by sgelabert-dgtic** [comment]
No, es tracta d'exportar a fitxer els resultats de la pestanya de cerca. Si no vaig errat el cercador sempre filtre per la UA seleccionada a la molla de pa. 
Ok amb la correcció del camp PER_EXTMOV

**Comment by slromero-indra** [comment]
Buenas, en las normativas se especifica un campo público objetivo pero no tenemos muy claro de donde extraer dicho campo. Las normativas carecen de público objetivo, no sé si dicho campo sobra o bien se debería extraer de los procedimientos asociados.

**Comment by sgelabert-dgtic** [comment]
És un error de copy&paste. Les normatives no s'associen a cap public objectiu.

**Comment by sgelabert-dgtic** [comment]
- En l'exportació de procediments, hi ha vegades que no recupera valor per les columnes COD_USUARI_DARRERA_ACT, NOM_USUARI_DARRERA_ACT. Aquí teniu un exemple [llistat-6.xlsx](https://github.com/GovernIB/rolsac/files/1097461/llistat-6.xlsx)

-No s'està tractant bé el nom de les columnes amb caràcters especials. Millor **eliminem** els accents de totes les columens (TIPUS_BUTLLETÍ, NUM_BUTLLETÍ, CORREU ELECTRÒNIC, EXTENSIÓ FIXA, TELÈFON MÒBIL, EXTENSIÓ MÒBIL)

**Comment by slromero-indra** [comment]
Actualizado los literales de las  cabeceras y se ha cambiado como se obtiene la auditoria para saber el último usuario en modificar el procedimiento (se ordena por fecha descendiente y se penaliza en el ordenamiento si no tiene el usuario o/y la fecha rellena; recorriendo uno a uno las auditorias se selecciona el primero que tenga los datos completos).

**Comment by sgelabert-dgtic** [comment]
Pareix que tenim errades JS en

**Comment by slromero-indra** [comment]
Se ha reabierto para solucionar el comentario incluido antes del cierre.

**Comment by sgelabert-dgtic** [comment]
En el llistat d'exportació de procediment hi manca el camp NOM_RESPONSABLE, el qual s'ha de situar entre   NOM UA_RESPONSABLE i NOM_UA_RESOLUTORIA, tal i com es demana incialment a la incidència.

**Comment by slromero-indra** [comment]
Habéis podido verificar el funcionamiento para cerrar la incidencia?
