### ISSUE TITLE
Modificar dades de contacte telefònic pàgina de Personal

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#402]
Es sol·licita efectuar els següent canvis sobre la secció contacte telefònic de la pàgina de personal. Concretament s'han de deixar només els següents camps:
- Correu electrònic (PER_EMAIL)
- Telèfon exterior (PER_NUMPUB)
- Extensió fixa (PER_EXTPUB)
- Mòbil exterior (PER_NUMMOV)
- Extensió mòbil (PER_EXTMOV)

**Comment by slromero-indra** [comment]
Hemos ocultado los 2 campos sobrantes (nº largo privado y extensión privada), tras probar a redistribuir las campos de contacto para aprovechar el espacio, finalmente hemos visto más correcto completar sólo una fila sólo sin aumentar el tamaño de los campos.

**Comment by sgelabert-dgtic** [comment]
Cal modificar els literals actuals pels que es sol·licita a la incidència:
ca --> Telèfon exterior , Extensió fixa, Mòbil exterior, Extensió mòbil
es --> Teléfono exterior , Extensión fija, Móvil exterior, Extensión móvil

**Comment by slromero-indra** [comment]
Buenas, ya hemos actualizado los literales. Además, en la cabecera del listado hemos cambiado el literal 'EXTENSIÓN PÚBLICA INTRANET' por 'Extensión fija / extenció fixa'.
