### ISSUE TITLE
Versionat de llibreries sac-api-client i solr-api

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#403]
Es sol·licita versionar les llibreries sac-api-client,jar i solr-api.jar a partir de la versió del projecte.
Les llibreries s'hauran d'instal·lar i recuperar del repositori Maven, per part del projecte generador o dels consumidors sense necessitat de fer instal·lacions o còpies manuals de les llibreries fora del projecte.
En cas de projectes ANT, valorar la utilització de llibreries ant-maven-task per automatitzar aquestes tasques.

**Comment by slromero-indra** [comment]
Se va a proceder a generar el tag rolsac-1.6 y gusite-1.5 para subir los cambios del versionado a las nuevas ramas.

**Comment by slromero-indra** [comment]
Está subido el versionado para ROLSAC-1.6. ¿Respecto a los cambios que había que realizar para GUSITE, queréis que creemos una nueva rama (GUSITE-1.5) para que incluya estos cambios o comiteamos en GUSITE-1.4?

En el caso de SEUCAIB y WEBCAIB, al ser cambios más sencillos (son proyectos mavenizados y cuesta menos añadir dependencias), los cambios pueden ser comiteados cuando se realice correctamente la subida de WEBCAIB 3-0.

**Comment by sgelabert-dgtic** [comment]
Si millor cream una nova branch GUSITE 1.5 i hi col·loquem tot el que tenim pendent de resoldre fora del tag 1.4.1

**Comment by sgelabert-dgtic** [comment]
Hauríem de poder especificar el repositori local maven en el fitxer de propietats d'usuari de ROLSAC i GUSITE i recuperar/instal·lar allà els clients solrapi i sac-api-client. Com ho veis ?

**Comment by slromero-indra** [comment]
Buenas, lo miramos y te decimos algo en la mayor brevedad posible.

**Comment by slromero-indra** [comment]
Hemos incluido en el fichero default.properties una propiedad donde incluir la ruta al repositorio local:
` svn.repository.path=C:\\Usuarios\\USUARIO\\.m2\\repository\\
`

En dicho repositorio se instalará el sac-api-client de ROLSAC y se leerá el jar de solrapi.

**Comment by sgelabert-dgtic** [comment]
- La propietat ha d'estar al fitxer `build.[user].properties` i no al `default.properties` ja que el path del repositori mvn depèn de cada instal·lació (és el mateix cas que la rurta de desplegament del Jboss).
- Cal canviar el nom de la propietat per `mvn.repository.path` ja que es refereix al repositori Maven no al SVN.
- En cas que sigui necessari en els fitxers ant, cal fer referència al fitxer de propietats d'usuari de la següent manera: `${home}/build.${user.name}.properties`

**Comment by sgelabert-dgtic** [comment]
Actualitzar també els següents valors per la branca 1.6: 
En el `default.properties`:
`# Version ROLSAC.`
`rolsac.version=1.6`
`rolsac.version.tag=1.6.0`

En del `build.xml` principal:
`<project name="rolsac-${rolsac.version}" default="main01ROLSAC" xmlns:artifact="antlib:org.apache.maven.artifact.ant">`

**Comment by slromero-indra** [comment]
Hemos para que utilice el fichero build.USERNAME.properties (se ha subido un fichero con dicho nombre por defecto, que debería renombrarse según cada máquina). Dichos cambios también están en la rama 1.5 de gusite.

**Comment by sgelabert-dgtic** [comment]
- Cal eliminar el fitxer build.slromero.properties del repositori Git
- Canviar el comentari del fitxer build.USERNAME.properties
```
# SVN
mvn.repository.path=C:\\Usuarios\\USERNAME\\.m2\\repository\\
```
Pel següent:
```
# Maven local repositori
mvn.repository.path=C:\\Usuarios\\USERNAME\\.m2\\repository\\
```
- Cal eliminar la dependència de compilació amb la llibreria solr-api-web.jar del projecte.  S'ha de reconfigurar la tasca ant perquè agafi la llibreria del repositori remot MVN de GitHub

**Comment by sgelabert-dgtic** [comment]
Podeu indicar-me si donau aquest tiquet per resolt ?

**Comment by dmadronal-indra** [comment]
Los cambios están comiteados sobre la rama 1.7, queda pendiente actualizar la rama 1.6 para darla por finalizada. En breve lo actualizamos y la marcamos como finalizada.

**Comment by dmadronal-indra** [comment]
Lo revisamos.

**Comment by bgarcia-dgtic** [comment]
Respecte al desplegament, ens retorna un http 405 (Not Allowed) quan activem l'opció mavencaib.deploy=true dins el build.USERNAME.properties
Com ho hauríem d'autenticar-nos?

**Comment by slromero-indra** [comment]
Hay dos maneras para autenticarse:
- Hemos incorporado en el default.properties dos parámetros para autenticarse (mavencaib.username=caib y mavencaib.password=caib). O bien se actualiza el default.properties o bien se añaden los dos parámetros al build.USERNAME.properties (username tiene que cambiarse por el del usuario).
- Otra posibilidad es añadirlo en el settings.xml de maven. En la issue de redmine solrapi se incluye un documento donde se especifica como poder autenticarse. https://redmine.caib.es/issues/2412

Respecto al punto : 
   _Des del punt de vista de SOLR-API-WEB s'ha de poder instal·lar en el repositori remot la versió solr-api.jar corresponent a la versió que s'empaqueta._
¿No fue resuelta en la issue 2412 de redmine? https://redmine.caib.es/issues/2412

**Comment by sgelabert-dgtic** [comment]
Seguim tenint problemes per pujar la llibreria sac-api-client.jar al repositori de GitHub:
```
[artifact:install] [INFO] Installing D:\Development\workspace-luna-R-win32-x86_64\ROLSAC-1-6-GIT\output\moduls\sac-api-client.jar to D:\LlibreriesJava\apache-maven-3.3.9\.m2\repository\es\caib\rolsac\rolsacAPI\1.6.0\rolsacAPI-1.6.0.jar
mavenDeployROLSAC:
[artifact:deploy] Deploying to https://GovernIB.github.io/maven/maven
[artifact:deploy] Uploading: es/caib/rolsac/rolsacAPI/1.6.0/rolsacAPI-1.6.0.jar to repository github-governib-maven-repos at https://GovernIB.github.io/maven/maven
[artifact:deploy] Transferring 1264K from github-governib-maven-repos
[artifact:deploy] An error has occurred while processing the Maven artifact tasks.
[artifact:deploy]  Diagnosis:
[artifact:deploy] 
[artifact:deploy] Error deploying artifact 'es.caib.rolsac:rolsacAPI:jar': Error deploying artifact: Failed to transfer file: https://GovernIB.github.io/maven/maven/es/caib/rolsac/rolsacAPI/1.6.0/rolsacAPI-1.6.0.jar. Return code is: 405
[artifact:deploy] 
```
S'autoritza a l'usuari @dmadronal-indra per fer upload de fitxers i testejar l'error

**Comment by dmadronal-indra** [comment]
Buenas, Se ha revisado lo siguiente:
- Modificado rolsac para que publique sac-api-client en guithub.  tanto en la rama 1.6 como en la 1.7
- Se ha actualizado gusite para que descargue correctamente la libreria.
- Se ha actualizado sede y webcaib para que descarguen correctamente la libreria.

Por otro lado, se ha validado que el proyecto solrapi permite publicar en github la libreria.

**Comment by dmadronal-indra** [comment]
Buenas, 
- Revertidos los cambios en los pom de WEBCAIB para que se continue usando la libreria almacenada en el proyecto. 

- A partir de la versión 1.6 del sacapiclient se modifica la obtención de documentos de normativas, que pasa a retornar un listado, y webcaib no esta preparada. se mantiene la libreria local, a la espera de verificar los cambios a realizar en webcaib para adaptarse a la versión rolsac 1.6 en adelante. 

Quedamos a la espera para que nos indiqueis como proceder con WEBCAIB.

**Comment by sgelabert-dgtic** [comment]
Seguim amb problemes per fer l'install de la llibreria al repositori MVN de GitHub de la llibreria sac-api-client.jar.
**Configuració:**
```
mvn.repository.path=D:\\LlibreriesJava\\apache-maven-3.3.9\\.m2\\repository
mvn.installation.path=D:\\LlibreriesJava\\apache-maven-3.3.9
mavencaib.deploy=true
mavencaib.username=sgelabert-dgtic
mavencaib.password=XXXXXX
```
**Error:**
```
  [echo] Comenzamos a realizar el deploy
[artifact:mvn] -Dmaven.multiModuleProjectDirectory system property is not set. Check $M2_HOME environment variable and mvn script match.org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
[artifact:mvn] 	at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:193)
[artifact:mvn] 	at java.lang.Runtime.exit(Runtime.java:107)
[artifact:mvn] 	at java.lang.System.exit(System.java:962)
[artifact:mvn] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:358)
[artifact:mvn] 	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[artifact:mvn] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[artifact:mvn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn] 	at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:217)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:152)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:771)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:221)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
[artifact:mvn] 	at org.apache.maven.artifact.ant.Mvn.execute(Mvn.java:91)
[artifact:mvn] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[artifact:mvn] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[artifact:mvn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn] 	at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[artifact:mvn] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[artifact:mvn] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[artifact:mvn] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[artifact:mvn] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[artifact:mvn] 	at org.eclipse.ant.internal.launching.remote.EclipseSingleCheckExecutor.executeTargets(EclipseSingleCheckExecutor.java:34)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[artifact:mvn] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[artifact:mvn] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[artifact:mvn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn] 	at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[artifact:mvn] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[artifact:mvn] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[artifact:mvn] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[artifact:mvn] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[artifact:mvn] 	at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[artifact:mvn] 	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:452)
[artifact:mvn] 	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:139)
[artifact:mvn] Java Result: 100
```

Respecte a WEBCAIB i SEUCAIB, ambdós projectes haurien de tenir la referència a la llibreria del repositori de GitHub amb la versió que correspongui

**Comment by dmadronal-indra** [comment]
Buenas,
Hace unos minutos hemos probado a deployar de nuevo y no hemos tenido problemas.
el error que aparece es posible que sea debido a la versión de maven, ¿podéis verificar si la variable del sistema M2_HOME se corresponde con la versión indicada en el properties? con referencia a esto hemos encontrado este enlace:
https://stackoverflow.com/questions/29330577/maven-3-3-1-eclipse-dmaven-multimoduleprojectdirectory-system-propery-is-not-s

**Comment by sgelabert-dgtic** [comment]
Afegint `-Dmaven.multiModuleProjectDirectory=$M2_HOME` m'ha pujat la llibreria.
La tasca ANT, acaba el següent missatge. A voltros us passa ?:
```
[artifact:mvn] [INFO] BUILD SUCCESS
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [INFO] Total time: 53.031 s
[artifact:mvn] [INFO] Finished at: 2018-08-20T11:52:31+02:00
[artifact:mvn] [INFO] Final Memory: 57M/692M
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
[artifact:mvn] 	at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:193)
[artifact:mvn] 	at java.lang.Runtime.exit(Runtime.java:107)
[artifact:mvn] 	at java.lang.System.exit(System.java:962)
[artifact:mvn] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:358)
[artifact:mvn] 	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[artifact:mvn] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[artifact:mvn] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[artifact:mvn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn] 	at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:217)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:152)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:771)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:221)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
[artifact:mvn] 	at org.apache.maven.artifact.ant.Mvn.execute(Mvn.java:91)
[artifact:mvn] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[artifact:mvn] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[artifact:mvn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn] 	at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[artifact:mvn] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[artifact:mvn] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[artifact:mvn] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[artifact:mvn] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[artifact:mvn] 	at org.eclipse.ant.internal.launching.remote.EclipseSingleCheckExecutor.executeTargets(EclipseSingleCheckExecutor.java:34)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
[artifact:mvn] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[artifact:mvn] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[artifact:mvn] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[artifact:mvn] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[artifact:mvn] 	at java.lang.reflect.Method.invoke(Method.java:606)
[artifact:mvn] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[artifact:mvn] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[artifact:mvn] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[artifact:mvn] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[artifact:mvn] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[artifact:mvn] 	at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
[artifact:mvn] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[artifact:mvn] 	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:452)
[artifact:mvn] 	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:139)
[artifact:mvn] Java Result: 100
BUILD SUCCESSFUL
Total time: 2 minutes 54 seconds
```

**Comment by dmadronal-indra** [comment]
Buenas,  
A pesar de que ese mensaje no impide la subida del fichero y la ejecución de la tarea ant acaba correctamente, hemos actualizado el build.xml para que deje de retornar el error.
Además, hemos actualizado la documentación (guía rápida de instalación) para realizar alguna corrección, y añadir varios comentarios.

**Comment by sgelabert-dgtic** [comment]
Amb la versió de de Maven 3.3.9 he hagut d'afegir el següent per fer el deploy de la llibreria:
- Definir la variable d'entorn M2_HOME que apunti a l'arrel del directori d'instalació de Maven
- Afegir a la variable d'entorn JAVA_TOOL_OPTIONS -Dmaven.multiModuleProjectDirectory=$M2_HOME

**Projecte:**
- La propietat mavencaib.deploy=false està duplicada en el  `default.properties` i `build.USERNAME.properties`. Basta deixar-la al  `default.properties` 

**Documentació:**
- La Guia ràpida d'instal·lació es troba a la carpeta arrel `/doc `i duplicada i desactualitzada en els subdirectoris de les versions. Cal eliminar el document de `/doc/1.5` i `/doc/1.6`
- Respecte al contingut:
  - Revisar l'apartat 6.1 Requisit. Hi falta com a requeriment tenir instal·lat Maven i com cal revisar la versió de la JVM (el projecte funciona amb una 1.5??)
  - Cal definir la utilitat i valors de les noves variables introduïdes dins els fitxer `default.properties` i `build.USERNAME.properties`
  ```
  mvn.repository.path=C:\\apache-maven-3.3.9\\.m2\\repository
  mvn.installation.path=C:\\apache-maven-3.3.9
  mavencaib.url=https://governIB.github.io/maven/maven/
  mavencaib.deploy=false
  mavencaib.username=XXXX
  mavencaib.password=XXXX
```

**Comment by dmadronal-indra** [comment]
Buenas,
hemos actualizado la documentación y eliminado la libreria ojdbc14 del proyecto.
