### ISSUE TITLE
Bug manteniment d'edificis del menú Administració

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#405]
S'ha detectat un bug en el manteniment d'edificis, quan s'intenta recuperar les coordenades de latitud i longitud a partir d'una adreça determinada.
Adjunt captura de pantalla
![bugedificis](https://user-images.githubusercontent.com/17268396/27904746-0167a9aa-623e-11e7-887a-b3b7164e9606.jpg)
En conseqüència el frontal no presenta bé la informació de geoposicionament
http://www.caib.es/govern/organigrama/planol.do?lang=ca&coduo=7

**Comment by sgelabert-dgtic** [comment]
He actualitzat el valor de la propietat  `es.indra.caib.rolsac.googleMapKey` sobre l'entorn de PREproducció i funciona correctament.
Es sol·licita però efectuar els canvis necessaris per normailtzar el nom de la propietat a `es.caib.rolsac.googleMapKey`
Revisar també si les següent propietats s'utilizen i en cas afirmatiu, normalitzar-les per `es.caib.rolsac`:
```
es.indra.caib.rolsac.servidor=localhost
es.indra.caib.rolsac.servidorPuerto=localhost
es.indra.caib.rolsac.oficina=N
       
```

**Comment by slromero-indra** [comment]
Actualizado las propiedades y los java que las utilizan:

- es.indra.caib.rolsac.oficina --> es.caib.rolsac.oficina
- es.indra.caib.rolsac.googleMapKey --> es.caib.rolsac.googleMapKey


Estas 2 propiedades no se utilizan y han sido borradas del jboss-service.xml:

- es.indra.caib.rolsac.servidor=localhost
- es.indra.caib.rolsac.servidorPuerto=localhost

**Comment by slromero-indra** [comment]
Se puede dar por cerrada la incidencia?
