### ISSUE TITLE
Millores en la gestió de normativa 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#406]
Es sol·licta modificar la pantalla de Normativa perquè doní servei tant a l'Inventari de procediments com a la publicació de normativa d'aplicació d'una Unitat Orgànica. D'entrada es proposen els següents canvis:
-	Eliminar la diferenciació entre normativa externa i local 
-	Eliminar del camp "Tipus de normativa" tot allò que no siguin normes (intruccions, circulars,...)
-	Introduir un nou camp "Núm. Norma" (format nnn/yyyy on nnn és el núm. de norma i yyyy es l'any).
-	Canviar nom camp "Data Norma" per "Data aprovació" (amb selector de data)
-	Deixar en el camp "Tipus de Butlletí" únicament els valors (BOIB, BOE i DOUE)
-	Controlar la unicitat de la norma a partir dels camps "Núm. Norma" + "Data aprovació" + "Tipus de Butlletí"
-	Canviar apartat "Dades del butlletí" per "Dades de publicació" en el qual hi figuraran només els camps "Tipus Butlletí", "Data Butlletí", "Núm. Butlletí" i "Enllaç a la norma"
-	Permetre relacionar la norma amb més d'una Unitat Orgànica, les quals indicaran els Organismes on es d'aplicació aquesta norma.
-	El camp "Estat" registrarà els valors "Vigent" per defecte i "Derogada". No té sentit el control de visibilitat de la norma, per tant, s'elimina
-	 Un usuari gestor només podrà modificar (dades de la norma, canviar l'estat a derogada) exclusivament de normes de les Unitat Orgàniques que gestiona o descendents. 
-	Es manté el mòdul lateral d'afectacions a la norma (no obligatori)
-	S'introdueix mòdul lateral de documents relacionats amb la norma
-	Quan la norma provingui del BOIB, es permetrà l'alta manual o bé la cerca a través de traspàs del BOIB
-	Revisar la funcionalitat de traspàs de BOIB perquè incorpori el "Tipus de Norma" a partir de les categories http://www.caib.es/eboibfront/ca/tipus-publicacio
-	Definir els camps obligatoris de la pantalla (Num Norma, Data aprovació, tipus butlletí, Titol, Tipus norma i enllaç)
-	Revisar les pantalles de cerca de normativa perquè es pugui filtrar per Num. Norma, Data Aprovació, Tipus de Butlletí , Tipus de Normativa, Titol i Estat
-	Revisar la pantalla de procediments administratius perquè alerti al desar, si hi ha normativa derogada relacionada amb el procediment.

En primera instància es sol·licita mockup de la pantalla per la validació funcional i el·laboració d'un document d'anàlisi i estimació de la tasca

**Comment by slromero-indra** [comment]
Ahora mismo en ROLSAC existe: Normativa, NormativaExterna, NormativaExternaRemota, NormativaLocal y NormativaRemota. Debido al requisito 'Eliminar la diferenciació entre normativa externa i local', se va a proceder a simplicar el número de clases a Normativa y NormativaRemota.

¿La normativa remota se debe mantener?

**Comment by slromero-indra** [comment]
Estamos actualizando el tipo de normativa debido a que los requisitos se pedían quitar alguno de ellos que no sean normas (instruccions, circulars...). Por favor, podéis indicarnos cuales deben quitarse.

![image](https://user-images.githubusercontent.com/17451407/30368426-5ed4d63a-9871-11e7-814d-2fd970a7e290.png)


Al igual que tipo de boletín, se dejará a nulo el tipo de normativa que se quiten.

También se incluyen los siguientes scripts:
 - Schema: Se crean las nuevas tablas y campos. En algunos casos, como por ejemplo el tipo y la validación, se utiliza un nuevo campo para poder realizar un cambio de rolsac-1.5 a 1.6 (y a la inversa) sin realizar ningún cambio (el único será la vista RSC_TRANOR que se tiene que renombrar ).
- Data. Para rellenar los nuevos campos o adaptarlos
- Script (hay 2 ficheros).  Son para rellenar los datos tanto de los documentos como los enlaces.

Falta terminar la batería de pruebas que estará a lo largo del día además de algún detalle menor.

**Comment by sgelabert-dgtic** [comment]
- S'han d'eliminar del repositori Git tots els fitxers de la carpeta /ROLSAC-1.6/scripts/bbdd/1.6/oracle que no siguin per pujar de la versió 1.5 a la 1.6 o bé per fer una instal·lació des de zero. Concretament:
```
/ROLSAC-1.6-GIT/scripts/bbdd/1.6/oracle/rolsac_update_data_from_1.4.0_to_1.5.0.sql
/ROLSAC-1.6-GIT/scripts/bbdd/1.6/oracle/rolsac_update_data_from_1.5.4_to_1.5.5.sql
/ROLSAC-1.6-GIT/scripts/bbdd/1.6/oracle/rolsac_update_schema_from_1.4.0_to_1.5.0.sql
/ROLSAC-1.6-GIT/scripts/bbdd/1.6/oracle/rolsac_update_schema_from_1.5.0_to_1.5.2.sql
/ROLSAC-1.6-GIT/scripts/bbdd/1.6/oracle/rolsac_update_schema_from_1.5.2_to_1.5.3.sql
/ROLSAC-1.6-GIT/scripts/bbdd/1.6/oracle/rolsac_update_schema_from_1.5.3_to_1.5.4.sql
/ROLSAC-1.6-GIT/scripts/bbdd/1.6/oracle/rolsac_update_schema_from_1.5.4_to_1.5.5.sql
```
Per altra banda un dubte, el canvis a nivell de BBDD per la gestió de normativa són compatibles amb la versió 1.5 ? És a dir, una vegada actualitzada la BBDD per 1.6 podriem seguir emprant una versió 1.5. Si no és així caldrá preparar script de restauració.

**Comment by sgelabert-dgtic** [comment]
Hi ha errades en l'script 'rolsac_update_data_script_from_1.5.5_to_1.6.0.sql'
`ORA-00904: "TNO_ENLACE": identificador no válido 00904. 00000 -  "%s: invalid identifier"`

**Comment by slromero-indra** [comment]
Buenas, la compatibilidad entre ambas versiones se mantienen (no borramos ningún campo para mantener la compatibilidad). Hay que tener en cuenta que hay campos nuevos en la 1.6 y campos deprecated, mezclar versiones no es recomendable para evitar datos consistentes o que se pierdan por el cambio, por lo que (al menos en producción) sólo volver a la 1.5 en caso de error grave. 

Respecto al problema del script, que scripts se han ejecutado? Sólo se ha ejecutado el 'rolsac_update_data_script_from_1.5.5_to_1.6.0.sql'?

**Comment by slromero-indra** [comment]
En el entorno caibter se  encuentra la rama 1.6. URL --> http://caibter.indra.es/rolsacback

**Comment by sgelabert-dgtic** [comment]
De moment no s'ha executat cap script sobre la BBDD de PREproducció de ROLSAC, evidentment sobre la de PROducció tampoc.
Vaig fer proves per fer un desplegament en local sobre una BBDD de desenvolupament i em vaig trobar amb l'error reportat al executar l'script 'rolsac_update_data_script_from_1.5.5_to_1.6.0.sql'. Pareix que hi ha un error en el prefix de la columna.
Ok al comentari sobre l'update de versió 1.5 a 1.6. Ho tindrem en compte.

**Comment by slromero-indra** [comment]
Pendiente de la DGTIBG para indicar las pautas a seguir para la depuración de datos.
