### ISSUE TITLE
Gestió catàleg de serveis administratius

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#407]
Es sol·licita incorporar dins ROLSAC la gestió d'un catàleg de serveis administratius. Es proposa partir de la mateixa fitxa de procediments i efectuar els següents canvis:
-	S'afegirà un filtre selector (procediment/servei) en per donar d'alta un servei (el qual ocultarà els camps no necessaris per un servei). (*pendent de validació, l'alternativa es fer-ho amb una pestanya nova de Serveis)
-	Es mantenen els camps estat, data de publicació i data caducitat (canviar nom per data despublicació)
-	Es mantenen els camps nom, objecte i destinataris
-	S'afegeix un camp requisits
-	S'eliminen els camps forma d'inici, termini, silenci, via i el check de taxa
-	S'afegeix un mòdul lateral de Taxa amb un nou camp URL
-	S'elimina Òrgan competent per resoldre
-	Es manté Òrgan instructor, coma òrgan que gestiona el servei
-	Es manté el camp Observacions
-	A la Secció Dades de Contacte: S'afegeix el camp telèfon de contacte
-	Es manté mòdul lateral de Públic Objectiu (obligatori)
-	Es manté mòdul lateral de Normatives (no obligatori)
-	Es manté mòdul lateral de Matèries (obligatori per SIA)
-	S'afegeixen camps per l'enllaça al tràmit telemàtic del servei
-	S'elimina mòdul lateral de tràmits
-	S'elimina camp "tipus procediment"

Respecte a la integració amb SIA es mostraran els camps Codi SIA, Actualització SIA i Estat SIA. Cal comprovar amb la documentació tència del MINHAP el conjunt mínim de camps obligatori per consolidar el catàleg de serveis ROLSAC amb SIA-PAG

En primera instància es sol·licita mockup de la pantalla per la validació funcional i el·laboració d'un document d'anàlisi i estimació de la tasca

**Comment by slromero-indra** [comment]
Necesitamos saber cual es la opción preferida para la creación correcta del documento de análisis, si bien preferís un filtro selector o una pestaña aparte, o bien somos nosotros quienes tomamos la decisión.

Si se selecciona un filtro selector:
 - Aumenta el coste de seleccionar, ocultar y mostrar los campos obligatorios.
 - Aumenta el tamaño de los ficheros, haciéndolos más complejos (catalegProcediments es un fichero demasiado grande).
- Cualquier campo que sea en común entre procedimientos y servicios será más sencillo de introducir.

Si se crea una nueva pestaña:
 - Es más fácil controlar los campos a mostrar y los obligatorios.
 - Por contra, estamos duplicando los ficheros (aunque partamos de catalegProcediments).

**Comment by sgelabert-dgtic** [comment]
D'entrada jo optaria per l'opció pestanya. Estic pendent però de confirmació per part de la DG de Transparència.

**Comment by sgelabert-dgtic** [comment]
L'opció que ha triat la DG de Transparència és obrir un nou menú general "Catàleg de serveis" independent del "Inventari de procediments".
Aquest nou menú tindria les 3 pestanyes típiques "Llistat", "Cercador", "Crea un nou Servei"
Si teniu algun dubte en parlem

**Comment by slromero-indra** [comment]
Ok, tomaremos esa vía. Sólo una duda que tenemos. De manera interna, los servicios y los procedimientos compartirán la misma tabla (a partir del atributo PRO_TYPE, se especificará a cuál pertenece). La duda es, en la pantalla de normativas, hay un módulo de 'Procedimientos relacionados'. Ahora con los servicios:
 - ¿Hay que crear un módulo especifico de servicios relacionados o bien tendrá dicho modulos los servicios y los procedimientos?

**Comment by sgelabert-dgtic** [comment]
Sí, per coherència convé separar-ho en un mòdul nou i independent de procediments.
Només comentar que en la pantalla de normativa tant el mòdul de procediment, com el futur mòdul de serveis són de només consulta. Una possible millora seria que els items funcionesin com enllaç i et duguin a la pantalla d'edició de procediments o serveis, respectivament (ho podeu incloure en el tiquet #406)

**Comment by sgelabert-dgtic** [comment]
Ok em pareix una bona opció. Entenc doncs que es dotarà a les capes de persistència/lògica de negoci de mètodes separats per gestionar la informació del Catàleg de Serveis, correcte ?

**Comment by slromero-indra** [comment]
Si, aprovecharemos el ya existente de Procedimiento para gestionar la información del catálogo de servicios.

**Comment by slromero-indra** [comment]
Trabajo realizado pendiente de activarlo en el menú principal tras la validación de normativas.

**Comment by sgelabert-dgtic** [comment]
Podeu habilitar de nou la pestanya per començar a fer proves ?
Gràcies

**Comment by sgelabert-dgtic** [comment]
Apareix un mòdul lateral "Normativa del procediment", quan s'hauria de dir "Normativa del Servei". Endemés quan es gestionen normatives s'ha d'enllaçar amb una pantalla amb els filtres nous de normativa (la mateixa que apareix quan gestiones la normativa del procediment.

**Comment by sgelabert-dgtic** [comment]
Per altra banda, les auditories no queden correctament registrades

**Comment by slromero-indra** [comment]
Hemos realizado las pruebas de integración con SIA y el servicio se publica correctamente sin tener en cuenta si tiene normativa o no.

**Comment by sgelabert-dgtic** [comment]
El filtres "Tipus normativa" i "Butlletí" del cercador de normativa en la pantalla de "Gestió de normativa" de l'inventari de serveis no recuperen valors. Adjunt captura de pantall de l'entorn de Dev:
![image](https://user-images.githubusercontent.com/17268396/40293459-57ddcfce-5cd1-11e8-9429-88de6b459e20.png)

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos actualizado la aplicación para solventar el problema.

**Comment by sgelabert-dgtic** [comment]
- Tot servei ha d'estar associat a l'òrgan instructor. Si aquest es canvia, s'ha canviar la dependència orgànica i ara no ho fa. Exemple:
  - Alta de servei a nivell de Govern
  - El servei queda en "Advertències pendents SIA" com "El ~~procedimiento~~ servicio esta asociado directamente a la entidad raiz." (modificar el literal)
  - Es canvia l'òrgan instructor a una DG qualsevol però el servei segueix quedant a nivell de Govern
- Per altra banda, en el mòdul lateral de gestió de normativa, el nom de les normes hauria de funcionar com enllaç cap a la pàgina d'edició de Normativa (igual que en els procediments administratius)

**Comment by sgelabert-dgtic** [comment]
- Canviar el literal " Inventari de Serveis" per "Catàleg de Serveis"

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos realizado las modificaciones oportunas, ¿Podeis validarlo?

**Comment by sgelabert-dgtic** [comment]
La vinculació del servei està amb el "Servei o Secció responsable" i no amb el "Òrgan o Servei Instructor" com es sol·licitva

**Comment by dmadronal-indra** [comment]
Buenas, hemos realizado las modificaciones, ¿lo podeis validar?

**Comment by sgelabert-dgtic** [comment]
Error al actualitzar l'estat a SIA a "NO Actiu" quan s'elimina el servei des de ROLSAC.

`Error no controlado para elemento pendiente 3266834: java.lang.Exception: Se ha producido un error enviando el dato a SIA de un borrado de servicio 3266050 at org.ibit.rol.sac.persistence.ejb.SiaPendienteFacadeEJB.borradoServicio(SiaPendienteFacadeEJB.`

Adjunt log del servidor d'aplicacions: [log_rolsac_sia_09-07-2018.txt](https://github.com/GovernIB/rolsac/files/2174911/log_rolsac_sia_09-07-2018.txt)

Les actualitzacions contra SIA funcionen correctament (amb el mateix usuari/password). Pareix com si s'intentés fer una operació no permesa amb l'usuari/password proporcionat.

**Comment by slromero-indra** [comment]
Ya está solucionado el problema de SIA y de la traducción

**Comment by sgelabert-dgtic** [comment]
Comentaris revisió DG Transparència:
PANTALLA "Gestió de Normativa"
- Canviar el label "Gestiona" per "Cercador de Normativa/Buscador de Normativa".
- Inhabilitar el botó "GUARDA!" quan està desactivat. Actualment es permet el click i mostra un missatge de "Normatives de servei guardades correctament" quan no hi ha canvis a la pantalla.
PANTALLA "Catàleg de Serveis"
- Canviar l'estil dels inputs "Nom del servei" i dels que hi ha en les seccions "Dades de contacte" i "Tràmit telemàtic" perquè apareguin en "gris" quan s'han moficat. Actualment sempre apareixen en color negre.
MENÚ PRINCIPAL
- Corregir accent del literal "Cataleg de serveis" --> "Catàleg de serveis/Catálogo de servicios"

**Comment by slromero-indra** [comment]
Se han realizado todos los cambios.  Cuando se pulsa el botón 'Guarda!' ya no realiza ningún acción si está desactivado (off). 

Varios cambios propuestos también se reflejan en procedimientos.  En procedimientos se han realizado los siguientes cambios:
 - El botón de guardar! se comporta igual (en modo desactivado, no hace nada).
 - El literal Gestiona actualizado a 'Cercador de normativa/Buscador de normativa'.
 - Los inputs 'Nom del procediment' y la sección 'Dades de contacte' aparecen en gris.

Si queréis, podemos realizar algún cambio más en procedimientos o tirar hacia atrás algún cambio. 

Tenéis que refrescar la caché porque hay cambios en los js/css que puede producir que se quede el navegador con alguna versión anterior.

**Comment by sgelabert-dgtic** [comment]
S'ha commitat exclusivament sobre el branch 1.7, quan el tiquet és de la versió 1.6.1

**Comment by slromero-indra** [comment]
Cierto, hemos pasado el commit también a la rama 1.6. 

Además de dar bueno los cambios, por favor, confirmadnos si lo que comentamos sobre procedimientos está correcto o se debe realizar algún cambio.

**Comment by sgelabert-dgtic** [comment]
Em podeu confirmar si els commits https://github.com/GovernIB/rolsac/commit/297ea43efa47d651540de1afed34f64502a221ba i https://github.com/GovernIB/rolsac/commit/3282468c9dda7c0111d87f61d7dd90ad726b9f1b són les adaptacions necessàries per la publicació del serveis a la Seu ? Fan falta més adaptacions ?

**Comment by dmadronal-indra** [comment]
Buenas lo que indicas es correcto, Son cambios necesarios para la publicación de servicios. Quedan pendientes varios cambios, ya que hemos detectado algunos problemas en la obtencion de los servicios a través del api. Estamos trabajando para solventarlos. Esperamos poder tener los cambios listos a principios de la semana que viene.

**Comment by episano-dgtic** [comment]
Varios puntos: 
A) Respecto a la página de alta de un servicio: 
   a.1) En castellano está mal traducido "Nom del servei" y "MAteries relacionadas"
![servei_castellano](https://user-images.githubusercontent.com/17451683/44780706-d5734680-ab82-11e8-95cc-b5e7b9cb5d18.gif)
   a.2) El campo objecto se marca como obligatorio pero te permite publicar un servicio con el campo vacio. Si se ha indicado alguna vez algún contenido en dicho campo ya no te deja vaciarlo, al ser obligatorio. 
![objectovacio](https://user-images.githubusercontent.com/17451683/44781424-a8c02e80-ab84-11e8-98e0-2d3bcc818ce5.gif)
   a.3) La normativa del servicio no es obligatoria, y si se indica una luego no deja eliminarla.
![elimina_normativaservei](https://user-images.githubusercontent.com/17451683/44781957-05701900-ab86-11e8-95e8-a3f6fa10fc80.gif)

B) En en buscador de servicios:
   b.1) El filtro por materias no funciona bien. No devuelve resultados, pese tener dicha materia
   b.2) Filtro textual: No filtra por el texto indicado, Devuelve todos los servicios posibles sin filtrar el texto indicado
   b.3) Filtro Visibilidad: No devuelve resultados indicado visible o no visible.

**Comment by dmadronal-indra** [comment]
realizado commit 363d900ebd429588939ce37341e8af0637e61ee9

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado la actualización indicada, ¿lo podeis revisar?
