### ISSUE TITLE
Bug exportació procediments després de l'ordenació de resultats

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#409]
S'ha detectat un bug en la utilitat d'exportació de procediments després de l'ordenació de resultats.
La seqüència de passes és:
1. Fer una cerca des de la pestanya del cercador de procediments
2. Ordenar pel camp "Data d'actualització"
3. Sol·licitar exportació a fitxes
Adjunt captura de pantalla i log del servidor d'aplicacions [logExportacioProc.txt](https://github.com/GovernIB/rolsac/files/1199493/logExportacioProc.txt)
![exportacioproc](https://user-images.githubusercontent.com/17268396/28957901-5a95146e-78f4-11e7-9774-04432c7a2070.jpg)

**Comment by sgelabert-dgtic** [comment]
Podrieu traslladar aquest canvi a la 1.5 ?

**Comment by slromero-indra** [comment]
Trasladados los cambios a la rama 1.5
