### ISSUE TITLE
Ordenació dels resultats de cerca en el cercador de personal

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#410]
L'ordenació per les columnes PERSONA, CÓDIGO UNIDAD ADMINISTRATIVA, CORREO ELECTRÓNICO, 
 o EXTENSIÓN FIJA en la pestanya de cercador no té efectes sobre el resultat de la cerca

**Comment by sgelabert-dgtic** [comment]
Podríeu traslladar aquest canvi a la 1.5?

**Comment by slromero-indra** [comment]
Trasladados los cambios a la rama 1.5
