### ISSUE TITLE
Bug neteja del camp UA competent per resoldre

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#411]
Si s'edita un procediment amb el camp UA competent per resoldre en blanc just després d'haver-ne consultat un altre que el té emplenat, es presenten les dades de l'anterior.

**Comment by sgelabert-dgtic** [comment]
Ens està passant el mateix amb el mòdul lateral del Tramits. Adjunt document de la DG Transparència amb creument d'informació  dels procediments 3005325 i 3020157 de l'entorn de PROducció
[2017-08-09-Captura-pantalla-Pts_3005325-3020157.docx](https://github.com/GovernIB/rolsac/files/1211260/2017-08-09-Captura-pantalla-Pts_3005325-3020157.docx)

S'hauria de revisar que això no passa en altres camps/mòduls

**Comment by sgelabert-dgtic** [comment]
S'hauria de revisar que això no passa en altres camps/mòduls de la fitxa de procediments i tràmits
- El camp Codi del procediment també manté el valor, la fitxa de Procediment
- No es presenten els arxius annexes en catellà en els mòduls de "Models" i "Documents Relacionats amb el Tràmit" de la fitxa de Tramits, tot i que al desar-los no presenten cap problema.

**Comment by sgelabert-dgtic** [comment]
Podríeu donar-li prioritat.
Grácies

**Comment by slromero-indra** [comment]
Buenas, nos ponemos con ello hoy mismo.

**Comment by slromero-indra** [comment]
Además de lo comentado, también se había observado que en el módulo de Trámites de procedimientos tampoco estaba activo el multilenguaje.

**Comment by sgelabert-dgtic** [comment]
No es recupera correctament el nom del tràmit des del mòdul lateral de tràmits en la fitxa de procediments:
![image](https://user-images.githubusercontent.com/17268396/30479990-def4378c-9a17-11e7-861d-24a776ac9321.png)

**Comment by sgelabert-dgtic** [comment]
Segueix sense entrar en l'edició de models quan cliques sobre el mòdul lateral:
![image](https://user-images.githubusercontent.com/17268396/30537218-1990c48e-9c69-11e7-991a-f2983386f878.png)

**Comment by slromero-indra** [comment]
Solucionado el problema tanto en la edición de modelos como de documentos.
