### ISSUE TITLE
Adequació del nom del producte als estàndards CAIB

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#412]
Es sol·licita revisar el projecte i eliminar les referències al nom 01ROLSAC i passar-les a ROLSAC. 
L'objectiu és que el producte final sigui **rolsac.ear** , eliminant qualsevol referència a l'ordre de desplegament de l'aplicació.

**Comment by slromero-indra** [comment]
Aunque los ears están en modo isolated y no debería de generar ningún problema, al cambiar el nombre provocaría un cambio en el orden de cargar los proyectos en jboss y muchos proyectos dependen de ROLSAC. Realizaremos pruebas para revisar que no produce ningún problema al cambiar el orden y que no se produce ningún error inesperado al no cargarse el primero.

**Comment by slromero-indra** [comment]
Actualizado en ambas ramas.
