### ISSUE TITLE
Bug publicació de procediments interns

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#413]
Tenim una errada greu que impedeix canviar l'estat de procediments interns a públics. Ens està donant un error "És obligatori crear un tràmit d'inici". Adjunt captura de pantalla.
![image](https://user-images.githubusercontent.com/17268396/30851682-9bdac00c-a2a9-11e7-8eaa-87574203365f.png)
Per favor, donau-li prioritat perquè rebem múltiples queixes.

**Comment by slromero-indra** [comment]
Nos ponemos a mirarlo. Sobre el procedimiento de la imagen, tiene un trámite de inicio? Todos los campos del trámite de inicio están introducidos (fecha inicio y fecha de publicación)?

**Comment by sgelabert-dgtic** [comment]
Sí, els procediments estan correctament emplenats, amb tràmit d'inici, models, normativa, dates coherents,.. etc. El problema es general i passa en qualsevol procediment intern que es vol passar a públic.

**Comment by slromero-indra** [comment]
Hemos solucionado el problema con el código javascript y el multidioma. cuando podáis, habría que desplegar de nuevo.
