### ISSUE TITLE
Marcat de procediments pendents d'enviament a SIA

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#414]
- Hem detectat procediments que després de ser actualitzats no passen a pendents d'enviament. Hi ha alguna excepció a aquest criteri ?
- Cal revisar el següent cas:
 --> Procediment d'alta a SIA amb codi
 --> S'actualitza el procediment de manera que s'eliminen/canvien dades que ara fan que no compleixi amb els requeriments SIA.
 -- >Com es deixa l'estat SIA del procediment ? Crec que el més lògic seria donar-lo de baixa i anotar-lo a Advertències pendents.
- Finalment, quan s'actualitza la pestanya "Advertències pendents"? Únicament després d'un bolcat complet o també hi passen els procediments pendents que una vegada sincronitzats amb SIA, no s'han pogut bolcar ?

**Comment by slromero-indra** [comment]
Hem detectat procediments que després de ser actualitzats no passen a pendents d'enviament. Hi ha alguna excepció a aquest criteri ?
```
Cuando se actualiza un procedimiento, se introduce en la tabla de pendientes si cumple lo siguiente:
 - El procedimiento es visible. 
 - El órgano resolutorio y sus padres son todos visibles.
 - El órgano resolutorio o uno de sus padres están en la tabla SiaUA (es decir, está introducido como una entidad raíz).

Puede que entre en la lista de pendientes pero con la marca de datos incompletos (advertencias pendientes).
```
Cal revisar el següent cas:
--> Procediment d'alta a SIA amb codi
--> S'actualitza el procediment de manera que s'eliminen/canvien dades que ara fan que no compleixi amb els requeriments SIA.
-- >Com es deixa l'estat SIA del procediment ? Crec que el més lògic seria donar-lo de baixa i anotar-lo a Advertències pendents.
` Cuando cambia un procedimiento, existen 4 estados contemplados por SIA (Alta, Baja, Modificación y Reactivación). Los 4 estados están implementados y se envían hacia SIA, habéis visto algún caso que no se produzca una baja?.`

Finalment, quan s'actualitza la pestanya "Advertències pendents"? Únicament després d'un bolcat complet o també hi passen els procediments pendents que una vegada sincronitzats amb SIA, no s'han pogut bolcar ?
 ` Las advertencias completas se actualiza tanto en el volcado completo como en el día a día.`

**Comment by sgelabert-dgtic** [comment]
Corregiu-me si m'equivoc amb aquest escenari ens deixam casos defora. Us pos un exemple:
- Suposeu un procediment integrat amb SIA amb estat alta
- El procediment se li canvia l'organ resolutori per un altre que està intern o no té codi DIR3 (els pares tampoc)
Amb el funcionament que descriviu, el procediment es despublicaria de la nostra Seu Electrònica però seguiria d'alta a SIA.

**Comment by slromero-indra** [comment]
Buenas, te comento aquí el resultado del problema que comentas y dos posibles problemas más que hemos detectado debido al cambio de órgano resolutorio.

**Problema 1.**
Los pasos que comentas. Si no es enviable SIA (es interno o no tiene código DIR3), si ya está dado de alta en SIA, se envía una baja.

**Problema 2.**
Un procedimiento dado de Alta se le cambia el órgano resolutorio (a uno sin código DIR3) manteniendo la entidad raíz. Por ejemplo, pensemos que se genera una nueva consellería de 'Educación infantil' y se le pasa procedimientos de otras consellerías. Aquí se producen 2 posibilidades:
 - La consellería nueva de 'Educación Infantil' está marcado como interna. En ese caso, NO sería enviable SIA y se marcaría como baja.
  - La consellería nueva de 'Educación Infantil' NO está marcado como interna (es pública). Aquí se produce un caso en que como no hay código DIR3 buscará el código del predecesor con el código DIR3 y, en este caso, sería la raíz. Se producirá un error porque SIA no permite que el id departamento y el id de la entidad raíz sean el mismo. 

**Problema 3.**
Un procedimiento dado de Alta se le cambia el órgano resolutorio y se mueve fuera de la entidad raíz.  Supongamos que movemos un procedimiento que cuelga de GIB a la APB. Aquí se producen 2 posibilidades:
- No existe ninguna entidad raíz (en este caso, la APB no ha sido mapeada como entidad raíz). Se -
 marcará como NO enviable hacia SIA. Se tendría que enviar una baja pero no se enviará porque no hay una entidad raíz asociada a la petición SIA. En este caso se provocará una incongruencia entre los datos SIA y los datos ROLSAC.
- Si existe entidad raíz (en este caso, la APB ha sido mapeada como entidad raíz). Se produce un error si se mantiene el código SIA porque es único y va asociado a la entidad raíz de GIB. 

Para evitar ambos errores, deberíamos realizar una comprobación extra en el back de procedimientos (y servicios) y bloquear cualquier cambio de entidad raíz cuando ya se tiene código SIA.

**Comment by sgelabert-dgtic** [comment]
Respecte al **problema 1 i 2** si no record malament amb en David quedàrem que el procediment anava a la borsa de "S'haurien d'enviar però hi manquen dades" sense actualitzar l'estat a SIA. Podeu confirmar-me aquest aspecte?

**Comment by slromero-indra** [comment]
Buenas, el problema 1, si se produce el problema que indicas en tu comentario ( 'S'actualitza el procediment de manera que s'eliminen/canvien dades que ara fan que no compleixi amb els requeriments SIA.') sí se iría como comentas a la pestaña de 'Advertencias pendientes' ("S'haurien d'enviar però hi manquen dades").

Respecto al problema 2, depende hacia que UA se mueva.   
- Si la nueva UA no es visible, se mandará una baja.
- Si la nueva UA no tiene DIR3 y su único predecesor con DIR3 es la entidad raíz, debería dar un mensaje (y pasar a la pestaña de advertencias pendientes) que el id centro no puede coincidir con la entidad raíz (el propio servicio web provoca un error por su parte avisando que no es posible que coincidan el id centro y la entidad raíz). Esta comprobación controlada aún no esta activa. 
- Si la nueva UA si tiene DIR3, se mandará una modificación.

**Comment by slromero-indra** [comment]
Vamos a proceder a realizar los siguientes cambios como se ha comentado por email:

- Incluir un bloquea de restricción cuando se cambia de entidad raíz (sólo cuando está de alta en SIA y sólo se aplica a la UA órgano resolutorio).
- Incluir una condición para que el id centro y la entidad raíz no sean la misma. En caso de serlo, aparecerán en la pestaña 'Advertencias pendientes'.

**Comment by slromero-indra** [comment]
Faltaba este cambio también comentado por email:
- Añadimos un campo extra con la información de la entidad raíz para poder obtener el usuario / password para la conexión con SIA cuando se borra un procedimiento.

**Comment by sgelabert-dgtic** [comment]
Controlar el canvi de visibilitat de les normatives relacionades amb el procediment respecte del procés d'integració amb SIA.

**Comment by slromero-indra** [comment]
Controlado el cambio de visibilidad en la función cumple datos. Es decir, si ninguno de las normativas asociadas a un procedimiento es no público o no tiene 'tipo sia', entonces el procedimiento pasará a la pestaña 'Advertencias pendientes'.

Respecto a los 23 procedimientos de la consulta, se deberán marcar como baja en la aplicación SIA.
