### ISSUE TITLE
Adaptacions nou servidor traductor automàtic

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#415]
Es sol·licita revisar el servei de traducció automàtica integrat a ROLSAC s'adapti als canvis del nou servidor de traducció (scatwnt2).
Es remet informació complementària per correu

**Comment by rsanz-indra** [comment]
Según el histórico de correos, entendemos que se debería hacer como comentan un tratamiento especial para los campos de tipo html, diferenciándolos de los de tipo texto plano (o bien enviarlos todos como tipo html/xml).

Este tratamiento, según la operativa de su servicio de traducción, entendemos que deberíamos enviar este tipo de campos como xml (evitando en caso necesario enviar los tags de <html></html> ya que “generan más ruido” en la respuesta.

Una de las soluciones podría ser la siguiente, sabiendo que de antemano ese campo puede contener html:
1)	Tenemos campo que puede tener un contenido html (bien metido entre tags o no):  contenido_campo
2)	Enviar metiendo el contenido entre tags: <traduccion>contenido_campo</traduccion>
3)	Recibimos respuesta: <?xml version="1.0" encoding="UTF-8"?> < traduccion >contenido_campo_traducido</ traduccion >
4)	Quitamos tags quedandonos con contenido_campo_traducido

Quedamos a la espera de ver que solución se quiere adoptar

**Comment by rsanz-indra** [comment]
Esperamos a tener acceso a los servidores de traducción para poder evaluar la solución a adoptar.

**Comment by slromero-indra** [comment]
Buenas,
tenemos unas modificaciones que deberían solventar el problema, comitamos los cambios en la rama 1.5?

**Comment by rsanz-indra** [comment]
Hemos estado realizando pruebas con el SoapUI contra el nuevo servidor de traducción y ya creemos tener la solución clara. Esperamos terminar de implementar y validar durante el lunes y os pasamos para que probéis.

**Comment by slromero-indra** [comment]
Buenas hemos actualizado las ramas 1.5 y 1.6 con los cambios. 
Hemos probado con ambos servidores y en nuestras pruebas, el resultado ha sido satisfactorio con ambos.

**Comment by sgelabert-dgtic** [comment]
Les proves han anat bé.
Quan pogueu cal actualitzar la propietat:
`es.caib.rolsac.integracion.traductor.servidor=scatwnt2.caib.es:8080`
