### ISSUE TITLE
Bug alta personal 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#416]
Hi ha un bug en la creació de Persones. Des de la pantalla i a nivell de log del servidor d'aplicacions no dona cap error però les dades no s'emmagatzemen a la BBDD

**Comment by slromero-indra** [comment]
No hemos sido capaces de replicar el error. Necesitamos que nos paséis las condiciones en las que se produce el error.

Lo que si se ha observado son dos errores:
 - En el log.error no se pasaba la excepción.
 - Sólo se capturaba el error DelegateException, si se produce otro tipo de excepción, esta no se captura. Eso podría explicar el problema, que al producirse un error no controlado de tipo NO DelegateException, este no sea capturado por el back (y por tanto no se vería en los logs) y la interfaz tampoco se enteraría.

Por favor, repetir las pruebas con esta versión que si captura las excepciones no controladas de tipo NO DelegateException.

**Comment by sgelabert-dgtic** [comment]
Seguim amb "l'error" sobre l'entorn de PROducció i PREproducció.
Us envii per correu les dades de l'usuari que intentam donar d'alta per si voleu fer proves. 
He debugat l'aplicació i no dóna cap errada a nivell d'aplicació, però les dades no s'emmagatzemen a BBDD.

Pedeu donar-li una ulla? Gràcies

**Comment by slromero-indra** [comment]
Estamos intentando replicar y cuesta bastante ver dónde puede encontrarse el problema. Hemos observado que en el código se puede introducir un espacio y podría crear un malentendido, podéis confirmarme que esta consulta no devuelve ningún resultado?

```
select * 
 from rsc_person
 where per_userna like 'u139366%' or lower(per_nombre) like 'alb%ma%rosi%l%' or lower(per_email) like '%amrosillo%';
``` 

Cuando termina de pulsar el botón de guardar,  se observa como la página se refresca? Por consola de javascript muestra algún error?

**Comment by sgelabert-dgtic** [comment]
La consulta restorna un resultat [export_bug_usuari.xlsx](https://github.com/GovernIB/rolsac/files/1440731/export_bug_usuari.xlsx).
Efectivament l'error pareix prové del espai posterior... Si és així caldria fer un trim del codi d'usuari
