### ISSUE TITLE
Actualització documentació: Guia Ràpida d'Intal·lació ROLSAC

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#419]
Es sol·licita actualitzar el document "Guia Ràpida d'Instal·lació" de ROLSAC. El document ha de tenir en compte la compilació i desplegament de ROLSAC tant en l'entorn CAIB (Jboss5.2-EAP+seycon) com en terceres administracions (Jboss 5.1+autenticació per BBDD)
Cal versionar el document nou document com:
/ROLSAC-1.5/doc/1.5/ROLSAC-GUIA_RAPIDA_INSTAL·LACIO-v1.5.odt
/ROLSAC-1.5/doc/1.5/pdf/ROLSAC-GUIA_RAPIDA_INSTAL·LACIO-v1.5.pdf

La documentació s'ha de generar en català.

**Comment by slromero-indra** [comment]
El documento se encuentra actualizado en las ramas rolsac-1.5 y rolsac-1.6. 

Respecto al jboss-5.1, se ha realizado las modificaciones básicas para conseguir arrancar la aplicación hasta el login (no se ha comprobado si toda la funcionalidad de la aplicación está correcta, a la espera de la decisión de la issue https://github.com/GovernIB/rolsac/issues/420).
