### ISSUE TITLE
Testeig ROLSAC 1.5.6 sobre Jboss 5.1

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#420]
Es sol·licita efectuar proves de desplegament de ROLSAC 1.5.6 sobre Jboss 5.1.
El·laborar informe amb els errors detectats i la solució proposada tenint en compte que s'ha de mantenir la compatibilitat amb Jboss 5.2-EAP de l'entorn CAIB.
Estimar en hores el cost de l'adaptació.

**Comment by sgelabert-dgtic** [comment]
Es cancel·len les proves pendent de verificar si es possible la distribució del Jboss-5.2-EAP

**Comment by slromero-indra** [comment]
En caso de volver a retomar el tema, se tendrá que actualizar el documento de instalación.
