### ISSUE TITLE
Bug noms d'arxius massa grans

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#421]
Es produeixen errors al intentar emmagatzemar noms d'arxiu massa grans:
`ORA-12899: el valor es demasiado grande para la columna "ROLSAC"."RSC_ARCHIV"."ARC_NOMBRE" (real: 135, mÃ¡ximo: 128)`
Es sol·licita controlar per aplicació la longitud de nom de l'arxiu per evitar el bug i informant a l'usuari abans dels desat de la informació.

**Comment by slromero-indra** [comment]
Se ha incluido en los back de procedimientos, fichas y trámites un control sobre los archivos para que cuando se produzca un tamaño del nombre del fichero muy largo devuelva un error.

En la rama 1.6 se incluye el control sobre las normativas y los servicios.

**Comment by sgelabert-dgtic** [comment]
Veig que salta el control però la comprovació es fa en el servidor a nivell de controlador. Això provoca que s'hagi d'esperar a que es faci l'upload de l'arxiu en el servidor perquè salti el missatge.
Seria més àgil fer la comprovació de la longitud de la cadena en un js de client.
