### ISSUE TITLE
Revisar els scripts de creació d'esquema de BBDD

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#422]
Ens comuniquen que els scripts de creació de l'schema des de zero `rolsac_create_schema.sql` incorporats en les versions 1.4 i 1.5 no estan actualitzats.
En principi la generació d'aquest scripts es feia a partir de la tasca ANT `build-db.xml` i la definició del model de dades amb Hibernate. Cal revisar-ho.

**Comment by slromero-indra** [comment]
Hemos actualizado el fichero tanto en rolsac-1.5 como rolsac-1.6 (se ha obviado actualizar en rolsac-1.4, si necesitáis que lo cambiemos, avisad). Hemos realizado prueba básicas, cargando en un schema vacío el create-schema-rolsac y cargando datos básicos (UA, traducción UA y Usuario) y revisando por encima el funcionamiento (hay cosas que fallan ya que no están todos los datos necesarios).

¿Queréis que hagamos más trabajo revisando en profundidad si se genera todo correctamente? Si continuamos, la idea sería ver si intentamos cargar la mínima información necesaria (dejando por ejemplo normativas, procedimientos y fichas vacíos) o bien lo contrario (ver que cargando los datos de un schema completa todo funciona correctamente e igual al original).

**Comment by slromero-indra** [comment]
Se ha incluido unos parámetros, comentado ya que por defecto está el SGBD Oracle, para la generación del documento. Además, se ha incluido, siguiendo el mismo esquema seguido en otras aplicaciones BIT, un fichero rolsac_create_data.sql con la información básica para arrancar la aplicación: 1 usuario, 1 UA, perfil y las relaciones entre ellas (además de la información sobre boletines).

Se ha añadido sentencias básicas (comentadas en el sql) para inicializar con la mínima información para generar normativas, procedimientos y fichas aunque toda la información podría ser introducida a través del menú de administración.
