### ISSUE TITLE
Bug API tractament caràcter especial

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#423]
Es detecta bug amb el tractament de caràcters especials introduits a partir de copy&pastes sobre camps de text pla com HTML (editor TinyMCE)
Adjunt log del servidor d'aplicacions [log.txt](https://github.com/GovernIB/rolsac/files/1457019/log.txt) i fitxer de test amb un codi especial que provoca l'error [hexaChar.txt](https://github.com/GovernIB/rolsac/files/1457020/hexaChar.txt)
Es sol·licita controlar l'error mitjançant la validació de XML abans de l'emmagatzematge de dades.

**Comment by slromero-indra** [comment]
Nos ponemos ya mismo con la tarea para tenerlo esta tarde solucionado.

**Comment by slromero-indra** [comment]
Estamos teniendo problemas para replicar el error. ¿Podéis dar más info del error que se produce? Da una alerta? Se produce un error 500 por log?

**Comment by sgelabert-dgtic** [comment]
Ho podeu provar intentant desar sense canvis la fitxa 2745358 de l'entorn de proves

**Comment by slromero-indra** [comment]
Gracias, revisamos y arreglamos el problema cuanto antes para poderlo comitear hoy, parece que ya hemos detectado el problema.

**Comment by slromero-indra** [comment]
Actualizado el método encargado de las comprobaciones de los caracteres no válidos. Desplegar en proves y, tras pulsar el botón de guardar, debería de permitirlo ya --> URL : http://caibter.indra.es/rolsacback/fitxainf/fitxainf.do?itemId=2724780
