### ISSUE TITLE
Actualització de documentació: Integració SIA

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#424]
Es sol·licita actualitzar el document "Integració SIA" de ROLSAC. El document ha de tenir en compte els darrers canvis introduïts en aquesta branca 1.5 (https://github.com/GovernIB/rolsac/issues/418, https://github.com/GovernIB/rolsac/issues/414, https://github.com/GovernIB/rolsac/issues/399) i la gestió de la multientitat del procés d'integració (https://github.com/GovernIB/rolsac/issues/407) 

La documentació s'ha de generar en català.

**Comment by sgelabert-dgtic** [comment]
S'adjunta document amb comentaris.
[ROLSAC-Integración-SIA-correccions.docx](https://github.com/GovernIB/rolsac/files/1550789/ROLSAC-Integracion-SIA-correccions.docx)
Tampoc veig que la documentació s'hagi generat en català.

**Comment by slromero-indra** [comment]
Acabamos de actualizar sólo los pdf (faltaba actualizarlos). 

Estamos buscando de donde se ha sacado el documento utilizado para realizar los comentarios, cuando puedas nos comentas si hay una ruta por actualizar o ha sido un pequeño malentendido. Los documentos actualizados son: 
 - ROLSAC/doc/1.5/ROLSAC-Integración-SIA.pdf (./pdf/ROLSAC-Integración-SIA.pdf)
 - ROLSAC/doc/1.6/ROLSAC-Integración-SIA.pdf (./pdf/ROLSAC-Integración-SIA.pdf)
