### ISSUE TITLE
Controlar la interpretació del codi HTML en el títol de procediment

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#425]
Se'ns ha notificat que un gestor de ROLSAC ha introduit codi HTML en el camp títol del procediment perquè aquest funcioni com enllaç. Això provoca que no es pugui accedir a l'edició del procediment des de les pestanyes de cercador o llistat de procediments.
En concret el codi introduit en el camp títol és el següent: `<p> <a href="http://www.caib.es/sacmicrofront/contenido.do?idsite=138&,cont=2936&,lang=ca&,campa=yes"> Tràmits </a></p>`
Es sol·licita no interpretar el codi HTML que prové del camp títol en les pestanyes llistat i cercador.
Efectuar el mateix control en fitxes informatives, UA, Normativa i Persones

**Comment by slromero-indra** [comment]
Buenas, hemos realizado las actualizaciones pertinentes en la rama 1.6.
