### ISSUE TITLE
Bug amb el tractament del caràcter %

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#428]
Se'ns notifica que el backoffice de ROLSAC no tracta bé el caràcter %. Pareix un problema de l'editor Tiny.
En /ROLSAC/moduls/back2/htdocs/js/detall_base.js i /ROLSAC/moduls/back2/htdocs/js/detall_base_n.js efectua un tractament especial per aquest càracter:
```
// TinyMCE, aún forzando a que escape a entidades numéricas, no contempla el caso del tanto por ciento %.
			// Toca hacerlo de forma explícita antes de codificar completamente la cadena con encodeURIComponent().
			if (typeof texto != 'undefined'){				
				texto = texto.replace(/%/g, "&#37;");
			} else {
				texto = "";
			}
```
El resultat es que a la Seu Electrònica no es presenta bé aquesta informació. Adjunt captura de pantalla:
![errorpercentatge](https://user-images.githubusercontent.com/17268396/38307635-9d0b6d90-3814-11e8-88e3-9500c565a038.jpg)

**Comment by slromero-indra** [comment]
Hemos revisado el código y en el caso de requisitos de un trámite, no pasa por tinymce sino que es un campo textarea. El texto de los campos (no sólo el de requisitos, sino el resto de campos también) de trámite no son parseados:
![imagen](https://user-images.githubusercontent.com/17451407/38631346-cfb1b65a-3db9-11e8-8614-db5c0b5428f5.png)

En seucaib:
![imagen](https://user-images.githubusercontent.com/17451407/38631370-de0eeea2-3db9-11e8-8765-b731c27e42f4.png)
http://caibter.indra.es/seucaib/ca/200/persones/tramites/tramite/2485274

Editando el requisito y cambiando &#37; por % tendría que solucionar el problema. Sino necesitamos que nos paséis el contenido del campo requisito de dicho trámite para replicar el problema.

**Comment by sgelabert-dgtic** [comment]
El problema apareix després de la traducció. Podeu veure un exemple amb el procediment 3270465 de l'entorn de DES:
http://sdevapplin5.caib.es:58080/rolsacback/catalegProcediments/catalegProcediments.do?itemId=3270465
http://sdevapplin5.caib.es:58080/seucaib/es/200/persones/tramites/tramite/3270465/ 
![image](https://user-images.githubusercontent.com/17268396/38660658-50bc0916-3e2e-11e8-9253-3283d6cb2aa0.png)

**Comment by dmadronal-indra** [comment]
buenas, hemos comiteado los cambios en la rama 1.7,  lo incluimos en la rama 1.6?
