### ISSUE TITLE
Bug eliminació de models de sol·licitud en els tràmits

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#429]
L'eliminació de models de sol·licitud en la pàgina de tràmits dóna error. Adjunt log [bug_model.txt](https://github.com/GovernIB/rolsac/files/1978777/bug_model.txt)
Podeu provar-ho sobre l'entorn de proves amb el procediment següent: https://appsproves.caib.es/rolsacback/catalegProcediments/catalegProcediments.do?itemId=3265288

**Comment by slromero-indra** [comment]
Revisamos la incidencia y os decimos algo en cuanto lo tengamos solucionado.

**Comment by sgelabert-dgtic** [comment]
Necessitem passar la correcció del bug dels models a producció, per tant, no hi pot haver actiu encara el tema dels serveis. Podeu tornar-ho a desactivar ?
