### ISSUE TITLE
Bug guardar procediment amb molts de documents

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#430]
A l'hora de eliminar la data de caducitat dóna el següent error:
![captura](https://user-images.githubusercontent.com/26536678/39694847-ec1baad8-51e8-11e8-8bc3-47e7ae68b58f.JPG)

Si elimino dos documents relacionats, no dóna error.
Podeu provar-ho sobre l'entorn de proves amb el procediment següent: https://appsproves.caib.es/rolsacback/catalegProcediments/catalegProcediments.do?itemId=3265394

**Comment by slromero-indra** [comment]
El problema se produce cuando el número de parámetros por POST es mayor al máximo valor por defecto. 

Para solucionarlo, existen dos maneras:
 - En el fichero properties-service.xml (en /jboss5/jboss-as/default/deploy) incluir donde ya están especificados las propiedades un parámetro extra para aumentar el MAX_COUNT de 512 a 1000:

```
 <mbean code="org.jboss.varia.property.SystemPropertiesService" 
	 name="jboss:type=Service,name=SystemProperties">

	<attribute name="Properties">
                  org.apache.tomcat.util.http.Parameters.MAX_COUNT=1000
         </attribute>

  </mbean>
```
- Rescribir el código para unificar parámetros y pasar los mismos valores pero en menos parámetros. Exigiría un coste bastante mayor.

Por lo que se ha observado, el problema es bastante complejo de replicarse (hay que aumentar bastante el tamaño de todos los parámetros, sobretodo el de documentos de un procedimiento).

**Comment by sgelabert-dgtic** [comment]
Ok, parlarem amb Sistemes a veure si ho podem ampliar

**Comment by sgelabert-dgtic** [comment]
Sistemes accepta augmentar el nombre de paràmtres post
