### ISSUE TITLE
Normalització Canals de Presentació Tràmit i Servei

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#432]
Es sol·licita modificar la pantalla de tràmits associats a procediments administratius i la pantalla de serveis administratius amb els següents canvis:
- A la pantalla de Tràmits associats a Proced. Adm, afegir checkboxs amb els canals de presentació : Presencial, Telemàtic
- A la pantalla de Serveis afegir checkboxs: Presencial, Telemàtic, Telefònic 
- En ambdós casos si es marca "Telemàtic" s'ha d'habilitar camps URL del tràmit i Identificador+Versió però ambdós han de ser mútuament excloents (no s'ha de permetre que s'emplenin els dos).
- Si es marca únicament "Telemàtic", el model de sol·licitud del tràmit deixar de ser obligatori.
- Revisar l'API de ROLSAC (SOAP i REST) perquè identifiqui que el tràmit és telemàtic per qualsevol dels dos camps (URL o Identificador+Versió)
- Revisar la indexació d'aquest camps a través de l'API de SOLR

**Comment by dmadronal-indra** [comment]
Comentado por teléfono:
- Si telemático está marcado, los campos de **_url_** o **_id+versión_** pasan a ser obligatorios (uno u otro deben estar rellenados)
- En SOLR por ahora solo se tendrá en cuenta el campo **_telemático_**.

**Comment by dmadronal-indra** [comment]
actualización:
- S'ha d'emplenar de manera obligatòria com a mínim un valor en els checks que fan referència als canals de presentació (Per procediments--> presencial/telemàtic || Per serveis --> presencial/telemàtic/telefònic)
- La migració considerarà com a canal telemàtic si té emplenat URL o bé els camps Identificador+Versió.
- De moment, noltros DGDT ens encarregarem de la depuració de dades i de l'emplenament dels checkbox. 
- Si ens interessa es pot passar els canvis sobre la branca 1.7 de ROLSAC i deixar la 1.6.1 únicament amb els canvis d'inventari i adequació MAVEN

**Comment by dmadronal-indra** [comment]
Buenas, se han realizado las modificaciones en la rama 1.7 ¿lo podeis validar?
