### ISSUE TITLE
Bug a l'hora eliminar la UA d'un usuari gestor 

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#433]
Hola,
Quan un usuari gestor està vinculat a vàries UAs, el pots desvincular de totes elles menys una. Per exemple, si un usuari està vinculat en 3 UAs, el pots desvincular de dues, però de la darrera no ho permet. El mateix passa si està vinculat només amb una UA. Quan el desvincules d'aquesta, pots guardar però quan tornes a cercar el mateix usuari per editar-lo, torna a aparèixer la UA. Adjunt captures.
1- Desvincular l'usuari de la UA
![captura1](https://user-images.githubusercontent.com/26536678/42017707-411dfa3c-7ab0-11e8-8268-9109741b8d0a.JPG)

2- Guardar
![captura2](https://user-images.githubusercontent.com/26536678/42017709-4812930c-7ab0-11e8-839a-22c0be95a008.JPG)

3- Missatge de que s'ha guardat correctament
![captura3](https://user-images.githubusercontent.com/26536678/42017726-57cc2830-7ab0-11e8-93b6-91eb31c2f206.JPG)

4- Quan tornes a cercar l'usuari per editar-lo, torna a aparèixer la UA
![captura4](https://user-images.githubusercontent.com/26536678/42017747-6ab7841c-7ab0-11e8-93a9-f895336527da.JPG)

**Comment by bgarcia-dgtic** [comment]
També passa el mateix amb l'apartat "PERFILS GESTOR RELACIONATS". No deixa desvincular-lo.

**Comment by slromero-indra** [comment]
Actualizado el controlador permitiendo borrar si se desea todas las relaciones de un usuario.

**Comment by bgarcia-dgtic** [comment]
Bon dia,
He fet proves de desvincular l'usuari de les UAs administratives i funciona correctament. Però a l'hora de desvincular l'usuari dels "PERFILS GESTOR RELACIONATS", no ho fa. Per exemple, si un usuari té els perfils "SUPERVISOR" i "SYSTEM" i intentes desvincular-los, et permet guardar però els canvis no es guarden correctament. Quan tornes a consultar el mateix usuari, tornen a apareixen els perfils que hi havia.

**Comment by slromero-indra** [comment]
Actualizado para que los perfiles gestor relacionados permita actualizarse aún estando vacíos . Hay que tener en cuenta que usuarios sin UAs ni perfiles gestores relacionados provocará graves errrores de comportamiento en la aplicación (es más, si no tienen ni perfil ni UAs, tal vez sería más lógico borrarlo).

**Comment by bgarcia-dgtic** [comment]
Ens interessa mantenir als usuaris perquè d'aquesta forma seguiran apareixent a les auditories.
