### ISSUE TITLE
Reorganització de projectes GitHub

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#435]
Es sol·licita reorganitzar els següents projectes de projectes GitHub:

GUSITE | Borrar elementos rama master y añadir  readme
-- | --
ROLSAC | Borrar elementos rama master y añadir  readme
SISTRA (Sistra1) | Borrar elementos rama master y añadir  readme
SISTRA-PLUGINS (Para Sistra1) | Borrar elementos rama master y añadir  readme
SISTRA2 | Crear Rama para versión 1.0. Borrar elementos rama master y  añadir readme
LOGINIB | Crear Rama para versión 1.0. Borrar Rama  pluginsib-login-1.0

**Comment by dmadronal-indra** [comment]
buenas, hemos procedido a reorganizar los difierentes proyectos.
