### ISSUE TITLE
Bub integració de procediments i serveis amb SIA

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#436]
Hola,
Hem detectat un mal funcionament a l'hora d'obtenir el codi SIA dels procediments i dels serveis.
Quan es crea un procediment amb l'estat "públic" i la data de publicació posterior a la data de creació, no es genera el codi SIA una vegada vençut la data de publicació. Es a dir, el procediment no s'incorpora a la llista de pendents d'enviar a SIA.

No obstant, amb els serveis la problemàtica és diferent. Quan es crea un servei amb l'estat "públic" i la data de publicació posterior a la data de creació, en aquest cas sí que es genera el codi SIA. Però es genera abans de que venci la data de publicació. Cosa que tampoc hauria de ser així.

**Comment by slromero-indra** [comment]
Buenas, hemos actualizado el proyecto para que envíe los procedimientos/servicios una vez pase a ser pública. Se enviará a pendientes aprovechando la tarea que se ejecuta periódicamente: 
 - Primero revisa si hay procedimientos/servicios si ya están publicos y no se han enviado a SIA (o bien si se caducan, se envía una baja),  y los manda a la pila de pendientes (o a la pila de todos los datos correctos o bien a la que le falta algún dato por cumplimentar).
 - Enviará los datos hacia SIA de la pila de pendientes que cumpla todos los datos.
¿Cada cuanto tenéis activo la ejecución de la tarea? Lo marca el valor en el jboss-service.xml de es.caib.rolsac.sia.jobpendientes.

Respecto a los servicios, ya está actualizado para que no envié el servicio si aun no está publicado.

**Comment by bgarcia-dgtic** [comment]
El valor de la propietat a producció és es.caib.rolsac.sia.jobpendientes=0 0 10 * * ?

**Comment by slromero-indra** [comment]
Se recomienda poner un horario que no coincida con el marco laboral de acceso a rolsac (que debería ser entre las 8:00 y las 19:00), o bien a primera hora de la mañana o bien por la noche (se recomienda por la mañana, sobre las 2 o las 3 por ejemplo).
