### ISSUE TITLE
Restricció alta/edició de normativa per usuari

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#437]
Es sol·licita restringir l'alta/edició de normativa a determinats usuaris amb rol RSC_SUPER.
Es proposa:
- Habilitar un check a nivell d'usuari per poder introduir/editar normativa
- Bloquejar el desat de canvis en l'alta i/o edició de normativa i traspàs de normativa del BOIB si l'usuari no disposa del permís anterior
- Analitzar les implicacions d'aquest bloqueig de desat amb el restriccions de desat definides per UA

**Comment by dmadronal-indra** [comment]
Bones,
Entenem que també s'ha de bloquetjar l'eliminació de normatives.
Per altra banda, asignam per defecte que tothom pugui desar, o que per defecte estigui restringit?

**Comment by sgelabert-dgtic** [comment]
Efectivament l'eliminació també ha d'estar bloquejada.
Respecte al bloqueig o no per defecte, el comportament és diferent per la CAIB que pel externs.
Cas CAIB --> Restringit per defecte
Cas instal·lació externa --> Obert per defecte
Ho externalitzem a una propietat de sistema es.caib.rolsac.usuari.gestioNormativa=(S o N) ?

**Comment by dmadronal-indra** [comment]
Buenas, 
ok, crearemos la propiedad para que al añadir un usuario el check este marcado por defecto, en caso de que sea S.
por otro lado, Entendemos que también habrá que bloquear que se puedan añadir/eliminar documentos, unidades administrativas y afectaciones relacionadas con la normativa.
¿Nos lo podéis confirmar?

**Comment by sgelabert-dgtic** [comment]
Efectivament, tampoc s'ha de permetre la modificació de cap dels elements relacionats amb la normativa.

**Comment by dmadronal-indra** [comment]
Bones,
hem pujat una actualització, ¿ho podeu revisar?

**Comment by episano-dgtic** [comment]
He visto que para los usuarios que tienen permisos de gestión de normativa una vez asignada la tienen asignada a una unidad orgánica no se la permite cambiar por otra, ó indicar otra unidad orgánica.
![normativa](https://user-images.githubusercontent.com/17451683/48553113-f2dec380-e8da-11e8-83e3-7d125a3ea6d9.gif)
.

**Comment by dmadronal-indra** [comment]
Según lo comentado parece una casuística que solo aplica con el rol super, revisaremos a que se debe este comportamiento y os añadimos un comentario, para ver como abordarlo.

**Comment by dmadronal-indra** [comment]
Buenas,
Por lo que hemos visto, el rol super no tenia permisos para realizar esta asignación. 
Hemos procedido a otorgarle permisos a este rol. 

¿Podeis verificarlo?
