### ISSUE TITLE
Camps obligatoris i mal funcionament dels canals de presentació

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#438]
Hola,
Hem detectat vàries coses:
1- En els tràmits dels procediments, falta marcar com a camps obligatoris: "Nom del tràmit", "Requisits" i "Termini màxim"

3- Quan es crea un nou Servei, falta marcar els camps obligatoris: "Nom del servei", "Objecte" i "Destinataris"

2- És referent als canals de presentació. Quan un tramit d'inici d'un procediment té com a canals de presentació marcat només el "Telemàtic" (s'ha emplenat el camp url), et deixa guardar el tràmit sense cap problema. Però si es vol posar el procediment com a públic, dóna l'error "Es obligatori crear un model de sol.licitiud per al tràmit d'inicialització."

**Comment by dmadronal-indra** [comment]
Lo revisamos.

**Comment by dmadronal-indra** [comment]
Buenas, referente al último punto, entendemos que, para mantener la coherencia, se deberá verificar también al guardar el tramite de inicio lo siguiente:
- Si no es presencial, se permitirá eliminar el modelo de solicitud
- Si es presencial, no se permitira eliminar el modelo.

**Comment by bgarcia-dgtic** [comment]
Efectivament, si el tràmit no es presencial, t'ha de permetre eliminar el model de sol·licitud. I si és presencial el model de sol·licitud ha de ser obligatori.

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos procedido a realizar varios cambios en la aplicación.
¿Lo podéis validar?
