### ISSUE TITLE
No se eliminan las unidades orgánicas pese a que salga un mensaje de aviso indicando que se ha eliminado. 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#440]
No se eliminan las unidades orgánicas pese a que salga un mensaje de aviso indicando que se ha eliminado. 
![eliminacion](https://user-images.githubusercontent.com/17451683/48346948-0bea3900-e67d-11e8-94e6-9b502393aa45.gif)

**Comment by dmadronal-indra** [comment]
Buenas, hemos realizado una actualización para solventar este problema, lo podeis verificar?
