### ISSUE TITLE
No se pueden eliminar directamente las fichas si estas tienen documentos relacionados

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#441]
No se pueden eliminar directamente las fichas si estas tienen documentos relacionados. Sale un mensaje
"no se ha podido realizar"
![eliminacio_fichas](https://user-images.githubusercontent.com/17451683/48349040-5c649500-e683-11e8-8a02-f1c928f7ec5f.gif)

Si previamente se eliminan los anexos, se elimina. No debería ser así. Debe poderse eliminar directamente sin eliminar particularmente los annexos, previo el aviso de seguridad (Está seguro de querer eliminar esta ficha?) , tal y como ocurre actualmente. 
![aviso eliminacion ficha](https://user-images.githubusercontent.com/17451683/48349152-b8c7b480-e683-11e8-9a80-ed043077deb5.gif)

**Comment by dmadronal-indra** [comment]
Buenas hemos actualizado la aplicación ¿lo podeis revisar?
