### ISSUE TITLE
En la traspaso del boib de normativa no se añade la url de de acceso de la normativa ni en catalán ni en castellano

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#442]
En la traspaso del boib de normativa no se añade la url de de acceso de la normativa (Enllaç a la norma) ni en catalán ni en castellano.

**Comment by dmadronal-indra** [comment]
buenas, 
¿podeis facilitarnos más información? estamos tratando de replicar el problema, pero se nos debe escapar algo porque no lo conseguimos. Hemos probado en la versión 1.6 y en la 1.7 y en ambos casos, si buscamos una normativa en el buscador de traspaso del boib, al seleccionarla se rellena la url de acceso, tanto en castellano como en catalán.
![imagen](https://user-images.githubusercontent.com/17270582/50210598-d7058c00-0376-11e9-81c7-94ec9df9ddaf.png)

¿Podeis indicarnos como reproducirlo?

**Comment by episano-dgtic** [comment]
Tras vuestro comentario.. lo he vuelto a probar y he visto que en producción funciona pero en pruebas no. Estamos investigando si es un problema configuración pruebas o algun cambio del boib en pruebas.
