### ISSUE TITLE
Afegir funcionalitats a l'API Rest

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#443]
Afegir dues funcionalitats a l'API Rest:

1- Afegir a nivell de tràmit la informació dels canals de tramitació permesos (electrònic / presencial).
2- Afegir una funció nova per obtenir el DIR3 associat a una UA (DIR3 associat a la UA o als seus antecessors). Podria situar-se en UAService

**Comment by dmadronal-indra** [comment]
buenas hemos actualizado la aplicación, ¿Lo podeis validar?
