### ISSUE TITLE
Problemes a l'hora de cercar personal per codi d'usuari xYYYYYYYx

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#445]
A l'apartat "Personal", a l'hora de cercar usuari per codi d'usuari tipus xYYYYYYYYx, no et permet ja que la màscara és del tipus xYYYYYY.
Exemple, si vull cercar l'usuari "e43044455r", només em permet introduir el codi "e430444"

**Comment by dmadronal-indra** [comment]
Lo revisamos

**Comment by dmadronal-indra** [comment]
Buenas, hemos realizado un cambio, ¿lo podeis validar?
