### ISSUE TITLE
Adaptació API-Rest Servei de Procediments/Serveis Administratius

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#446]
Es sol·licita revisar el tipus de retorn de les operacions /procedimientos/{codigo} i /procedimientos perquè no es converteixi a objecte les propietats llista d'un únic element. Revisar també si aquesta casuística es replica en la resta de serveis oferits per l'API, especialment en els serveis administratius /servicios/{codigo} i /servicios
Per altra banda, es sol·licita incorporar al filtre de les operacions de procediments i serveis administratius la possibilitat de retornar una llista de procediments/serveis que depenen d'una UA i descendents. A més incorporar una operació de cerca textual sobre el títol de procediment/servei perquè es pugui emprar com cerca predictiva per les aplicacions consumidores de l'API.

**Comment by dmadronal-indra** [comment]
Buenos dias,
Hemos actualizado la aplicación con los últimos cambios, ¿lo podeis validar?

**Comment by bgarcia-dgtic** [comment]
Hola,
Referent als filtres "buscarEnDescendientesUA" i "titulo", he comprovat que funcionen correctament. No obstant, al swagger-ui no apareix com a opcions per filtrar tant als procediments com als serveis. Adjunt captures de pantalles.

Procediments.
![procediments](https://user-images.githubusercontent.com/26536678/59026670-502a6a00-8857-11e9-91e8-f209509ca7b8.JPG)

Serveis.
![serveis](https://user-images.githubusercontent.com/26536678/59026671-502a6a00-8857-11e9-809e-db0dfd3e8e05.JPG)

**Comment by dmadronal-indra** [comment]
Buenos días,
¿Habeis realizado un clean del proyecto antes de relizar el build?  Hemos revisado el código y os debería aparecer

**Comment by bgarcia-dgtic** [comment]
Efectivament, faltava realitzar el clean.

**Comment by bgarcia-dgtic** [comment]
Hola,
Es sol·licita incorporar al filtre de les operacions de procediments i serveis administratius la possibilitat de retornar una llista de procediments/serveis que depenen d'una UA i descendents a través del codi DIR3 de la UA.

**Comment by sgelabert-dgtic** [comment]
Pareix que el filtre per estat SIA {"codigoUA":"1","buscarEnDescendientesUA":"1","estadoSia":"1"} de l'operació "Lista los procedimientos" no funciona correctament

**Comment by dmadronal-indra** [comment]
Buenas, estadoSia debe ser un valor que se corresponda con los de la BBDD, actualmente puede ser A o B. Hemos probado con estos valores y funciona. ¿Os sigue fallando aplicando los filtros de esta manera?

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la aplicación para contemplar el nuevo filtro por código dir3. 
además hemos mejorado los mensajes descriptivos del swagger para los filtros de procedimientos y servicios.
