### ISSUE TITLE
Anàlisi incorporació procediments/serveis interns

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#447]
Es sol·licita analitzar la incorporació de procediments/serveis interns i comuns segons terminologia SIA. Es proposa el següent esquema de funcionament:
**1.-Procediment.-interns-específics i Serveis-interns-específics** 
- Afegir a ROLSAC un públic objectiu nou "Empleat públic" per a procediments i serveis administratius
- La selecció de "Empleat públic" serà excloent amb la resta de públic objectius (ciutadà, empresa i administració)
- La selecció de "Empleat públic" evitarà la publicació del procediment o servei a la Seu Electrònica
- La selecció de "Empleat públic" provocarà l'enviament a SIA del procediment o servei com intern-específic
- Si a SIA el camp Destinatari (ciudadano, empresa, administración) és obligatori per a procediments o serveis interns, s'enviarà com a "Administración".(Es confirmarà amb Madrid aquest aspecte)

**2.-Procediment.-Comú i Serveis-Comú (amb independència de si són interns/externs)**
- No hi haurà un camp especial per marcar el procediment o servei com a comú, simplement es posarà com a "Òrgan competent per resoldre", la unitat administrativa (UA) fictícia "El conseller o consellera competent en la matèria"
- La selecció de "El conseller o consellera competent en la matèria" classificarà el servei o procediment com a comú a SIA i determinarà si es intern o extern a partir del públic objectiu (veure punt 1) i així ho enviarà a SIA
- Els camps òrgan responsable i nom responsable no es sincronitza amb SIA, de moment i per no introduir casuístiques ho deixaria així.
- En l'enviament a SIA d'aquests procediments/serveis no s'informaran els camps "Consejería / Departamento" ni  "Centro Directivo"
- Un usuari només podrà assignar la UA  "El conseller o consellera competent en la matèria" com a  "Òrgan competent per resoldre" si la té configurada des del menú Usuaris

En relació amb els comuns es consultarà amb Madrid els següents aspectes: 
- Disponibilitat del canvi en l'obligatorietat del camp Centro Directivo sobre l'API d'integració amb SIA a l'entorn de PREproducció
- Documentació d'integració sobre la nova interfície.
- Previsió de la posta en producció del canvi aplicats sobre el frontal SIA de PREproducció

**Comment by sgelabert-dgtic** [comment]
Segons el frontal de SIA és obligatori la selecció del procediment comú a partir d'una llista tancada de procediments SIA. 
![image](https://user-images.githubusercontent.com/17268396/53003964-735c1580-3430-11e9-9ff1-cb97e872f669.png)
Es sol·licita analitzar la interfície WS per l'alta de procediments/serveis comuns tenint en compte que aquest camp procediments és obligatoria

**Comment by sgelabert-dgtic** [comment]
Un altre aspecte a tenir en compte a l'anàlisi és que en els Serveis Administratius, no tenim òrgan competent per resoldre, només òrgan tramitador. Entenc que en aquest cas no podríem fer servir "el conseller/a competent en la matèria"... 
En l'estimació de la tasca #407 s'indicava  "_Cuando es de tipo servicio, según el documento de especificación de conexión con SIA, el campo ‘UNIDADGESTORATRAMITE ‘ no deberá ser enviado_"

**Comment by dmadronal-indra** [comment]
Buenas, hemos revisado estos temas,
1.  Según la documentación de SIA, el campo procedimiento parece ser usado a modo de plantilla (aunque no se especifica directamente), el cual, al indicar un procedimiento, rellena los campos automáticamente, y a posteriori se pueden modificar todos los campos excepto “Denominación” y “Descripción”. A nivel del API, este campo es inexistente, de hecho, hemos realizado diversas pruebas y hemos podido crear procedimientos comunes, alterando la propiedad ESCOMUN, y no nos ha dado problemas. 
En este punto hemos estado buscando de donde proceden los procedimientos "plantilla" que se muestran en el desplegable, pero no los hemos localizado. Sería conveniente enviar una consulta a SIA para aclarar de donde proceden estos procedimientos, y si para realizar el alta de un procedimiento/servicio común a través del api es necesario enviar determinadas descripciones / Denominaciones. A priori en el api únicamente se especifica que, en el alta, estos campos son obligatorios.

2. Referente al campo UNIDADGESTORATRAMITE, según la definición del api de SIA, para el caso de los servicios es un campo opcional, y actualmente en ROLSAC no está contemplado su correspondencia  "òrgan competent per resoldre"  A priori la opción que parece más adecuada es Añadir un checkbox o similar que indique si un servicio es común o no. ¿Os parece adecuado?

**Comment by sgelabert-dgtic** [comment]
El MINHAP informa que els procediment/serveis comuns estan en procés de revisió. Ens recomanen no fer-ne ús i donar-los d'alta com a procediments/serveis específics sense òrgan destí.
Podeu canviar l'abast del document d'estimació per deixar els comuns defora ?

**Comment by sgelabert-dgtic** [comment]
Hem rebut l'OK de l'OAE. Podeu començar el desenvolupament per la incorporació dels procediments i serveis interns segons el document d'anàlisi.
De moment, no tractem els procediments comuns

**Comment by episano-dgtic** [comment]
La parte de procedimientos internos parece que va bien, sólo una puntulización. En la sede si conozco el código de un procedimiento "empleado público" puedo visualizarlo. 

Ejemplo: https://dev.caib.es/seucaib/ca/200/persones/tramites/tramite/3285795

**Comment by dmadronal-indra** [comment]
Este tema se ha tratado en la sede: issue #4546

**Comment by bgarcia-dgtic** [comment]
Hola,
Els procediments interns no s'envien a SIA.
He creat el públic objectiu "Empleat Públic" i he marcat la casella "Públic objectiu intern". 
He creat un procediment intern  (marcant com a públic objectiu "Empleat Públic") i no s'envia a SIA. 
Codi del procediment: 3852412
Adjunt captura del error.
![Captura](https://user-images.githubusercontent.com/26536678/64321610-29e4a980-cfc1-11e9-8ec9-8cd9c08693ed.PNG)

No obstant, amb els serveis no ha hagut problemes. He creat un servei intern i s'ha enviat correctament a SIA

**Comment by bgarcia-dgtic** [comment]
Ja està solventat. El problema era de Serveis Web que no havien afegit les propietats de sistema al fitxer de propietats.
No fa falta faceu rés.
