### ISSUE TITLE
Integración rolsac con el nuevo sistema de traducción automática (Opentrad)

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#451]
Se ha contratado una nueva empresa para la traducción de los contenidos coorporativos. Con lo que se debería integración gusite al nuevo sistema de traducción. Os envio por correo la documentación que nos facilitaron.

El anterior traductor, tenía únicamente el servicio de catalán a castellano. El nuevo permite la dupla castellano->catalán y la traducción de documentación.

De primeras nos urge la traducción de catalán al castellano para restablecer el servicio que actualmente no damos. Preveer si es más optimo hacer ambas opciones a la vez (catalán->castellano y castellano->catalán).

Pensar en limpiar bien el código del anterior sistema de traductor.
A nivel de prioridad empezar antes por sites que rolsac.

**Comment by bgarcia-dgtic** [comment]
He descarregat la branca 1.9 de ROLSAC per començar a fer proves amb el traductor, però a l'hora de comilar em dóna el següent error:

Buildfile: E:\Eclipse\workspace\ROLSAC-1.9\build.xml

BUILD FAILED
E:\Eclipse\workspace\ROLSAC-1.9\build.xml:4: Execute failed: java.io.IOException: Cannot run program "C:\Program Files\Git\bin\git.exe": CreateProcess error=2, El sistema no puede encontrar el archivo especificado

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización lo podeis revisar?

**Comment by bgarcia-dgtic** [comment]
Ja no dóna error

**Comment by bgarcia-dgtic** [comment]
He compilat i desplegat correctament.
He intentat fer la traducció d'una fitxa però em dóna el següent error:
![imatge](https://user-images.githubusercontent.com/26536678/102481763-7a6f0180-4062-11eb-9901-80aacbcd9adb.png)

i al logs mostra el següent error:
12:08:32,094 ERROR [FitxaInfBackController] FitxaBackController.traduir: El traductor no se encuentra en en contexto.

També he fet una prova de traduir un procediment i dóna el mateix error que la imatge d'abans, però al logs mostra el següent:
12:10:25,749 ERROR [CatalegProcedimentsBackController] CatalegProcedimentBackController.traduir: El traductor no se encuentra en en contexto.

**Comment by slromero-indra** [comment]
Buenas, ya está subido la solución, por favor, cuando podáis lo probáis.

Por si acaso, hay que añadir en el jboss-service.xml de rolsac los siguientes parámetros de conexión:


>                
> 		es.caib.rolsac.translatorib.user=api-tib
> 		es.caib.rolsac.translatorib.pass=XXX
> 		es.caib.rolsac.translatorib.url=http://caibter.indra.es/translatorib/api/services/traduccion/v1/texto
> 

Saludos y felices fiestas!

**Comment by bgarcia-dgtic** [comment]
Bon dia,
He descarregat les modificacions però encara dóna error. M'he assegurat que les propietats de connexió al jboss-service.xml siguin correctes.
He provat de traduir una fitxa, un servei i un procediment. Adjunto els errors:

09:27:31,997 ERROR [FitxaInfBackController] FitxaBackController.traduir: Error en al traducir ficha: com.sun.jersey.api.client.ClientHandlerException: javax.ws.rs.WebApplicationException: com.owlike.genson.stream.JsonStreamException
09:27:51,798 ERROR [CatalegServeisBackController] CatalegServeisBackController.traduir: Error en al traducir servicio: com.sun.jersey.api.client.ClientHandlerException: javax.ws.rs.WebApplicationException: com.owlike.genson.stream.JsonStreamException
09:28:02,666 ERROR [CatalegProcedimentsBackController] CatalegProcedimentBackController.traduir: Error en al traducir procedimiento: com.sun.jersey.api.client.ClientHandlerException: javax.ws.rs.WebApplicationException: com.owlike.genson.stream.JsonStreamException

**Comment by bgarcia-dgtic** [comment]
Hola,
He descarregat les darreres modificacions, però a l'hora d'empaquetar em dóna error:

[javac] E:\Eclipse\workspace\ROLSAC-1.9\output\persistence\gen-src\org\ibit\rol\sac\persistence\util\UsuarioFacadeUtil.java:21: error: package javax.rmi does not exist
    [javac]             return javax.rmi.PortableRemoteObject.narrow(objRef, narrowTo);
    [javac]                             ^
    [javac] 60 errors
    [javac] 5 warnings

BUILD FAILED
E:\Eclipse\workspace\ROLSAC-1.9\build.xml:639: The following error occurred while executing this line:
E:\Eclipse\workspace\ROLSAC-1.9\build.xml:656: The following error occurred while executing this line:
E:\Eclipse\workspace\ROLSAC-1.9\build.xml:245: The following error occurred while executing this line:
E:\Eclipse\workspace\ROLSAC-1.9\moduls\persistence\build.xml:217: Compile failed; see the compiler error output for details.

**Comment by bgarcia-dgtic** [comment]
Ja no dóna error

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la rama 1.8 con la integración de translatorib ¿podeis verificar si os está funcionando?

**Comment by sgelabert-dgtic** [comment]
No es tradueix el camp Observacions en els Tràmits d'un procediment administratiu.

**Comment by episano-dgtic** [comment]
No funciona el mòdul traductor en bloc "taxa" dels tràmits dels procediments. 
Ni el mòdul documents relacionats de la gestió de normativa.

**Comment by slromero-indra** [comment]
Buenas, la integración de Opentrad sólo cambió el servicio de traducción por la versión nueva integrándose con Opentrad. Los campos que no se traducen es porque eran parámetros que nunca se han pasado en la traducción.

Revisar los cambios que propones aumenta bastante el alcance de la tarea. Si te parece correcto, creo que sería más óptimo incorporar los cambios en una nueva tarea e incluirlo en rolsac 1.9 (y así poder cerrar una versión de rolsac 1.8).

**Comment by bgarcia-dgtic** [comment]
Hola,
He creat la issue #471 per resoldre el problema de traducció.
