### ISSUE TITLE
Anàlisi incorporació procediments/serveis comuns

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#452]
Analitzar la incorporació de procediments i serveis comuns segons terminologia SIA.

1. Des del punt de vista "extern" a ROLSAC aquests procediments comuns han d'estar associats directament a la UA arrel (Govern): SIA, Seucaib, etc.

2. L'operativa plantejada per als procediments comuns serà la següent:

  - Establir en el manteniment d'usuaris un permís específic per a determinar qui pot gestionar aquest tipus de procediments/serveis comuns.
  - A nivell de presentació en ROLSAC es podria gestionar visualment de la següent manera (només s'aplica si es tenen associats els permisos indicats anteriorment):
      - Mostrar els procediments comuns en el llistat de procediments/serveis a situar-se sobre la UA arrel.
      - Afegir un camp per indicar si un procediment/servei és comú per ROLSAC.
      - Validar en desar que el procediment/servei comú està associat a la UA arrel i que s'han permisos per realitzar l'acció.
      - Modificar el procés d'integració amb SIA per gestionar aquests procediments/serveis comuns de manera que es donin d'alta en SIA associa-dues a la UA arrel (Departament), no especificar res en centre directiu, i especificar el camp Unitat gestora del tràmit, un valor fix extret d'una property.
      - Es afegirà una propietat per indicar si aquests procediments s'envien a SIA com comuns o específics. Inicialment mitjançant aquesta propietat s'enviaran com específics, tal com es fa actualment.

**Comment by dmadronal-indra** [comment]
Buenos días,
Hemos actualizado la rama 1.8 con los cambios referente a incorporación de servicios comunes.
se debe tener en cuenta que conlleva cambios en la librería rolsacAPI, por lo que antes de actualizar la aplicación en los entornos productivos, se deberían revisar las aplicaciones dependientes para verificar que no se ven afectadas.

**Comment by bgarcia-dgtic** [comment]
Hola,
1- Si s'utilitza el navegador Chrome, els botons "Canviar Òrgan" i "Esborrar" de l'apartat dades de contacte no estan alineats. Això passa tant als procediments com als serveis. Adjunt captura.
![Captura1](https://user-images.githubusercontent.com/26536678/62194610-7e6d8700-b37a-11e9-91d3-f02bfeb22f96.JPG)

2- Quan es marca un procediment/servei com a comú, els camps "Òrgan competent per resoldre" i "Òrgan o Servei instructor" sempre mostren el literal en Català "L'organ competent per materia". Adjunt captura.
![Captura2](https://user-images.githubusercontent.com/26536678/62195036-664a3780-b37b-11e9-8d75-6b63d4c6614a.JPG)

**Comment by dmadronal-indra** [comment]
Buenos días, 
hemos procedido a solventar las problemáticas indicadas, ¿podéis revisarlo?

**Comment by sgelabert-dgtic** [comment]
Hem detectat problemes de sessió quan dos usuaris accedeixen al mateix procediment.
Adjunt log http://tn.caib.es/O0ZPXnpXb3ml
Si voleu veure un exemple, ho podeu veure amb el procediment https://dev.caib.es/rolsacback/catalegProcediments/catalegProcediments.do?itemId=3850494

**Comment by bgarcia-dgtic** [comment]
Hola,
Respecte a l'error anterior, ens hem adonat que el problema no té a veure amb el nombre de persones que accedeixen per modificar el procediment.
El problema sorgeix quan el procediment és comú i té tràmits. Quan coincideixen aquestes dues condicions, no es possible modificar les matèries ni les normatives del procediment. En el moment en que no es dona aquesta condició, es a dir, que el procediment deixa de ser comú o no té tràmits, sí que permet l'edició de les matèries i les normatives.

**Comment by dmadronal-indra** [comment]
Buenas, hemos realizado una actualización, ¿Lo podéis validar?

**Comment by episano-dgtic** [comment]
Hemos detectado que los usuarios que no tienen permisos para trabajar con los procedimientos comunes, si tratan de crear uno les sale un aviso de que no tienen permisos y luego se queda pensando. 
Pese a que les sale el aviso de que no tienen permisos, el procedimimiento se crea como común, pero en la unidad orgánica que el usuario tuviera acceso. No debería crearse. 
Para evitar que sucedan este tipo de errores, recomendamos que estos usuarios sin permiso de gestión de procedimientos comunes les aparezca el check pero deshabilitado.

**Comment by dmadronal-indra** [comment]
Hemos actualizado el proyecto para evitar el problema cuando se creaba un procedimiento/servicio sin permiso de gestión de comunes, no permitiendo seleccionar el check. 
Además, se han incluido más seguridad en el detalle como al guardar un procedimiento/servicio para bloquearlo si es común y no se tiene el permiso.

**Comment by episano-dgtic** [comment]
Okey ya no se puede crear procedimientos sin tener permiso comunes. 
Hemos detectado otro problema, se solvetó con procedimientos habituales, pero en los comunes sigue ocurriendo.
Los procedimientos comunes de futura publicación y imagino tb. pasa cuando caducan, no obtienen el código sia, en el proceso automático ocurre a las 7:00. Probablemente tb. pase a los servicios. 
Podéis tenerlos tb. en cuenta. 
![NOsia_futuraPublicacion](https://user-images.githubusercontent.com/17451683/66108317-9d7ad600-e5c2-11e9-8861-f08c4cd87f7f.gif)

**Comment by bgarcia-dgtic** [comment]
Hola,
Respecta a la darrera anotació, hem realitzat un parell de proves i funciona correctament. No faceu cas a la darrera nota.
