### ISSUE TITLE
Creació document d'integració API REST

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#453]
Hola,
Crec que actualment no hi ha un document que expliqui com integrar l'API REST. Podeu crear un document d'integració de l'API REST?

**Comment by dmadronal-indra** [comment]
Buenas hemos creado el documento de integración con el api rest.
creando el cliente para el documento detectamos un problema a la hora de retornar trámites que podría afectar a SISTRA 2, hemos aprovechado esta issue para solventar esta casuística.
