### ISSUE TITLE
Carga datos trámites del último procedimiento visitado en procedimientos sin trámites

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#454]
He detectado que si un procedimiento no tiene trámites, y previamente has visto otro procedimiento con trámites, en lugar de indicar que no tiene te muestra los trámites del último procedimiento. 

Adjunto imágenes de un procedimiento que muestra trámites no le corresponde ya que no tiene ninguno. 
![3329589_b](https://user-images.githubusercontent.com/17451683/59744651-5404b600-9273-11e9-9ce8-f0d8ae37e855.gif)
![3329589](https://user-images.githubusercontent.com/17451683/59744652-5404b600-9273-11e9-9603-38a728d98a6e.gif)

**Comment by episano-dgtic** [comment]
Acabo de detectar otro problema del mismo estilo. Si accedes a un trámite de un procedimiento, y éste trámite no tiene indicado un "Òrgan competent per a la tramitació" en lugar de estar en blanco muestra el última uo que hubieras accedido. 
![tramita_IBSALUT](https://user-images.githubusercontent.com/17451683/61358574-e56b4600-a87a-11e9-9712-631b5dab4827.gif)
![tramita_DGformacio](https://user-images.githubusercontent.com/17451683/61358575-e603dc80-a87a-11e9-8b3f-ac992987239a.gif)

**Comment by dmadronal-indra** [comment]
Buenas hemos actualizado la aplicación con los cambios solicitados, ¿podéis revisarlo?

**Comment by episano-dgtic** [comment]
correcto
