### ISSUE TITLE
Problemes a l'hora de mostrar la informació a l'excel amb l'exportació de procediments/serveis.

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#455]
Bon dia,

- Procediments: quan es realitza una exportació de procediments, la columna "NUM TRAMITS TELEMATICS", de l'excel, no té en compte els tràmits telemàtics que estan emplenats mitjançant URL, només té en compte els tràmits que estan emplenats amb el camp "identificador tràmit telemàtic" i "versió tràmit telemàtic". A l'hora de contar els tràmits telemàtics, hauria de fer-ho a través del check "Telemàtic" i no a través dels camps "url" o "identificador".

- Serveis: a l'hora de fer l'exportació de serveis, l'excel no mostra cap informació referent als canals de presentació (presencial, telemàtic, telefònic).

**Comment by dmadronal-indra** [comment]
Buenas hemos actualizado la aplicación con los cambios indicados, ¿Lo podéis validar?
