### ISSUE TITLE
Selecció plataformas de tramitació

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#457]
A fi de poder destriar entre diferents plataformes de tramitació associades al mateix catàleg d'aplicacions es sol·licita:
- Manteniment dins ROLSAC de les plataformes internes de tramitació disponibles
- Modificar els canals de presentació de les pantalles de Procediments i Serveis Administratius per poder seleccionar o bé una URL externa o bé una plataforma interna de tramitació, establient en aquest darrer cas la definició l'identificador, la versió i els paràmetres d'inici del tràmit.
- Modificar els filtres del cercadors de procediments i serveis per poder filtrar per plataforma de tramitació interna o externa, així com l'exportació a CSV

**Comment by bgarcia-dgtic** [comment]
Hola,
Ens hem adonat que als canals de presentació dels tràmits dels procediments apareix l'opció "Telefònic" i no hauria d'estar. Aquesta opció només és pels serveis. 
També hem vist que als tràmits dels procediments, el títol "Canals de presentació" apareix tres vegades. Adjunt captura de pantalla.
![Captura](https://user-images.githubusercontent.com/26536678/66186429-869bb880-e682-11e9-9097-235d1b9fdd94.PNG)

**Comment by dmadronal-indra** [comment]
Hemos actualizado el proyecto solucionando el problema de las cabeceras, además de incluir los cambios necesarios para obtener el enlace telemático de la issue 4697 de SEUCAIB

**Comment by bgarcia-dgtic** [comment]
Bon dia,

A l'hora de compilar les noves modificacions, em dona error. Us he enviat un fitxer .txt amb els errors.

**Comment by dmadronal-indra** [comment]
Buenos días, 
hemos realizado una actualización, ¿podéis volver a probar?
