### ISSUE TITLE
Comprovar si  l'API de web service pot consultar si un tràmit/servei es telemàtci o presencial

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#458]
Hola,

En referència a la incidència de Redmine #4655 de SEUCAIB, podeu verificar si l'API de web service pot consultar si un tramit/servei es telemàtic o presencial?

**Comment by dmadronal-indra** [comment]
Buenas, 
hemos realizado una actualización para incluir estas propiedades en el API. ¿Lo podéis verificar?
