### ISSUE TITLE
No funciona el botó "Mes info" de l'apartat "Indexar tots" de la sincronització amb SIA

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#459]
Quan s'accedeix a "Administració -> SIA -> Procés d'integració", a la pipella "Indexar tots" es mostren totes les indexacions amb SIA que s'han realitzat. 
El botó "Més info" que es troba a la dreta de cada indexació, no funciona. Quan es prem damunt no fa rés.

**Comment by dmadronal-indra** [comment]
Buenas, hemos realizado una actualización, ¿lo podéis verificar?
