### ISSUE TITLE
url fixa ( http://boib.caib.es/pdf/2009015/mp2.pdf) al Export de normativa camp (ENLLAÇ)

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#460]
Al excel que s'exporta indica sempre la mateixa url("http://boib.caib.es/pdf/2009015/mp2.pdf") en el camp enllaç. Hauria indicar el camp de base de datos  "enllaç a la norma" en català. 

tno_enlace de la tabla RSC_TRANOR para tnc_codidi='ca'

**Comment by dmadronal-indra** [comment]
buenas hemos actualizado la aplicacion con los cambios, ¿lo podeis validar?
