### ISSUE TITLE
Visibilitat pestanya "Crea una nova normativa"

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#462]
Es sol·licita mostrar únicament la pestanya de "Crea una nova normativa" si el gestor de ROLSAC té permís d'edició de normativa. De la mateixa manera es requereix que també s'oculti la pestanya "Traspàs del BOIB".

Es sol·licita endemés afegir el següent missatge informatiu en la pantalla de Procediment/Serveis:
"En cas de no trobar la normativa, poseu-vos en contacte amb l'administrador " + [simplificacio@caib.es]. L'adreça de correu s'ha d'extreure d'una propietat de sistema de manera que sigui configurable per entitat.

**Comment by sgelabert-dgtic** [comment]
De la mateixa manera es requereix que també s'oculti la pestanya "Traspàs del BOIB".
Es sol·licita endemés afegir el següent missatge informatiu en la pantalla de Procediment/Serveis:
"En cas de no trobar la normativa, poseu-vos en contacte amb l'administrador " + [simplificacio@caib.es]. L'adreça de correu s'ha d'extreure d'una propietat de sistema de manera que sigui configurable per entitat.

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos revisado este tema. ¿Lo podeis revisar?

**Comment by dmadronal-indra** [comment]
Buenas hemos revisado la problemática con las UA sin código dir3 y revisado la recuperación del código dir3 para que siempre recupere el código dir3 de la UA raíz.
