### ISSUE TITLE
Afegir mètode a l'API per obtenir el núm de procediments

### ISSUE THREAD

**Issue by acuevas-dgtic** [GovernIB/rolsac#463]
Actualment si volem obtenir tots els procediments a ROLSAC he de realitzar dues consultes al mètode /api/rest/v1/procedimientos, ja que no si s'indica el núm d'elements a obtenir retorna només els 30 primers. A la primera consulta obtenim la variable numeroElementos per després tornar a realitzar la mateixa consulta indicant aquest número a la petició. Feraquestes  dues consultes és ineficient: hauria d'haver un mètode per obtenir els mètodes

Exemple de JBOS obtingut:
{
    "numeroElementos": "2308",
    "status": "200",
    "resultado": [
        {
            "codigo": "2893276",
            "codigoSIA": "1161275",
            "comun": "false",
            "destinatarios": "Persones, empreses, administracions públiques que executin un projecte que impliqui la necessitat d'avaluació d'impacte ambiental ordinària",
            "dirElectronica": "jadrover@cbma.caib.es",
            "estadoSIA": "A",
            "fechaActualizacion": "2018-06-22T12:51:26+02:00",
            "fechaPublicacion": "2017-04-08T00:00:00+02:00",
            "fechaSIA": "2019-07-11T11:31:01+02:00",
            "indicador": "false",
            "iniciacion": {
                "codigo": "439059",
                "nombre": "Instància de part"
            },
            "link_familia": {
                "codigo": "4",
                "href": "http://sdevapplin5.caib.es:58080/rolsac/api/rest/rolsac/api/rest/v1/familias/4",
                "rel": "familias"
            },
            "link_organResolutori": {
                "codigo": "954",
                "href": "http://sdevapplin5.caib.es:58080/rolsac/api/rest/rolsac/api/rest/v1/unidades_administrativas/954",
                "rel": "unidades_administrativas"
            },

**Comment by sgelabert-dgtic** [comment]
Es sol·licita que el paràmetre "size" del filtre de paginació es pugui parametritzar amb un -1, retornant així tots els elements.

**Comment by sgelabert-dgtic** [comment]
Es tanca el tiquet després d'analitzar que la resposta de l'operació és suficient per als requeriement sol·licitats
