### ISSUE TITLE
El camp "URL tràmit telemàtico extern" del catàleg de serveis no permet multi-idioma.

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#464]
El camp "URL tràmit telemàtico extern"del catàleg de serveis no permet multiidioma. Amb la qual cosa només es pot incloure en català i castellà.

**Comment by dmadronal-indra** [comment]
Buenas, hemos realizado una actualización , ¿lo podéis validar?

**Comment by sgelabert-dgtic** [comment]
Seguim sense poder accedir a la URL externa en castellà configurada en els Serveis Administratius.
Us pas un exemple: https://dev.caib.es/seucaib/es/200/persones/tramites/servicio/3865413/

**Comment by slromero-indra** [comment]
Buenas, podéis desplegar de nuevo la última versión de seucaib y nos confirmáis si sigue sin verse la url en castellano?

Hemos probado en caibter y los procedimientos y servicios se ven correctamente ambos idiomas.

PROCEDIMIENTO:
http://caibter.indra.es/seucaib/es/200/persones/tramites/tramite/2749958
http://caibter.indra.es/seucaib/ca/200/persones/tramites/tramite/2749958

SERVICIO:
http://caibter.indra.es/seucaib/es/200/persones/tramites/servicio/2749979
http://caibter.indra.es/seucaib/ca/200/persones/tramites/servicio/2749979

**Comment by bgarcia-dgtic** [comment]
funciona correctament

**Comment by episano-dgtic** [comment]
Ya está los cambios en producción. Y hemos detectado que no se incluyó el script para la migración de datos de antiguo campo al nuevo campo en la tabla. Podéis actualizar los scripts?

**Comment by slromero-indra** [comment]
Buenas, hemos incorporado en los scripts un método que obtiene la url del tramite externo del campo antiguo y lo introduce en la url trámite externo de la traducción (si es nulo, para evitar si alguien ya ha introducido algún valor).
