### ISSUE TITLE
Tractament LOPD en procediments i serveis administratius

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#465]
Es sol·licita incorporar la gestió d'informació de tractament de dades de caràcter personal sobre els procediments i serveis administratius. Concretament:
- Afegir un nou menú de Legitimacio dins el menú Administració.
- Modificar les fitxes d'edició i creació de procediments administratius per incorporar una nova secció LOPD.
- Modificar les fitxes d'edició i creació de serveis administratius per incorporar una nova secció LOPD.

**Comment by sgelabert-dgtic** [comment]
Es sol·licita que el camp FINALITAT s'empleni via property amb el literal per defecte  "Tramitació del procediment" en lloc de recuperar-lo del camp OBJECTE.

**Comment by slromero-indra** [comment]
Buenas, se ha comiteado una primera versión que incluye los cambios en procedimientos y servicios para gestionar la lopd como un formulario para la gestión de LOPD Legitimación. El restapi ya incluye la nueva información y la parte soap estamos en ello. Además del soap, falta un detalle para los documentos de información adicional (falta que sólo permita pdf y permitir bajar una plantilla). 

¿Por favor, podéis pasar las plantillas que los usuarios se pueden descargar para incluirlo?

Además, necesito que me actualicéis los literales de propiedades (los caracteres raros son los valores unicodes de los acentos para que se vean bien por pantalla):
 

> 
		es.caib.rolsac.lopd.finalidad.ca=Tramitaci\u00F3 del procediment 
		es.caib.rolsac.lopd.finalidad.es=Tramitaci\u00F3n del procedimiento
		es.caib.rolsac.lopd.destinatario.ca=El destinatari de la lopd
		es.caib.rolsac.lopd.destinatario.es=El destinatario de la lopd
		es.caib.rolsac.lopd.derechos.ca=El dret de la lopd
		es.caib.rolsac.lopd.derechos.es=El derecho de la lopd
		es.caib.rolsac.lopd.responsable.comun.ca=Responsable lopd com\u00FA
		es.caib.rolsac.lopd.responsable.comun.es=Responsable lopd com\u00FAn
		es.caib.rolsac.lopd.cabecera.ca=De conformitat amb el reglament (UE) 2016/679 i la legistaci\u00F3 vigente en mat\u00E8ria de protecci\u00F3 de dades, s\u2019informa del tractament de les dades personales que cont\u00E9 aquest tr\u00E0mit
		es.caib.rolsac.lopd.cabecera.es=De conformidad con el reglamento (UE) 2016/679 y la legistaci\u00F3n vigente en materia de protecci\u00F3n de datos, se informa del tratamiento de los datos personales que contiene este tr\u00E1mite

**Comment by slromero-indra** [comment]
Si se desea instalar y probar esta versión, hay que ejecutar los sql (se recomienda actualizar los valores del rolsac_update_data por los correctos):

> rolsac_update_data_from_1.8.0_to_1.9.0.sql
> rolsac_update_schema_from_1.8.0_to_1.9.0.sql

**Comment by bgarcia-dgtic** [comment]
Hola,
He descarregat les darreres modificacions, però a l'hora d'empaquetar em dóna error:

[javac] E:\Eclipse\workspace\ROLSAC-1.9\output\persistence\gen-src\org\ibit\rol\sac\persistence\util\UsuarioFacadeUtil.java:21: error: package javax.rmi does not exist
[javac] return javax.rmi.PortableRemoteObject.narrow(objRef, narrowTo);
[javac] ^
[javac] 60 errors
[javac] 5 warnings

BUILD FAILED
E:\Eclipse\workspace\ROLSAC-1.9\build.xml:639: The following error occurred while executing this line:
E:\Eclipse\workspace\ROLSAC-1.9\build.xml:656: The following error occurred while executing this line:
E:\Eclipse\workspace\ROLSAC-1.9\build.xml:245: The following error occurred while executing this line:
E:\Eclipse\workspace\ROLSAC-1.9\moduls\persistence\build.xml:217: Compile failed; see the compiler error output for details.

**Comment by slromero-indra** [comment]
Buenas, revisamos el problema, te avisamos en cuanto lo tengamos.

**Comment by slromero-indra** [comment]
Buenas, perdón por tardar. Hemos hecho diversas pruebas compilando y no hemos tenido ningún problema. Al compilar utilizamos jdk1.8 (ya que rolsac se encuentra en un jboss5). 

Hemos realizado una prueba con openjdk11 y vemos que se genera un error similar. Podéis confirmarme si lo estáis generando con jdk11? En caso de ser así, podéis probar con jdk1.8.

Saludos!

**Comment by bgarcia-dgtic** [comment]
Hola, disculpau. Teniu raó. He compilat amb jdk 1.7_45 (és el que tenim a producció) i no dóna errors.

**Comment by slromero-indra** [comment]
Buenas, hemos comiteado todos los cambios asociados a esta issue  (en cuanto lo tengamos cerrado y testeado, subiremos los cambios pendientes de la issue 466).

Cuando podáis, necesitamos los literales de los lopd (finalidad, derechos..) y también el documento de plantilla lopd.

**Comment by bgarcia-dgtic** [comment]
Hola,
Hem pujat a DEV la versió 1.9 de ROLSAC amb els canvis de LOPD i hem trobat les següents diferències en relació al document d'estimació.

* Camps del mòdul LOPD:

	- Dret:
		Quan es crea un procediment nou, el text que apareix és el de la propietat "es.caib.rolsac.lopd.responsable.comun" en lloc del text de la propietat "es.caib.rolsac.lopd.derechos". Als serveis funciona correctament.

	- Informació adicional:
		No apareix aquest camp tant als procediments com als serveis.

	- Camps obligatoris:
		Tan si es deixa el camp "Finalitat" o "Destinatari" buit, sempre mostra el mateix error amb el text "El camp responsable és obligatori".

	- Camps no editables:
		No es distingeixen de la resta. El color de fons es blau en lloc de gris.

**Comment by slromero-indra** [comment]
Hemos comiteado los cambios respecto a los problemas detectados. 

Respecto a la información adicional, se observó que tanto el módulo de servicios como el de procedimientos no envían la información mediante un submit del formulario sino que manipulan los datos y realizan un post (de esta manera, no se pueden enviar ficheros). Teniendo en cuenta que los documentos tienen un módulo lateral, se optó por reaprovechar el módulo, adaptándolo a la información adicional del LOPD.

![imagen](https://user-images.githubusercontent.com/17451407/107247826-fc135800-6a31-11eb-9995-757c67c9e66a.png)

Cuando podáis, validad los cambios y pasadnos los literales y las plantillas.

**Comment by bgarcia-dgtic** [comment]
Hola,
Ens agradaria que el document de l'apartat "Informació adicional" apareixi abaix de l'apartat "Drets". Aquest camp ha de ser obligatori.
![imatge](https://user-images.githubusercontent.com/26536678/107500907-03a04180-6b97-11eb-840d-c8d3b2a46228.png)

També ens agradaria que el document plantilla LOPD fos editable.

**Comment by slromero-indra** [comment]
Buenas, vamos a introducir la información adicional debajo de los derechos. 

Respecto a poder gestionar las plantillas, se puede realizar de dos maneras:
- A través de las propiedades, poder poner la url (los ficheros estarían, por ejemplo, en un microsite).
- A través de una opción para gestionarlo (como la legitimación de LOPD) y su respectiva tabla para almacenar los pdfs, el cuál conllevaría bastantes horas.

¿Qué opción preferís?

**Comment by bgarcia-dgtic** [comment]
Hola,
En relació al gestionament de les plantilles, optarem per la primera opció, a través de propietats i posar una url.

**Comment by slromero-indra** [comment]
La motivación del cambio de tratar el upload del fichero ha sido un problema técnico con Rolsac tal como está construido. Se intentó realizar como estaba en la plantilla pero no hubo manera. Si se quiere cambiar el funcionamiento tenemos que ver con vosotros como se puede enfocar el tema.

Respecto a la plantilla, vamos a proceder a cambiarlo para añadir las url a través de un campo en las propiedades.

**Comment by bgarcia-dgtic** [comment]
Hola, 
Des de la OAE ens han donat el vistiplau a l'hora tenir el mòdul lateral del document LOPD. Les tasques a realitzar són:

- Hi ha d'haver un enllaç per la descàrrega d'una plantilla de PDP en format ODT (aquest enllaç ha de ser mantenible via propietat de sistema).
- S'ha d'efectuar un control sobre el tipus dels fitxer annexat i validar que només es puguin pujar PDFs (tal i com apareix al document d'estimació de la tasca).
- S'ha de controlar l'alta de procediments nous perquè no permeti canviar l'estat a "public" fins que no s'hagin emplenats tots els camps obligatoris i adjuntat el document amb informació addicional.
- S'ha de controlar la modificació de procediments existents perquè no permeti el desat de canvis sense haver emplenats tots els camps obligatoris i adjuntat el document amb informació addicional.
- S'ha de canviar el literal de la secció LOPD per "Informació sobre protecció de dades personals" en les pantalles de procediment i serveis
- Respecte al serveis s'ha de contemplar l'opcionalitat de la secció i del document LOPD, ja que no es d'aplicació en tots els casos. Endemés si la informació de PDP no es d'aplicació no s'ha de visualitzar cap graella a la Seu Electrònic.

**Comment by bgarcia-dgtic** [comment]
Hems hem adonat d'un funcionament no desitjat.
Quan s'accedix a un procediment/servei que té un document LOPD pujat i després es crea un procediment/servei nou, aquest document apareix al nou procediment/servei. Això no hauria de passar.

**Comment by slromero-indra** [comment]
Hemos comiteado los cambios que solucionan los problemas previos, validadlo cuando podáis.

El único cambio no realizado es el referente a servicios que se pospone para más adelante cuando se validen todos los cambios (ya que no es bloqueante, de esa manera podemos cerrar una versión).

Respecto al enlace para la descarga de las plantillas, las propiedades son:
               

> es.caib.rolsac.lopd.plantilla.ca=http://www.caib.es/plantillaCAT.pdf
> 		es.caib.rolsac.lopd.plantilla.es=http://www.caib.es/plantillaESP.pdf

**Comment by episano-dgtic** [comment]
Problema el caso de que se elimine el documento lopd después de haber introducido y publicado el procedimiento. Ya que el sistema te permite eliminar el documento lopd estando el procedimiiento publicado usando el hasta roja del bloque Documentos LOPD.

Por otro lado tb ocurre si se elimina el fichero entrando en documento. He hecho incluso el backoffice se muestra extraño al tener referencia en blanco en ambos idiomas. Parece que hay un documento sin documento ni título:
![documento_lopd](https://user-images.githubusercontent.com/17451683/108336854-c65e3400-71d4-11eb-8091-a17e2d655852.gif)

Se deberían controlar ambos casos, y no permitir que el procedimiento esté publicado, ya que no tienen el documento lopd. 

Esta última imagino tiene solución fuera comportamiento habitual. Porque normalmente aparece el título del documento anexo, y en plan apaño en este caso el nombre fichero.
La cosa es que si se eliminan todas las versiones idiomáticas del documento LOPD no indicara tiene uno.
Porque si está en catalán y no en castellano, ya cumple. De hecho normalmente aparecía en blanco en castellano, y se sabía hacía falta traducirlo/subir documento

**Comment by slromero-indra** [comment]
Hemos actualizado el código para que, si está el procedimiento o servicio publicado, no puedas borrar el documento tanto desde el menu lateral como una vez introducido en la gestión del documento.

**Comment by episano-dgtic** [comment]
Hay un comportamiento no deseable. Si tienes el procedimiento publicado, con documentos de lopd. Si tratas de modificar el documento  ( no eliminarlo) no te deja, y te dice que no puedes eliminar fichero. 
Podéis poner tb. en el título del módulo "Documentos LOPD" un * al final para marcar que es obligatorio.

**Comment by slromero-indra** [comment]
Buenas, están subidos los cambios, cuando podáis lo validáis.

**Comment by episano-dgtic** [comment]
perfect en dev.
