### ISSUE TITLE
Modificacions APIs REST i SOAP - LOPD

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac#466]
Es sol·licita modificar les APIs REST i SOAP de l'aplicació per poder servir la informació de LOPD a terceres aplicacions.

**Comment by slromero-indra** [comment]
El APIREST ya está actualizado, faltan los cambios de la parte SOAP.

**Comment by bgarcia-dgtic** [comment]
He revisat el funcionament del Swagger i no funciona correctament, quan es vol llistar els procediments o els serveis dóna un error 400 "La petición recibida es incorreta". De fet, no funciona cap consulta.
