### ISSUE TITLE
El camp "URL tràmit telemàtico extern" dels tràmits del catàleg de procediments no permet multi-idioma

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#467]
Al igual que a la issue #464 (El camp "URL tràmit telemàtico extern" del catàleg de serveis no permet multi-idioma), amb els procediments passa el mateix.
El camp "URL tràmit telemàtico extern"dels tràmits del catàleg de procediments,no permet multiidioma.
S'ha de tenir en compte el funcionament amb la SEU, ja que arrel de la incidència #464 a la SEU no es mostra el llistat de novetats ni els procediments/serveis d'una UA.
He obert a Redmine la issue #5430 amb relació a aquest problema.

**Comment by episano-dgtic** [comment]
Para subir la 1.8 a producción sería interesante que esta incidencia tb. estubiera hecha. Ocurre tanto a nivel de procedimimiento como servicio.

**Comment by episano-dgtic** [comment]
Podéis de paso, hacer que no aparezca por defecto un 0 en el campo  Versió tràmit telemàtic, porque así se asume será telemático aunque no lo sea. Y siempre salta un error.

**Comment by dmadronal-indra** [comment]
para tener los temas separados, podeis crear una nueva issue para este tema?

> Podéis de paso, hacer que no aparezca por defecto un 0 en el campo Versió tràmit telemàtic, porque así se asume será telemático aunque no lo sea. Y siempre salta un error.

**Comment by bgarcia-dgtic** [comment]
He creat la issue #470.

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos actualizado la aplicación para incluir la opción multiidioma en este campo. ¿Lo podeis revisar?

**Comment by episano-dgtic** [comment]
parte backoffice hecha.

**Comment by episano-dgtic** [comment]
Ya está los cambios en producción. Y hemos detectado que no se incluyó el script para la migración de datos de antiguo campo al nuevo campo en la tabla. Podéis actualizar los scripts?
