### ISSUE TITLE
Llevar el nombre màxim de caràcters dels títols de normativa

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#468]
Els títols de normativa tenen una grandària màxima de 230 caràcters, però només està limitat en la versió en català, en castellà no té límit de caràcters.
Es sol·licita que es llevi la limitació del nombre màxim de caràcters en la versió en català.

**Comment by dmadronal-indra** [comment]
Buenas, hemos revisado lo indicado, ¿lo podeis verificar?

**Comment by bgarcia-dgtic** [comment]
Bon dia,
He vist que heu augmentat el nombre de caràcters a 1024 a la versió en Català, no obstant en la versió en castellà no té límit de caràcters.
Es pot limitar també la versió en Castellà a 1024?

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización, ¿lo podeis revisar?

**Comment by bgarcia-dgtic** [comment]
Està correcte
