### ISSUE TITLE
Bug amb el traductor dels camp de LOPD

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#469]
No funciona el botó "Traduir" en els camps multidioma del bloc LOPD.
A l'apartat "Administració -> LOPD" no funciona el botó "Traduir" per a cap de les opcions.

**Comment by slromero-indra** [comment]
Hemos subido los cambios para solucionar los problemas detectados, podéis validarlo?

**Comment by episano-dgtic** [comment]
pruebas okey.
