### ISSUE TITLE
Llevar el valor per defecta "0" del camp "Versió tràmit telemàtic" dels Procediments/Serveis

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#470]
A l'apartat "Canals de presentació", sempre apareix per defecte el valor "0" al camp "Versió tràmit telemàtic". Si es vol que el tràmit sigui telemàtic i extern, sempre s'ha de llevar el "0". Molts d'usuaris no es donen compta i nomes emplenen el camp "URL tràmit telemàtic extern" i no lleven el "0", per tant a l'hora de guardar els dóna error.

**Comment by dmadronal-indra** [comment]
Buenas hemos revisado esta problemática, lo podeis verificar?

**Comment by episano-dgtic** [comment]
perfect.
