### ISSUE TITLE
Bug varis de traducció

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#471]
No funciona el mòdul traductor en bloc "taxa" dels tràmits dels procediments.
Ni el mòdul documents relacionats de la gestió de normativa.

Del bloc "Administració", tampoc funciona el traductor a:
    Apartat (sistema o generals) Perfils gestor.
    Apartat (sistema o generals) Plataforma de tramitació

D'altra banda, al fer aquestes proves en tots els mòduls. He detectat que bloc "Administració", apartat "Procediments excepcions Aportació documentació" no és funcional. Desconec des de quan no està operatiu, perquè no és un mòdul que actualment s'estigui emprant.

**Comment by slromero-indra** [comment]
Ya hemos subido los cambios que solucionan los problemas, exceptuando el problema que se comenta de bloc "taxa" del tràmits, no tenemos muy claro que sección es la que no se traduce, podèis pasarnos una captura?

Respecto a "Procediments excepcions Aportació documentació", queréis que lo quitemos?

**Comment by episano-dgtic** [comment]
El mòdul TAXA: Si indica el procediment té taxa. 
![pantallazo_Modulotaxa](https://user-images.githubusercontent.com/17451683/107341839-c7e67880-6abf-11eb-8836-fe5d050ab19c.gif)

Apareix en en el tràmit esmentat mòdul
![pantallazo_taxa](https://user-images.githubusercontent.com/17451683/107341864-cfa61d00-6abf-11eb-8f33-a58449b5ac16.gif)

**Comment by slromero-indra** [comment]
Gracias por la información, ya están comiteados los cambios, por favor, cuando podáis validad los cambios realizados.

El único cambio pendiente es si se debe quitar o no del módulo la opción de "Procediments excepcions Aportació documentació".

**Comment by episano-dgtic** [comment]
Pruebas okey, y se puede ocultar el bloque "Procediments excepcions Aportació documentació"

**Comment by bgarcia-dgtic** [comment]
Hola,
He fet una prova de traducció i funciona correctament, no obstant, quan es fa la traducció el botó "Guarda" no es posa en blau i no se sap si s'ha guardat per defecte. Si no s'espitja expressament sobre "Guarda", la traducció no queda guardada.
També he vist que el camp "Codi" no es trasllada de la versió en català a la castellana

**Comment by slromero-indra** [comment]
Buenas, incorporado el camp codi en la traducción. Además, al realizar la traducción, el botón guardar cambia de color.

**Comment by episano-dgtic** [comment]
Había hecho una prueba de traducción concienzuda.. pero ahora fallan la traducción en:
El bloque de Documentos relacionados de los Catálogo de servicios 
El bloque de Documentos relacionados de los Inventario de procedimientos

Pese a que indica que traduce correctamente.

**Comment by slromero-indra** [comment]
Hemos actualizado con los cambios comentados (ya traduce los documentos y se ha quitado la opción del menu)

**Comment by bgarcia-dgtic** [comment]
Funciona correctament
