### ISSUE TITLE
Error visualització documents relacionats serveis en el ROLSAC (backoffice)

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#472]
Si adjuntem un fitxer en documents relacionats del catàleg de serveis, i tractem d'accedir a el document des del gestor dóna un error 404.
![adjuntos_servicios](https://user-images.githubusercontent.com/17451683/107489054-79e97780-6b88-11eb-8d85-e91bbf7b7534.gif)

L'URL que es munta és
https://proves.caib.es/rolsacback/servicio/archivoServicio.do?id=3909285&lang=ca

**Comment by slromero-indra** [comment]
Ya hemos solucionado el bug, cuando podáis validad los cambios.

**Comment by episano-dgtic** [comment]
okey.
