### ISSUE TITLE
Indicar quin "LOPD Legitimació" està per defecte

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#473]
Quan accedim a "Administració -> LOPD -> Legitimació" ens apareix el llistat dels diferents "LOPD legitimacions" que hi ha, però no se sap quin és el que està per defecte. Per saber-ho s'ha d'accedir un a un. Ens agradaria que aparegués quin dels elements és el que està per defecte.

També s'ha de canviar el títol d'aquesta secció. En aquests moments apareix "LOPD" i hauria d'apareixer "Legitimació".
![imatge](https://user-images.githubusercontent.com/26536678/107508083-c80a7500-6ba0-11eb-8cf4-5e5c71b8be2c.png)

**Comment by slromero-indra** [comment]
Buenas, ya están subidos los cambios. Se incluye un pequeño comentario entre paréntesis para indicar la opción por defecto.

![imagen](https://user-images.githubusercontent.com/17451407/107636039-5a2b7f80-6c6c-11eb-9d5f-32dae8e109fe.png)
