### ISSUE TITLE
Canviar literal del mòdul "Document LOPD" dels procediments/serveis

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#476]
S'ha de canviar el literal del mòdul "Document LOPD" pel de "Documents informació sobre protecció de dades personals" als procediments/serveis.

**Comment by slromero-indra** [comment]
Además del literal, hemos cambiado algún mensaje de error para que en vez de decir 'Documentos LOPD' indique 'Documents informació sobre protecció de dades personals'.

Podéis validar los cambios?
