### ISSUE TITLE
Bug a l'hora d'agafar propietats en castellà de la LOPD

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#477]
Bon dia,
Quan es crear un procediment/servei nou i es marca com a comú, el text que apareix a l'apartat "Responsable del tractament" sempre l'agafa de la propietat de sistema "es.caib.rolsac.lopd.responsable.comun.ca". Mai agafa la propietat en castellà "es.caib.rolsac.lopd.responsable.comun.es"

**Comment by slromero-indra** [comment]
Buenas, hemos comiteado los cambios, cuando podáis lo validáis.

**Comment by bgarcia-dgtic** [comment]
Està correcte
