### ISSUE TITLE
Bug: no es desplega l'ear a l'entorn de producció

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#478]
Hola,

Hem intentat desplegar ROLSAC 1.9.0 a producció, però no ha anat bé. Pareix que es queda en un bucle quan fa el mapping de clases i consumeix les conexions de BBDD.
Els scripts de BBDD s'han executat correctament.
Hem tornat enrere el pas a producció.

**Comment by slromero-indra** [comment]
Se ha realizado las siguientes optimizaciones:
- Mejorado el método para comprobar si el servicio/procedimiento tiene info adicional incorporado y cuando se actualiza la info adicional.
- Mejorado el método para obtener el LOPD Responsable en el back (también en el SOAP) 
- Revisado el método de obtener LOPD Responsable, de momento, está comentado ya que sólo se podría observar desde seucaib (que actualmente la sección LOPD está oculta) y podría producir un consumo de memoria.

**Comment by bgarcia-dgtic** [comment]
Hola,
He descarregat les darreres modificacions.
En el backoffice, el camp "Responsable del tractament" de la LOPD d'un procediment/servei no comú, no apareix emplenat.

**Comment by slromero-indra** [comment]
Buenas, ya está subido, podéis validarlo?

**Comment by bgarcia-dgtic** [comment]
Funciona correctament

**Comment by bgarcia-dgtic** [comment]
Falta revisar el funcionament a l'hora de recuperar el LOPD responsable des de seucaib.
