### ISSUE TITLE
Bug a l'hora de recuperar la plataforma de tramitació alst tràmits dels procediments/serveis

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#480]
Revisant els logs de producció per damunt hem vist que hi ha errors. Entre d'altres i ha bastants d'errors que pareix que fan referència a l'hora de recuperar la plataforma de tramitació dels procediments/serveis.
Podeu revisar els logs per fer una depuració dels errors?

**Comment by slromero-indra** [comment]
Buenas, hemos incluido mas trazas cuando la plataforma está vacía, para saber con que datos se produce el error. Respecto al error en arxiuServlet, hemos incluido más trazas para detectar también el error.

Podéis ejecutar la siguiente sql en producción para saber el estado de los trámites?:
```
select TRA_CODI, TRA_VERSIO, TRA_IDTRAMTEL, TRA_CODPLT
 from RSC_TRAMIT
 where  ( TRA_VERSIO IS NOT NULL
     OR   TRA_IDTRAMTEL IS NOT NULL) AND TRA_CODPLT IS NULL;

```

**Comment by bgarcia-dgtic** [comment]
Us he enviat un correu amb el resultat de la consulta

**Comment by slromero-indra** [comment]
Buenas, hemos incorporado los sigiuentes cambios:
- Incluido más trazas en el error ya que es imposible detectar el problema con la info que da el log.
- Hemos detectado que aun hay tramites que tienen en version el valor 0, aunque la plataforma y el idtramiteversion están nulos. Hemos incorporado en el script un update que marca la versión a nulo si esta versión está rellena pero la plataforma y el idtramiteversion están a nulo.

**Comment by slromero-indra** [comment]
Hasta que no se suba versión de ROLSAC, no se puede ver y resolver mejor la incidencia. Para asegurarnos antes de subir, podéis ejecutar la siguiente SQL y confirmarme si se devuelve algún dato (son trámites sin código de plataforma pero con la versión y el id tramite rellenos)?
```

select *
 from RSC_TRAMIT
 where  TRA_VERSIO IS NOT NULL
     AND TRA_IDTRAMTEL IS NOT NULL
     AND TRA_CODPLT IS NULL;
```

**Comment by bgarcia-dgtic** [comment]
Hola,
He executat la instrucció sql i no ha retornat cap resultat.
Quan facem el desplegament a producció amb els darrers canvis, us aviso d'immediat.

**Comment by slromero-indra** [comment]
Buenas, podéis pasarnos los logs para seguir con el desarrollo de esta issue?

**Comment by bgarcia-dgtic** [comment]
Hola, us he enviat per correu els logs dels dies 03/05 i 04/05

**Comment by slromero-indra** [comment]
Buenas, hemos revisado los 2 logs que se desglosa de la siguiente manera:

### Fichero del 05-03 contiene 1321 Errores
   - apiArxiuServlet --> 659 (por alguna extraña razón, no se ve la traza)
   - obtenirUnitatAdministrativa --> 491
		 * 65 --> query did not return a unique result: 755 (Revisar pq se queja de duplicado, hay que ver que pasa con esta UA)
		 * 426 --> i18nLang mal introducidco
   - obtenirFitxa --> 171  (problema con el i18nLang)
   - SecurityException --> 27 errores con seycon
   - UsuarioFacadeEJB.obtenerUsuariobyUsername --> 28 (Linea 183 Error al inicializar UnitdadesAdministrativas cuando es nulo, habría que hacer un if)
   -  HtmlUtils --> 2 (Linea 53, de null pointers, habría que comprobar que el html no es nulo)
   - FichaResumenFacade.buscarFichas --> 6 (habría que revisar el método, parece que algún parámetro no se pasa en el orden correcto o no se pasa)
	 

### Fichero del 05-04 contiene  1274 errores:
   - apiArxiuServlet --> 651  (por alguna extraña razón, no se ve la traza)
   - obtenirUnitatAdministrativa --> 478
		* 76 --> query did not return a unique result: 755 (Revisar pq se queja de duplicado, hay que ver que pasa con esta UA)
                * 402 --> i18nLang mal introducidco
   - obtenirFitxa --> 108  (problema con el i18nLang)
   - SecurityException --> 26 errores de seycon
   - UsuarioFacadeEJB.obtenerUsuariobyUsername --> 28 (Linea 183 Error al inicializar UnitdadesAdministrativas cuando es nulo, habría que hacer un if)
   - HtmlUtils --> 2 (Linea 53, de null pointers, habría que comprobar que el html no es nulo)
   - FichaResumenFacade.buscarFichas --> 1 (habría que revisar el método, parece que algún parámetro no se pasa en el orden correcto o no se pasa)
	 

### Resumen.

ERRORES SENCILLOS.
Si os parece bien, nos creáis una issue para poder controlar que algún campo sea nulo.
- Se produce un error en HtmlUtils, más concretamente un null pointer al intentar sanitizar una variable que es nula.
- Se produce un error en UsuarioFacadeEJB.obtenerUsuariobyUsername  al intentar inicializar una propiedad que puede estar a nulo.

### ERRORES COMPLEJOS

**Error en ArxiuServlet**
En el arxiuServlet se produce un error y, revisando el código, por alguna extraña razón no se ven los logs (si está subida la última versión). Debería verse una serie de mensajes para identificar los archivos que se piden.

**Error con i18nLang**
Se produce una serie de peticiones con el idioma mal. Por ejemplo: _esÃƒÂƒÃ‚ÂƒÃƒÂ‚Ã‚ÂƒÃƒÂƒÃ‚Â†ÃƒÂ‚Ã‚Â’Ã_ o _cal_ o _cawordpress/wp-login.php_ entre muchos más (algunos son ids). Como no se sabe quien realiza la petición, se pueden realizar las siguientes dos acciones:
 1. Esperar a rolsac2, al adaptar las llamadas al restapi y utilizar un cliente, es dificil que el idioma se pase mal.
 2. Rescribir el valor de i18nLang a uno más acorde. Por ejemplo, si se pasa _esÃƒÂƒÃ_  pues cambiarlo a 'es'. En caso de no saber que idioma se pasa, pues directamente se pone 'ca' como idioma por defecto.

**Error en FichaResumenFacade.buscarFichas** 
Se produce un error al llamar al método de buscarFichas. Se debería de realizar pruebas para detectar con que combinación de datos se produce un error.

**Comment by dmadronal-indra** [comment]
buenas para evitar problemas, convendria cerrar esta tarea y crear issues nuevas para cada uno de los puntos que querais tratar, asi separamos las incidencias.

**Comment by bgarcia-dgtic** [comment]
Bon dia,
De moment ho deixam estar. Tancaré aquesta issue i si hem de fer una depuració obriré les issues per separat.
