### ISSUE TITLE
Habilitar check als serveis per publicar/despublicar la informació de LOPD

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#481]
És sol·licita habilitar un check als serveis de tal forma que a l'hora de marcar-lo o desmarcar-lo es mostri o no la informació relacionada amb la LOPD a la SEU.

**Comment by slromero-indra** [comment]
Ya están los cambios, cuando podáis lo validais.

Tenéis que ejecutar los siguientes SQL que están comiteados:

ALTER TABLE RSC_SERVIC ADD SER_CLOPD NUMBER(1,0);
UPDATE RSC_SERVIC SET SER_CLOPD  = 1;

Además, está activo el cálculo del LOPD Responsable (antes de subir rolsac, se debería de subir SEUCAIB).
