### ISSUE TITLE
Revisar els camps obligatoris abans de publicar un procediment/servei

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#482]
Hola,
Hem detectat que quan hi ha un procediment/servei antic publicat i que té camps obligatoris sense emplenar, permet fe canvis en els mòduls laterals. 
Hauria d'haver un control de tal forma que quan es faci algun canvi en algun modul lateral d'un procediment/servei públic, comprovi tots els camps obligatoris.

En concret el procediment 1171643 és públic, té camps obligatoris sense emplenar i han pogut modificar-lo ja que apareix a les auditories.

També s'ha de controlar que qualsevol canvi que es faci a algun mòdul lateral, quedi enregistrat a les auditories, ja que hi ha algunes modificacions que no queden enregistrades, per exemple quan es modifica un tràmit.

**Comment by slromero-indra** [comment]
Hemos subido los cambios de la issue, cuando podáis lo validáis.

¿Podéis cambiar la versión de ROLSAC de la 1.9.2 a la milestone de la 1.10?

**Comment by bgarcia-dgtic** [comment]
Funciona correctament
