### ISSUE TITLE
Bug a l'hora de cercar i mostrar tots els procediments de la UA "Govern de les Illes Balears"

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#484]
Hola,
Quan et situes a la unitat arrel "Govern de les Illes Balears" i fas una cerca de tots els procediments incloent les unitats filles, una vegada que et retorna el resultat i li dones a l'opció "Mostrar **tots** elements per pàgina", dóna l'error "S'ha produït un error de connexió. Intente-ho de nou en uns minuts".

**Comment by slromero-indra** [comment]
Estamos intentando replicarlo en nuestro entorno y no nos da ningún error. Es posible que se deba a la gran cantidad de procedimientos que tenéis, ¿podéis pasarnos el error que se debe monstrar por los logs?

**Comment by bgarcia-dgtic** [comment]
He fet un parell de proves i no dóna error. Quan torni a passar us enviaré els logs.

**Comment by slromero-indra** [comment]
Buenas, podéis cerrar la issue y volverla a abrir si surge de nuevo el problema?
