### ISSUE TITLE
Bug: no funciona el traspàs del BOIB

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#491]
Hola,
Des de fa un parell de setmanes ens han informat que el traspàs des del BOIB no funciona.
Revisant el codi i fent debugs, he observat que el problema es troba a l'hora de consultar les dades d'un edicte.
El procediment és el següent:

1. Llegeix butlletí.
2. Llegeix dades del butlletí.
3. Llegeix edicte. (Fins aquí no hi ha problema)
4. Llegir dades edicte. (Aquí és quan hi ha problemes. Quan intenta llegir, per exemple el número de registre d'un edicte, retorna null).

He parlat amb 3 digits, que és qui duia el manteniment del BOIB (ja han acabat el contracte), però no m'han pogut resoldre el problema.

Ho podeu revisar?

**Comment by slromero-indra** [comment]
- Actualizado el código para leer correctamente la info de boib

**Comment by bgarcia-dgtic** [comment]
Pareix que funciona correctament.

**Comment by bgarcia-dgtic** [comment]
He fet més proves i no acaba d'anar bé.
Només funciona per als boibs del 1 de juny de 2021 cap endavant. Els boibs anteriors, no funciona. Dóna error.

**Comment by slromero-indra** [comment]
ROLSAC obtiene las normativas a través de esta url (ejemplo pidiendo los datos del 1 de mayo): 
https://www.caib.es/eboibfront/filtrerss.do?lang=ca&resultados=10&fec_ini=01/05/2021&fec_fin=01/05/2021

De la ruta anterior, obtenemos la url para obtener la url rdf con toda la información. Hemos observado que la obtención de rdf ha cambiado en BOIB. 

El 1 de junio (funcionamiento correcto):
- URL -->  https://www.caib.es/eboibfront/ca/2021/11389
- RDF --> https://www.caib.es/eboibfront/ca/2021/11389/rdf

El 1 de mayo (se produce error):
- URL -->  https://www.caib.es/eboibfront/ca/2021/11375
- RDF --> https://www.caib.es/eboibfront/ca/2021/11375/rdf

Como se puede observar en el enlace RDF del 1 de mayo ( https://www.caib.es/eboibfront/ca/2021/11375/rdf  ) se produce un error interno de BOIB. ¿Puede cambiarlo BOIB para que no se produzca el error o bien como obtener el rdf a partir de la url?

**Comment by bgarcia-dgtic** [comment]
Bon dia,

De moment no. Hem traslladat la problemàtica als encarregats del BOIB i ho revisaran.
Estam a l'espera de que ens informin.

**Comment by dmadronal-indra** [comment]
Buenas,
Tenéis alguna novedad respecto a esta issue?

**Comment by bgarcia-dgtic** [comment]
Hola,
Pareix que el traspàs del BOIB ja funciona, he fet un parell de proves de cerques i finalitzar el procés del traspàs i ha anat bé.
