### ISSUE TITLE
Bugs control flux a producció. 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#492]
1)Hem detectat que es creen missatges de la consola sense indicar l'usuari que el genera. En proves hi ha un cas (3185855), però en producció 53. 
[mensajes_procemientos sin usuario.xls](https://github.com/GovernIB/rolsac/files/7941807/mensajes_procemientos.sin.usuario.xls)

És un problema especialment, en el cas que passi en el primer contacte del gestor amb el supervisor, ja que impedeix que el supervisor pugui respondre-li per correu electrònic. El procediment en guardar-se indica l'usuari a les auditories, i es guarda el procediment amb què aparentment no seria un problema de sessió.
No puc passar-vos logs de proves perquè ja no existeix per a aquesta data. Puc intentar-ho per a producció, si ho necessiteu per detectar com reproduir-ho.

2) Hem detectat que als missatges personalitzats pels supervisors (no automàtics) apareixen un null juntament amb la identificació del supervisor. Tot i que la registres BD no té nulls.
![error null supervisores](https://user-images.githubusercontent.com/17451683/151166575-b7080b2e-c916-44ad-b511-7e3b0dbb05ce.gif)

**Comment by slromero-indra** [comment]
Para el primero de los problemas, hemos actualizado la manera de obtener el usuario (ahora se ha centralizado y se intenta obtener bien a través del request.getRemoteUser o bien a través del username) por lo que la posibilidad de que se guarde con un usuario nulo no debería pasar.

Para evitar más esta posibilidad, se va a proceder a poner el campo como no nulo (en caso de que alguna casuística rara lo produzca, será una manera de conocer cómo puede pasar). Se debe ejecutar lo siguiente (los mensajes sin usuario, se le pondrá el valor 'Desconegut' para poder ponerlo a no nulo y tener detectados siempre cuales son):

```
UPDATE RSC_PROMSJ SET PMN_USUARIO = 'Desconegut' WHERE PMN_USUARIO IS NULL;
UPDATE RSC_SERMSJ SET SMN_USUARIO = 'Desconegut' WHERE SMN_USUARIO IS NULL;
COMMIT;
ALTER TABLE RSC_PROMSJ MODIFY PMN_USUARIO NOT NULL;
ALTER TABLE RSC_SERMSJ MODIFY SMN_USUARIO NOT NULL;
```
Respecto al punto 2, se ha controlado mejor para que no muestre el valor 'null' en la pantalla. Igualmente, podéis ejecutar la siguiente consulta y nos pasáis los resultados por privado:

```
select distinct pmn_usuario
 from rsc_promsj
 where pmn_usuario like '% - %';
 
 select distinct pmn_usuario
 from rsc_promsj
 where pmn_usuario like '% - %';
```

**Comment by slromero-indra** [comment]
Buenas, habéis podido ejecutar la sql que os hemos pasado?

```
select distinct pmn_usuario
 from rsc_promsj
 where pmn_usuario like '% - %';
 
 select distinct pmn_usuario
 from rsc_promsj
 where pmn_usuario like '% - %';
```

**Comment by slromero-indra** [comment]
Perdonad por insistir pero sobre la consulta, ha devuelto resultados?

**Comment by bgarcia-dgtic** [comment]
Hola, 
Hem executat els scripts i us he enviat un correu amb el resultat de la select.

**Comment by bgarcia-dgtic** [comment]
Hola,
Seguim tenint missatges en el que apareix el text "null"
![imagen](https://user-images.githubusercontent.com/26536678/165080428-baf864ed-c35c-4cb5-b629-197237343e3b.png)

**Comment by slromero-indra** [comment]
Buenas, se debieron quedar datos incorrectos debido a un bug que había en el js, para solucionarlo, hay que ejecutar los siguientes 2 scripts:

```
 
 update rsc_promsj
    set pmn_usuario = SUBSTR(pmn_usuario, 1, INSTR(pmn_usuario, ' ')-1)
  where pmn_usuario like '% - %';

 update rsc_sermsj
    set smn_usuario = SUBSTR(smn_usuario, 1, INSTR(smn_usuario, ' ')-1)
  where smn_usuario like '% - %';
```

**Comment by bgarcia-dgtic** [comment]
Pareix que funciona
