### ISSUE TITLE
Bug a la missatgeria del control de flux

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#493]
Hola,
S'ha detectat que si es posen dos o més interrogants seguits, és genera un text del tipus "jQuery16407818073047249646_1647244740537 ".

Exemple, si es vol enviar el missatge "Sol·licitau el canvi d'estat de publicació d'aquest procediment a reserva??" es genera el següent missatge:
"Sol·licitau el canvi d'estat de publicació d'aquest procediment a reservajQuery16407818073047249646_1647244740536"

Un altra exemple, si es vol enviar el missatge "Sol·licitau el canvi d'estat de publicació d'aquest procediment a reserva???", es genera el següent missatge:
"Sol·licitau el canvi d'estat de publicació d'aquest procediment a reservajQuery16407818073047249646_1647244740538?"

Pareix que quan hi ha dos interrogants seguits "??", genera el text "jQuery.......".

**Comment by slromero-indra** [comment]
Ya están subidos los cambios para solucionar el problema al enviar mensaje. Parece que jquery utiliza el ?? para un tema de url de callback.

**Comment by bgarcia-dgtic** [comment]
Funciona correctament
