### ISSUE TITLE
Integració amb SIA, marcar procediments i serveis com apoderable i Disponible funcionari habilitat

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#495]
Finalment l'OAE vol:

**"Disponible per apoderament"**
1.- Es registra a nivell de procediment administratiu
2.- El check és de complimentació obligatòria i està vinculat de forma automàtica al públic objectiu del procediment (Persones, Empreses i Empleat Públic = True / Administracions = False)
3.- S'estableix un control en el desat del procediment de manera que avisarà a l'usuari si aquest canvia el comportament per defecte (punt 2)
4.- El check aplica únicament a procediments administratius i en cap cas a serveis, és a dir, no és possible apoderar serveis administratius
5.- Integrar valor del check amb SIA (Si el check està marcat enviant a sia que el procedimient/servei es "apoderable"). Així aquest estaran disponibles al Registre Electrònic d'Apoderaments (REA)
6.- Incorporar camp a nivell de procediment a la Seu Electrònica

**"Disponible per funcionari habilitat"** 
1.- Es registra a nivell de procediment administratiu (no es possible fer-ho a nivell de tràmit degut a què el model de dades SIA)
2.- El check és de complimentació obligatòria, lliure i valor per defecte NULL (finalment es decideix no vincular el valor del check al canal de presentació del tràmit, ja que el procediment pot tenir N tràmits amb canals de presentació potencialment diferents)
3.- S'estableix un control en el desat del tràmit de manera que avisarà a l'usuari si es marca el tràmit amb un canal de presentació exclusivament telemàtic i alhora el check disponible per FH a nivell de procediment.
4.- El check aplica únicament a procediments administratius i en cap cas a serveis, és a dir, no és possible tramitar un servei per part d'un funcionari habilitat.
5.- De moment, no apareixera cap referència de tramitació per Funcionari Habilitat a la Seu Electrònica, tot i que l'API estarà preparada per mostrar-ho

**Comment by episano-dgtic** [comment]
Per defecte, el check apoderable ha d'estar marcat. Però si el procediment/servei està vinculat únicament al públic objectiu "Administracions" ha de desmarcar-se i no permetre's la seva activació.

**Comment by episano-dgtic** [comment]
Rea se ha integrado completamente con sia, con lo que es prioritario ya que actualmente no se puede hacer ningún apoderamiento en nuestra comunidad.

**Comment by dmadronal-indra** [comment]
Comentado por correo:
- No localizamos en la documentación de SIA, como especificar esta propiedad.  ¿Podéis consultar con SIA como indicar esta información a través del API?

**Comment by episano-dgtic** [comment]
Actualitzo la incidència amb la decisió final de l'OAE respecte a l'apoderament i la tramitació per funcionari habilitat.

**Comment by episano-dgtic** [comment]
Funcionalmente no están correctamente identificado los Públicos Objetivos. 

**REspecto al check "Disponible per Apoderat Habilitat**, debería cambiarse el literal a Disponible para apoderamiento:
Se comporta correctamente para Personas y empresas. Pero para el PO Administraciones y  PO empleado público el comportamiento es totalmente el opuesto. 
En el caso PO Administraciones
1) Se habilita por defecto apoderado, cuando debería ser al revés.
2) Continua apareciendo el mensaje "opció marcada per a Disponible per a apoderament no és l'esperada" cuando en su caso es correcto esté desmarcada. 

Para el PO empleado público:
1) Se desahabilita por defecto, cuando se debiera habilitado. 
2) Continua apareciendo el mensaje "opció marcada per a Disponible per a apoderament no és l'esperada" cuando está marcado el check. 

A nivel de código hemos detectado que se trata de identificar al PO Empresas usando el código que identifica a PO "interno" Empleado público. De ahí que se comporten ambos al revés de como debieran respecto a dicho check. 
![image](https://user-images.githubusercontent.com/17451683/216553331-7b7fa2d9-f959-46e8-a093-4d8ef64ad053.png)

![image2](https://user-images.githubusercontent.com/17451683/216553408-7e3924dc-797e-4115-82f2-c68f368b94cf.png)

**REspecto a funcionario habilitado,** funciona respecto al guardar del trámite que es lo que la petición solicita. Pero se puede saltar el control, con el guardar del procedimiento ya que no hay control a dicho nivel. Es decir que si tengo un trámite de inicio telemático únicamente, puedo indicar que esté habilitado para funcionario habilitado cuando no es deseable.

**Comment by episano-dgtic** [comment]
Hemos detectado que en el envio a sia hay errores en el envio si está el check de funcionario habilitado y no está dirigido a PO personas.
![sia_funcionarioHAbilitado_personas](https://user-images.githubusercontent.com/17451683/221169915-6992d4a6-bb46-4832-a778-782f57690a43.gif)

Con lo que se deberá añadirá una validación adicional al guardar a nivel del procedimiento. En el caso de que no se cumpla la lógica (funcionario habilitado y estar marcado PO "personas"):
1) Se mostrará un mensaje informativo  siguiente:
"Para que el procedimiento esté disponible para funcionario habilitado, es obligatorio que dicho procedimiento vaya dirigido a Personas. Con lo que se desmarcará la disponible para funcionario habilitado" con un botón aceptar. 
2) Se indicará a "no" la opción disponible para funcionario habilitado.
3) Se guardará el procedimiento.

**Comment by dmadronal-indra** [comment]
Buenas, 
Hemos realizado una actualización de la aplicación. ¿Podéis validar los cambios?

**Comment by dmadronal-indra** [comment]
Buenas,
Hemos realizado una actualización para comprobar que el PO sea administración en lugar de interno.
al actualizar la aplicación se debe especificar en el fichero de properties las siguientes propiedades, con los valores que correspondan:

```
es.caib.rolsac.publico.objetivo.personas=200
es.caib.rolsac.publico.objetivo.personas.administracion=202
```

**Comment by episano-dgtic** [comment]
Finalmente se ha decidido simplificar el control respecto al check de Apoderamiento:

1) La etiqueta en el backoffice será: "Tramitació per persona apoderada"
2) Deberá ser un campo obligatorio, y mostrarse como el de Disponible para Funcionario habilitado. En la creación marcado "cap", con opciones "si" o "no". 

![apoderamiento](https://user-images.githubusercontent.com/17451683/224946108-4367a55a-7c80-4b31-ad38-bc71a4328f44.gif)

3) Sólo habrá el mensaje de aviso que alerte de la obligatoriedad de definir el campo, si no se ha definido "si" o "no". Pero nada en función del PO elegido. 

![aviso_obligatorio](https://user-images.githubusercontent.com/17451683/224948591-dc58b63f-4dbb-45ef-958d-c677bf58371b.gif)

**Comment by episano-dgtic** [comment]
Acabo de detectar que la gestión de los PO en fichas , servicios se habia visto afectada y no es posible definirlos. Entiendo que cuando se elimine la lógica en procedimientos se resolverá.

**Comment by dmadronal-indra** [comment]
Buenas 
hemos actualizado la aplicación con lo indicado ¿lo podéis revisar?

**Comment by episano-dgtic** [comment]
En la versión [rolsac-1.12]. Continuan apareciendo mensajes de aviso opción incorrecta por público objetivo y también se cambia estado check apoderado según el po. Toda esta lógica debe desaparecer. 

![mensaje_po_incorrecto](https://user-images.githubusercontent.com/17451683/226303412-bf100aba-69a0-4d2c-a4ba-c39ac7cffc84.gif)

No se ha cambiado la etiqueta a "Tramitació per persona apoderada"

Parece es inexistente el mensaje de obligatoriedad el check apoderado. En el caso eliga PO empleado publico se desmarca, y sin acción sobre él no aparece mensaje.

Corregido el problema en del módulo lateral en servicios y fichas. 

El campo apoderamiento continua siendo un check en lugar de un desplegable, con opciones. 
![apoderado_check](https://user-images.githubusercontent.com/17451683/226303517-93fc5ab5-f46c-405e-8474-b440a900de6a.gif)

**Comment by episano-dgtic** [comment]
Ahora no está la lógica para desplegable funcionario habilitado para evitar problemas actualización sia. 

No aparece el mensaje cuando se marca como activo, y no tiene incluido el PO Personas, 
"Para que el procedimiento esté disponible para funcionario habilitado, es obligatorio que dicho procedimiento vaya dirigido a Personas. Con lo que se desmarcará la disponible para funcionario habilitado" con un botón aceptar.

**Comment by episano-dgtic** [comment]
Ahora está tal cual os habiamos especificado. Pero la oae cambia el simplifica también el criterio respecto al **funcionario habilitado**:
1) El check con las opciones (cap, si y no),  aparecerá por defecto con la opción "no", y inhabilitado para todos los gestores, con fondo gris. 
![apoderado_FH_back](https://user-images.githubusercontent.com/17451683/227467239-921bf853-354f-4d13-bcd7-a3eed339fc47.gif)

2) Se elimina todo mensaje y control de error, tanto a nivel de procedimiento como de trámite respecto al canal de presentación como de público objetivo elegido.

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la aplicación con lo indicado. ¿Podéis validarlo?

**Comment by episano-dgtic** [comment]
En la creación tanto para rol supervisor como system, el check funcionario habilitado está habilitado y se puede marcar cualquier opción. Debe estar deshabilitado siempre. 

![creación](https://user-images.githubusercontent.com/17451683/231983134-02068f78-9961-408e-8850-453847e47266.gif)


Es cierto que desde el supervisor, si se accede a un procedimiento previo, se muestra deshabilitado, y crear uno nuevo luego aparece deshabilitado. 
![super_deshabilitado_al_guardar](https://user-images.githubusercontent.com/17451683/231979017-912406d5-3112-4117-b459-67cb76e4d117.gif)

Pero parece que hubiera algo cache. Trabajando miga de pan, la cache se pierde.. y se puede replicar otra vez el problema al crear para super. 
EX: Si se pulsa miga de pan inici, y luego eliges uo tengas acceso, al crear aparece habilitado y puede marcar cualquier opción.

**Comment by episano-dgtic** [comment]
También he detectado un caso en el que salta el mensaje de FH(si) al crear trámite sólo tiene el canal telemático. 
![aviso FH, solo telematico](https://user-images.githubusercontent.com/17451683/231985686-24b7de4e-21de-4131-b829-59b8cc540d05.gif)

Se debe eliminar esta lógica mensajes.

**Comment by dmadronal-indra** [comment]
Buenas, 
hemos realizado una actualización, ¿lo podéis validar?

**Comment by episano-dgtic** [comment]
Está okey.

**Comment by episano-dgtic** [comment]
La OAE, sugiere que los desplegables aparezcan antes de check de taxa. 
![cambio_posicion](https://user-images.githubusercontent.com/17451683/235619239-3c5bbf7d-c9d3-48ad-a9e8-503c7305b540.gif)

Para ganar espacio de pantalla, hacer que silencio administrativo y fi d la via administrativa esté en dos columnas.

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la aplicación, ¿lo podéis revisar?

**Comment by episano-dgtic** [comment]
Está genial, gracias.

**Comment by episano-dgtic** [comment]
Acabamos de detectar problemas tanto en la creación inicial/modifición procedimientos con el desplegable en castellano "Tramitació per persona apoderada ", no tiene una conexión con desplegable en catalán. Auqnue se rellene sale el aviso que es un campo obligatorio, y se rellene lo que se rellene al guardar indica "cap" al refrescar.

**Comment by dmadronal-indra** [comment]
Buenas, hemos actualizado la aplicación para solventar el problema, ¿lo podéis revisar?

**Comment by bgarcia-dgtic** [comment]
Hola,
Hem detectat que el desplegable del camp "Disponible per Funcionari Habilitat" a la versió en castellà està desabilitat, la qual cosa permet la seva modificació. En la versió en català es troba deshabilitat.
Hauria de tenir el mateix funcionament que a la versió en català.

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización, ¿Lo podéis revisar?

**Comment by scalafat-dgtic** [comment]
Revisat funcionament correcte a PRO
