### ISSUE TITLE
Incorporació dels tràmits plantilla

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#496]
Es sol·licita la incorporació dels tràmits plantilla.

**Comment by bgarcia-dgtic** [comment]
Hola,
Hem pujat els canvis a DEV però no acaba d'anar bé. Quan intentam accedir a un procediment o servei dóna error.
Us he enviat un correu amb els logs.

**Comment by slromero-indra** [comment]
Buenas, hemos comiteado lso cambios (cuando podáis, lo validáis).

Vamos a proceder a actualizar seucaib para que obtenga los datos de la version 1.11 de rolsacAPI (sino puede producir un error al obtener los datos de un procedimiento/trámite y no entender el nuevo campo idPlantilla)

**Comment by slromero-indra** [comment]
Buenas, se han creado dos nuevas tablas, tenéis que darle permisos (creo que al usuario www_rolsac). 

Desde el usuario que tenga las tablas (que supongo que es rolsac), debéis darle permisos al usuario que se utiliza (supongo que www_rolsac):
```
GRANT all on RSC_TRATPA to www_rolsac;
GRANT all on RSC_TRAMPL to www_rolsac;
```


Luego en www_rolsac, debéis crear los sinónimos:
```
create synonym RSC_TRATPA for rolsac.RSC_TRATPA;
create synonym RSC_TRAMPL for rolsac.RSC_TRAMPL;

```

**Comment by slromero-indra** [comment]
Rectifico, parece que el problema es otro, os avisamos en cuanto lo tengamos claro, parece un problema de valores nulos.

**Comment by slromero-indra** [comment]
El problema se debía a que los scripts incluía el campo nombre (que se decidió pasar mejor a una traducción). Ya está actualizado el script.

En la base de datos donde ya se haya ejecutado el script, hay que ejecutar la siguiente sql:
`ALTER TABLE RSC_TRAMPL DROP COLUMN TPA_NOMBRE;
`

**Comment by slromero-indra** [comment]
Además de solucionar el problema en la issue 493, se ha subido un pequeño cambio en esta issue ya que había un bug al recuperar los datos desde sistra2.

**Comment by bgarcia-dgtic** [comment]
Hola, pareix que va bé, llevat d'una coseta.
A l'hora de crear/modificar els tràmits plantilla, el camp "Parámetros" no  ha de ser obligatori.

**Comment by bgarcia-dgtic** [comment]
Hola, hem detectat que als serveis no funciona correctament.
Quan es selecciona un tràmit plantilla, només es deshabilita el camp "Parámetros" i s'haurien de deshabilitar tots. A l'hora de guardar dóna un error de "null".

**Comment by episano-dgtic** [comment]
Dos cosas relacionadas, al no haber habilitado una opción independiente para la personalización manual de la tramitación telemática:
1) Cambiaría la etiqueta "Selecció tràmit telemàtic" a "Selecció plantilla tràmit telemàtic". Y la opción por defecto en lugar de "Tria una opció"a (Tria opció "personalizado")
2) Al crear un trámite nuevo, si anteriormente elegiste un "trámite plantilla" no están habilitados los campos de personalización (identificación, versión, plataforma)
![plantilla](https://user-images.githubusercontent.com/17451683/163962280-da412622-4392-4e08-af3f-7a7cd037d9ab.jpg)
Ahora para que se habilite, es necesario elegir una plantilla, para volver a "tria una opció"

**Comment by episano-dgtic** [comment]
Más bugs: el filtro del buscador para encontrar los procedimientos con una plantilla concreta no filtra en ningún caso. 
No consigo forzar las envia a sia manualmente en el bloque indexar pendents.
![indexar_pendent](https://user-images.githubusercontent.com/17451683/164216488-6c31d213-8338-4b2e-8d71-04c850744a18.gif)

**Comment by slromero-indra** [comment]
Buenas, está actualizado los literales y el buscador funciona correctamente cuando se selecciona una plantilla.

Respecto al punto 2, al crear un trámite nuevo, creemos que sale deshabilitdo porque no se ha seleccionado la opción 'telemático' para que se activen.

Respecto al envío a SIA, ¿Qué error se produce, es error javascript o java? Nos podéis pasar el log con el error (creemos que el error seguramente sea otro distinto a esta issue, por lo que se debería de generar una issue nueva con el error)

**Comment by bgarcia-dgtic** [comment]
Hem pujat els canvis i hen detectat el següent:

1. La sincronització amb SIA funciona. Pareix que ha sigut puntual.
2. La part de serveis no està feta, falta el segënt:
    - Canviar els literals.
    - Quan es selecciona un tràmit plantilla, només es deshabilita el camp "Parámetros" i s'haurien de deshabilitar tots.
    - El filtre del cercador per trobar serveis amb algun tràmit plantilla, no funciona. No filtre en cap cas.
    - A l'hora de guardar un servei que seleccionat un tràmit plantilla dóna un error "null".
 
![imagen](https://user-images.githubusercontent.com/26536678/165475120-d2633b82-3669-4bee-8659-f7f84ac3fd4d.png)

**Comment by bgarcia-dgtic** [comment]
Perdonau, ignorau la part de la implementació dels tràmits plantilla als serveis ja que al darrer document d'anàlisi així ho indica.
Per tant, s'ha de llevar el selector de tràmits plantilla i el filtre del cercador.
![imagen](https://user-images.githubusercontent.com/26536678/165498293-4e5a9922-44bd-484b-ac22-1582118ba864.png)
![imagen](https://user-images.githubusercontent.com/26536678/165498415-189f9ec1-907e-43ff-b879-40340a46d955.png)

**Comment by bgarcia-dgtic** [comment]
Funciona correctament

**Comment by bgarcia-dgtic** [comment]
Arrel dels darrers canvis, quan s'accedeix a la SEU no es veuen les novetats.
Us he enviat un correu amb els logs

**Comment by slromero-indra** [comment]
Se realizó un pequeño cambio en la parte de servicios del SOAP de rolsac (seguramente de ahí el error en el listado de servicios), por lo que seguramente haya que volver a generar de nuevo seucaib con la librería rolsacAPI actualizada, ¿el error se produce en seucaib sin la librería actualizada o con la librería actualizada?

**Comment by bgarcia-dgtic** [comment]
Hola, l'error s'ha produit amb la llibreria actualitzada. Actualment està utilitzant rolsacAPI 1.11.0

**Comment by slromero-indra** [comment]
Hemos revisado el código y creemos que puede ser porque exista algún servicio con check de lopd activo a nulo (en vez de false o true). Podéis ejecutar esta sql para ver cuantos elementos hay?:
```
 select *
 from rsc_servic
 where ser_clopd is null;
```
 
Si os parece bien, se actualizarán todos ellos de nulo a false (valor 0):
`       update rsc_servic   set ser_clopd = 0   where ser_clopd is null;`
  o bien los podéis tocar a mano (cambiando VALOR_SER_CODI por el código del servicio):
    http://www.caib.es/rolsacback/catalegServeis/catalegServeis.do?itemId=VALOR_SER_CODI

Luego, hay que poner el valor por defecto a 0(falso):
`alter table rsc_servic modify ser_clopd default 0;`

**Comment by bgarcia-dgtic** [comment]
Hola,
He llançat la consulta `select *
 from rsc_servic
 where ser_clopd is null;` i no ha retornat cap resultat.

**Comment by bgarcia-dgtic** [comment]
Perdonau,
Ja funciona correctament. No havia tornat a empaquetar SEU després de la darrera actualització.
Ara mostra l'apartat novetats i qualsevol llistat que inclogui serveis.

**Comment by bgarcia-dgtic** [comment]
Hola, 
Ens hem adonat que falta vincular el tràmit plantilla a la "Fase del procediment"
A la part d'administració dels tràmits plantilla falta afegir el selector de "Fase del procediment".
El selector de tràmit telemàtic de l'apartat "Canals de presentació" hauria de filtrar d'acord a la fase del procediment i presentar únicament els tràmits plantilla associats a cada fase ordenats alfabèticament per plataforma.
Abanda d'això i degut a que el nombre de tràmits plantilla pot ser elevat, seria eficient poder filtrar els tràmits plantilla per text, es a dir, que al selector es pugui escriure text per així filtrar-lo per aquest text.

**Comment by slromero-indra** [comment]
Hemos incorporado la fase en la plantilla (además, dependiendo del tipo de fase de la plantilla, el desplegable de plantillas varía).

Se ha actualizado la sql, para incorporar el cambio de la columna, hay que ejecutar lo siguiente:

```
/** El valor 1 corresponde a la fase iniciacion. Pondría todas las plantillas creadas en la fase de iniciacion: **/
alter table RSC_TRAMPL add TPA_FASE NUMBER(2,0) DEFAULT 1;
UPDATE RSC_TRAMPL SET TPA_FASE = 1;
COMMIT;
alter table RSC_TRAMPL MODIFY TPA_FASE NOT NULL;
```


Estamos viendo una manera más correcta de seleccionar una plantilla sin utilizar el desplegable (por si el número de plantillas fuese muy elevado), en cuanto veamos cómo, os avisamos.

**Comment by bgarcia-dgtic** [comment]
Funciona correctament

**Comment by slromero-indra** [comment]
Hemos actualizado el desplegable con un componente para poder introducir el campo texto, ya que nos comentasteis la posibilidad que la cantidad de plantillas fuese muy elevada.

**Comment by bgarcia-dgtic** [comment]
Pareix que funciona correctament

**Comment by bgarcia-dgtic** [comment]
Hola, ens hem adonat que el filtre del cercador dels tràmits plantilla, només té en compte els de la fase d'inici. Els de la fase d'instrucció i finalització no els té en compte.

**Comment by slromero-indra** [comment]
Actualizado, ahora el filtro incluye todos las plantillas (incluida los de fase de instruccion y finalizacion)

**Comment by bgarcia-dgtic** [comment]
Funciona correctament

**Comment by bgarcia-dgtic** [comment]
A l'hora d'executar l'script "rolsac_update_schema_from_1.10.0_to_1.11.0.sql" ens ha donat error. Es veu que a l'hora de crear la taula RSC_TRAMPL dóna error a la columna "TPA_FASE" ja que no permet crear la columna com a "not null" i "defaultt 1" al mateix temps. 
Hem agut de crear la taula amb la columna "TPA_FASE" només amb el "default 1" i després executar un altra script amb la sentència "alter table RSC_TRAMPL MODIFY TPA_FASE NOT NULL;"

També ens hem adonat que a l'escript "rolsac_creat_schema.aql" no s'ha afegit el codi per crear les taules "RSC_TRAMPL" i "RSC_TRATPA".

Podeu afegir aquestes modificacions?

**Comment by bgarcia-dgtic** [comment]
Ens hem adonat que a l'hora de crear un tràmit nou d'un procediment, inicialment el check "Telemàtic" de canals de presentació està deshabilitat i el desplegable per seleccionar el tràmit plantilla està habilitat. 
Hauria d'estar deshabilitat, perquè si es selecciona una plantilla i posteriorment es seleccionar l'opció "Elige opción personalizado" els altres camps "URL", "Identificador", "Versió", "Plataforma" i "Paràmetres" s'habiliten i no haurien d'habilitar-se.

**Comment by bgarcia-dgtic** [comment]
Hola, s'ha de canviar el literal "tria opció personalitzada" per "Tràmit personalitzat" del desplegable per sel·leccionar un tràmit plantilla.

**Comment by slromero-indra** [comment]
Hemos realizado los siguientes cambios solicitados:

- Amplicado el tamaño del desplegado y actualizado el literal. 
- Actualizado la sql como nos habías solicitado.
- Se ha revisado el desplegable de plantilla salga disabled cuando se crea un trámite.

Respecto a la sql, comentáis "no s'ha afegit el codi per crear les taules "RSC_TRAMPL" i "RSC_TRATPA". A que os referís con ésto? No sé si os referís a la sql para dar permisos al usuario www_rolsac y después crear un sinónimo que está en la sql "rolsac_update_schema_from_1.10.0_to_1.11.0.sql":

```
/** grants hacia www_rolsac
GRANT all on RSC_TRATPA to www_rolsac;
GRANT all on RSC_TRAMPL to www_rolsac;
**/

/** en el usuario www_rolsac ejecutar
create synonym RSC_TRATPA for rolsac.RSC_TRATPA;
create synonym RSC_TRAMPL for rolsac.RSC_TRAMPL;
*/
```

**Comment by bgarcia-dgtic** [comment]
Funciona correctament.

Pel que fa al comentaria sobre les taules "RSC_TRAMPL" i "RSC_TRATPA", ens referim a que si executam el fitxer "/scripts/bbdd/1.11/oracle/rolsac_creat_schema.aql" per una instal·lació nova de ROLSAC, aquestes taules no es creen. També passa a l'script de Postgres.

**Comment by bgarcia-dgtic** [comment]
Hola,
Hem detectat que quan es crea un tràtmit nou i es marcar el check "Telemàtic", inicialment el desplegable dels tràmits plantilla, mostra totes les plantilles (fase d'inici, instrucció i finialització) enlloc de només mostrar les de la fase d'inici ja que és l'opció per defecte quan es cree un tràmit nou.

**Comment by episano-dgtic** [comment]
También he detectado que el botón "Borrar" de la pestaña "Cercador" no resetea el campo 
Plantilla de tràmit a "cap
![reseteo](https://user-images.githubusercontent.com/17451683/171361930-3de3df38-a29f-439b-beba-1f88b92a6c57.gif)
"

**Comment by slromero-indra** [comment]
Hemos subido los cambios para solucionar lo del botón borrar y los scripts de creación actualizados

**Comment by bgarcia-dgtic** [comment]
Falta fer la part de que quan es crea un tràtmit nou i es marcar el check "Telemàtic", inicialment el desplegable dels tràmits plantilla, mostra totes les plantilles (fase d'inici, instrucció i finialització) enlloc de només mostrar les de la fase d'inici ja que és l'opció per defecte quan es cree un tràmit nou.

**Comment by dmadronal-indra** [comment]
Hemos actualizado la aplicación, ¿podéis verificar que os está funcionando correctamente?

**Comment by bgarcia-dgtic** [comment]
Funciona correctament
