### ISSUE TITLE
BUG greu per a internet explorer 11 y anteriores, al control de flux

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac#501]
A Internet explorer11 no funciona el control, de canvi estat. Els apareixen tots els estats possibles en crear procediments.

Per tant, els gestors poden canviar l'estat sense control. Fins i tot podrien eliminar un procediment hagués estat publicat i amb sia, si prèviament canvien a l'estat intern.

![explorer_modificar](https://user-images.githubusercontent.com/17451683/202149945-c43b4a45-1d0c-4d19-b5a3-78ebac825f64.png)
![Mozilla](https://user-images.githubusercontent.com/17451683/202149954-f400314b-13bb-43d5-bd91-62310cfcb173.png)
![explorer_guardarInicial](https://user-images.githubusercontent.com/17451683/202149960-0f703466-bb3e-4ef3-b4d8-cc57155fb1e0.png)

**Comment by dmadronal-indra** [comment]
buenas tardes,
Hemos realizado una actualización que solventa el problema, ¿lo podéis revisar?

**Comment by episano-dgtic** [comment]
En el caso de modificación va bien, ya no permite el cambio de estado . Pero en dicho navegador, si crean un procedimiento o servicio nuevo por defecto lo crean en estado "publico" y posteriormente pueden modificarlo manteniendo estado público. 

En los servicios, el problema se mantiene tanto la creación como en la modificación, que tienen vía libre para definir el estado.

**Comment by dmadronal-indra** [comment]
buenas tardes,
Hemos realizado una actualización que solventa el problema, ¿lo podéis revisar?

**Comment by bgarcia-dgtic** [comment]
Hola,
Hem fet proves i no acaba d'anar del tot bé en els procediments, pareix que s'acumulen els estats. Es a dir, a mida que vaig obrint procediments, el llistat dels possibles estats va augmentant. Adjunto captura.
![imatge](https://user-images.githubusercontent.com/26536678/203532517-f02848a0-7e97-4289-bbd5-751598d45c1c.png)

**Comment by dmadronal-indra** [comment]
buenas tardes,
Hemos realizado una actualización que solventa el problema, ¿lo podéis revisar?

**Comment by episano-dgtic** [comment]
Sip, ahora se evita puedan saltarse el control de flujo. 
Lo que el mensaje aviso, es preferible recomendar mozilla en lugar del edge. 
Informaros que me han confirmado que en febrero del 2023 el explorer dejará de estar en los ordenadores cooporativos del govern.
