### ISSUE TITLE
Bug No es mostren els tràmits RSS

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac#502]
Quan intentem accedir als tràmits RSS de la web https://www.caib.es/govern/rss.do?lang=ca, no retorna resultats.
Revisant el codi pareix que és un problema de l'api SOAP a l'hora de llistar els procediments.
Us envio un correu amb l'error al log.

**Comment by bgarcia-dgtic** [comment]
Es un problema de WEBCAIB, sha d'actualitzar la versió de ROLSAC al pom.

**Comment by dmadronal-indra** [comment]
Se ha revisado el api de rolsac y realizado multiples pruebas, funciona correctamente, Revisando el código de webcaib vemos que habría que actualizar las librerías de sacapiclient de webcaib.
