### ISSUE TITLE
Millora/Bugfix - Enllaçar "adreça web externa" de UA amb SEU

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac#507]
El camp "Adreça web externa" de les Unitats Administratives a ROLSAC1 no acaba de funcionar del tot bé. Es poden introduir dades però no queden desades i, si ho afegim per BD, no es mostra el valor que tocaria des de la UA en qüestió. Es demana arreglar-ne el comportament i que es desi correctament a BD.

![image](https://github.com/user-attachments/assets/014c2fd1-7613-4f36-86d9-e008893fe3a0)

A més, es vol que la URL en qüestió sigui visitable des del botó "Visitar website" de l'organigrama de SeuCAIB. 

![image](https://github.com/user-attachments/assets/9c803fc0-029b-405c-9fa7-f0617154ab98)

**Comment by dmadronal-indra** [comment]
Buenos días,
Hemos actualizado tanto ROLSAC como la SEDE para incluir estos cambios, ¿lo podéis revisar?
