### ISSUE TITLE
Modificar el mètode /procedimientos de l'API REST de ROLSAC1

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac#508]
Des de la OTAE ens sol·liciten si se pot modificar el mètode /procedimientos de l'API REST de ROLSAC1 per poder afegir els filtres de cerca per els camps:

- disponibleApoderadoHabilitado
- disponibleFuncionarioHabilitado

**Comment by dmadronal-indra** [comment]
Buenas, hemos añadido los filtros indicados en el api rest.
disponibleApoderadoHabilitado
disponibleFuncionarioHabilitado

¿Podéis validarlo?

**Comment by scalafat-dgtic** [comment]
OTAE nos indica que reciben la información que necesitaban.
