### ISSUE TITLE
Canvi etiquetes pantalla gestió de procediement

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/rolsac#6]
Numero: 575
Creació: 2016-02-12 08:48:57.820
En la pantalla de gestió de procediments s'ha de canviar:
* Etiqueta "Organisme responsable" per "Òrgan o Servei instructor"
* En l'apartat Informadors, l'etiqueta "Responsable" per "Responsable del procediment (cap del servei o secció que gestiona el procediment)

**Comment by sgelabert-dgtic** [comment]
- Etiqueta "Família" per "Tipus de procediment"
