### ISSUE TITLE
Fusionar camps "Termini màxim per Resoldre" - "Termini per resoldre i notificar"

### ISSUE THREAD

**Issue by kitanibaladmin** [GovernIB/rolsac#8]
Numero: 574
Creació: 2016-02-12 08:11:06.769
Eliminar el camp "Termini màxim per notificar" de la pantalla de gestió de procediments.
Canviar l'etiqueta del camp "Termini màxim per Resoldre" per "Termini per resoldre i notificar"
Preparar script de BBDD per detectar incoherències entre els camps TPR_NOTIFICACIO i TPR_RESOLUCIO de la taula RSC_TRAPRO, i actualitzar el camp TPR_RESOLUCIO amb la informació de TPR_NOTIFICACIO en el cas que no hi hagi incoherència de dades.
Es deixa per una segona fase l'eliminació del camp TPR_NOTIFICACIO en BBDD i de les classes de model ROLSAC.

**Comment by kitanibaladmin** [comment]
sgelabert-dgtic
2016-02-12 08:50:00.887000
- **status**: new --> assigned
- **assigned_to**: David Madroñal

**Comment by slromero-indra** [comment]
Buenas, hemos estado revisando los campos y se ha observado que ambos textos son de campo texto. Revisando el contenido, de los aproximadamente 7000 valores, sólo unos 1000 valores son el campo notificación y resolución son distintos. 

Necesitamos que nos resolváis dos dudas:
 - La primera es si cuando os referís a que hay incoherencia de datos es cuando ambos campos son distintos?
 - La segunda es si cuando se actualice el campo tpr_resolución, debe ser sustituido totalmente por tpr_notificación o debe ser concatenado (por ejemplo, cuando ambos valores son distintos).

Saludos!

**Comment by episano-dgtic** [comment]
Con datos en real de  1833 procedimientos, en catalán:
          con ambos campos iguales(1089) ó null alguno(318) 1407, 
          diferentes 248

He hablado con calidad y finalmente el campo que va a misa es el tiempo de resolución. Independientemente de lo que se indique en el campo de notificación, aunque el de notificación esté informado y el de resolución no.

**Comment by mcgonzalezu-indra** [comment]
Buenas, por tanto, viendo que finalmente calidad da por bueno el campo tiempo de resolución, se eliminará el campo tiempo de notificación (no realizaremos ningún script de actualización de campos, simplemente eliminaremos el campo tiempo de notificación) tanto de la base de datos como de la interfaz.

**Comment by episano-dgtic** [comment]
No eliminéis el campo notificación, en una segunda fase se eliminarán los datos que tuviera. De esa forma se puede proceder a posibles correcciones individuales, si los gestores no actualizaron previamente los datos correctamente.

**Comment by episano-dgtic** [comment]
Eso si.. podéis eliminar del interfaz el campo notificación.

**Comment by sgelabert-dgtic** [comment]
Finalment decidim que en una primera fase:
- El camp de notificació es deixa a la BBDD per no perdre la informació inconsistent entre els dos camps. Els scripts de BBDD del projecte tindran aquests canvis comentats.
- A nivell de pantalla de gestió de procediments, el camp ha de desaparèixer del backoffice.
- A nivell d'API es seguirà servint aquest camp, a fi de mantenir la coherència entre les versions 1.2 i 1.3 de l'aplicació.

**Comment by sgelabert-dgtic** [comment]
Falta traducció del text de control d'obligatorietat en el properties multiidioma en català

12:51:37,163 ERROR [Engine] ApplicationDispatcher[/rolsacback] Servlet.service() for servlet jsp threw exception
javax.servlet.jsp.JspTagException: No message found under code 'tramit.formulari.termini.obligatori' for locale 'ca'.
